
--These tables are used for unique creations only (no national wonders!).
--Everything here is either created by a great person or placed by some specific game mechanic.
--Prereqs are controled entirely in EaActions.

CREATE TABLE EaWonders ('ID' INTEGER PRIMARY KEY AUTOINCREMENT,
						'Type' TEXT NOT NULL UNIQUE,
						'Description' TEXT DEFAULT NULL,
						'BuildingType' TEXT DEFAULT NULL,
						'ImprovementType' TEXT DEFAULT NULL,	--not used yet
						'EaAction' TEXT DEFAULT NULL,
						'IconIndex' INTEGER DEFAULT NULL,
						'IconAtlas' TEXT DEFAULT NULL);
						--Wonders are always associated with a specific iPlot (city iPlot if it is a city wonder) and can change ownership
						--gWonders[ID] = nil or {mod, iPlot} for built wonders
						--or, gWonders[ID][ID2] = {iPlot, ...} if it is a special instance wonder (ID2 is iPerson for Arcane Tower)

CREATE TABLE EaEpics (	'ID' INTEGER PRIMARY KEY AUTOINCREMENT,
						'Type' TEXT NOT NULL UNIQUE,
						'Description' TEXT DEFAULT NULL,
						'EaAction' TEXT DEFAULT NULL,
						'IconIndex' INTEGER DEFAULT NULL,
						'IconAtlas' TEXT DEFAULT NULL);
						--Epics are always associated with a specific iPlayer and never change ownership
						--gEpics[ID] = nil or {mod, iPlayer} for created epics

CREATE TABLE EaArtifacts ('ID' INTEGER PRIMARY KEY AUTOINCREMENT,
						'Type' TEXT NOT NULL UNIQUE,
						'Description' TEXT DEFAULT NULL,
						'ItemClass' TEXT DEFAULT NULL,
						'EaAction' TEXT DEFAULT NULL,
						'IconIndex' INTEGER DEFAULT NULL,
						'IconAtlas' TEXT DEFAULT NULL);
						--Items can move around and may be associated with a plot (if in city or dropped somewhere), a GP or a non-GP unit
						--gArtifacts[ID] = nil or {mod, iPlayer, locationType, locationIndex}, where locationType = "iPlot", "iPerson", or "iUnit"
						--note: if Players[iPlayer]:GetUnitByID(iUnit) == nil then artifact will become lost for a while

INSERT INTO EaWonders (Type,			Description,						BuildingType,				EaAction)					--only World unique belong in this table
SELECT 'EA_WONDER_STANHENCG',			'TXT_KEY_EA_WONDER_STANHENCG',		'BUILDING_STANHENCG',		'EA_ACTION_STANHENCG'		UNION ALL
SELECT 'EA_WONDER_KOLOSSOS',			'TXT_KEY_EA_WONDER_KOLOSSOS',		'BUILDING_KOLOSSOS',		'EA_ACTION_KOLOSSOS'		UNION ALL
SELECT 'EA_WONDER_MEGALOS_FAROS',		'TXT_KEY_EA_WONDER_MEGALOS_FAROS',	'BUILDING_MEGALOS_FAROS',	'EA_ACTION_MEGALOS_FAROS'	UNION ALL
SELECT 'EA_WONDER_HANGING_GARDENS',		'TXT_KEY_EA_WONDER_HANGING_GARDENS','BUILDING_HANGING_GARDENS',	'EA_ACTION_HANGING_GARDENS'	UNION ALL
SELECT 'EA_WONDER_UUC_YABNAL',			'TXT_KEY_EA_WONDER_UUC_YABNAL',		'BUILDING_UUC_YABNAL',		'EA_ACTION_UUC_YABNAL'		UNION ALL
SELECT 'EA_WONDER_THE_LONG_WALL',		'TXT_KEY_EA_WONDER_THE_LONG_WALL',	'BUILDING_THE_LONG_WALL',	'EA_ACTION_THE_LONG_WALL'	UNION ALL
SELECT 'EA_WONDER_CLOG_MOR',			'TXT_KEY_EA_WONDER_CLOG_MOR',		'BUILDING_CLOG_MOR',		'EA_ACTION_CLOG_MOR'		UNION ALL
SELECT 'EA_WONDER_DA_BAOEN_SI',			'TXT_KEY_EA_WONDER_DA_BAOEN_SI',	'BUILDING_DA_BAOEN_SI',		'EA_ACTION_DA_BAOEN_SI'		UNION ALL
SELECT 'EA_WONDER_GREAT_LIBRARY',		'TXT_KEY_EA_WONDER_GREAT_LIBRARY',	'BUILDING_GREAT_LIBRARY',	'EA_ACTION_GREAT_LIBRARY'	UNION ALL
SELECT 'EA_WONDER_ARCANE_TOWER',		'TXT_KEY_EA_WONDER_ARCANE_TOWER',	NULL,						'EA_ACTION_ARCANE_TOWER'	;

UPDATE EaWonders SET IconIndex = (SELECT IconIndex FROM EaActions WHERE EaWonder = EaWonders.Type);
UPDATE EaWonders SET IconAtlas = (SELECT IconAtlas FROM EaActions WHERE EaWonder = EaWonders.Type);
--UPDATE EaWonders SET Description = (SELECT Description FROM EaActions WHERE EaWonder = EaWonders.Type);

INSERT INTO EaEpics (Type,				Description,						EaAction)	--world uniques only
SELECT 'EA_EPIC_VOLUSPA',				'TXT_KEY_EA_EPIC_VOLUSPA',			'EA_ACTION_EPIC_VOLUSPA'			UNION ALL
SELECT 'EA_EPIC_HAVAMAL',				'TXT_KEY_EA_EPIC_HAVAMAL',			'EA_ACTION_EPIC_HAVAMAL'			UNION ALL
SELECT 'EA_EPIC_VAFTHRUTHNISMAL',		'TXT_KEY_EA_EPIC_VAFTHRUTHNISMAL',	'EA_ACTION_EPIC_VAFTHRUTHNISMAL'	UNION ALL
SELECT 'EA_EPIC_GRIMNISMAL',			'TXT_KEY_EA_EPIC_GRIMNISMAL',		'EA_ACTION_EPIC_GRIMNISMAL'			UNION ALL
SELECT 'EA_EPIC_HYMISKVITHA',			'TXT_KEY_EA_EPIC_HYMISKVITHA',		'EA_ACTION_EPIC_HYMISKVITHA'		;

UPDATE EaEpics SET IconIndex = (SELECT IconIndex FROM EaActions WHERE EaEpic = EaEpics.Type);
UPDATE EaEpics SET IconAtlas = (SELECT IconAtlas FROM EaActions WHERE EaEpic = EaEpics.Type);
--UPDATE EaEpics SET Description = (SELECT Description FROM EaActions WHERE EaEpic = EaEpics.Type);

--Tomes
INSERT INTO EaArtifacts (Type,				Description,							ItemClass,	EaAction)
SELECT 'EA_ARTIFACT_TOME_OF_EQUUS',			'TXT_KEY_EA_ARTIFACT_TOME_OF_EQUUS',		'Tome',		'EA_ACTION_TOME_OF_EQUUS'			UNION ALL
SELECT 'EA_ARTIFACT_TOME_OF_BEASTS',		'TXT_KEY_EA_ARTIFACT_TOME_OF_BEASTS',		'Tome',		'EA_ACTION_TOME_OF_BEASTS'			UNION ALL
SELECT 'EA_ARTIFACT_TOME_OF_THE_LEVIATHAN',	'TXT_KEY_EA_ARTIFACT_TOME_OF_THE_LEVIATHAN','Tome',		'EA_ACTION_TOME_OF_THE_LEVIATHAN'	UNION ALL
SELECT 'EA_ARTIFACT_TOME_OF_HARVESTS',		'TXT_KEY_EA_ARTIFACT_TOME_OF_HARVESTS',		'Tome',		'EA_ACTION_TOME_OF_HARVESTS'		UNION ALL
SELECT 'EA_ARTIFACT_TOME_OF_TOMES',			'TXT_KEY_EA_ARTIFACT_TOME_OF_TOMES',		'Tome',		'EA_ACTION_TOME_OF_TOMES'			UNION ALL
SELECT 'EA_ARTIFACT_TOME_OF_AESTHETICS',	'TXT_KEY_EA_ARTIFACT_TOME_OF_AESTHETICS',	'Tome',		'EA_ACTION_TOME_OF_AESTHETICS'		UNION ALL
SELECT 'EA_ARTIFACT_TOME_OF_AXIOMS',		'TXT_KEY_EA_ARTIFACT_TOME_OF_AXIOMS',		'Tome',		'EA_ACTION_TOME_OF_AXIOMS'			UNION ALL
SELECT 'EA_ARTIFACT_TOME_OF_FORM',			'TXT_KEY_EA_ARTIFACT_TOME_OF_FORM',			'Tome',		'EA_ACTION_TOME_OF_FORM'			UNION ALL
SELECT 'EA_ARTIFACT_TOME_OF_METALLURGY',	'TXT_KEY_EA_ARTIFACT_TOME_OF_METALLURGY',	'Tome',		'EA_ACTION_TOME_OF_METALLURGY'		;

UPDATE EaArtifacts SET IconIndex = (SELECT IconIndex FROM EaActions WHERE EaArtifact = EaArtifacts.Type);
UPDATE EaArtifacts SET IconAtlas = (SELECT IconAtlas FROM EaActions WHERE EaArtifact = EaArtifacts.Type);
--UPDATE EaArtifacts SET Description = (SELECT Description FROM EaActions WHERE EaArtifact = EaArtifacts.Type);

CREATE TABLE EaArtifacts_TomeTechs ('ArtifactType' TEXT, 'TechType' TEXT, 'Change' FLOAT);
INSERT INTO EaArtifacts_TomeTechs (ArtifactType, TechType, Change) VALUES
('EA_ARTIFACT_TOME_OF_EQUUS',			'TECH_HORSEBACK_RIDING',	-2		),	
('EA_ARTIFACT_TOME_OF_EQUUS',			'TECH_ANIMAL_HUSBANDRY',	-2		),	
('EA_ARTIFACT_TOME_OF_EQUUS',			'TECH_STIRRUPS',			-2		),	
('EA_ARTIFACT_TOME_OF_EQUUS',			'TECH_ANIMAL_INDUSTRY',		-2		),	
('EA_ARTIFACT_TOME_OF_EQUUS',			'TECH_ANIMAL_BREEDING',		-2		),	
('EA_ARTIFACT_TOME_OF_EQUUS',			'TECH_WAR_HORSES',			-2		),

('EA_ARTIFACT_TOME_OF_BEASTS',			'TECH_ELEPHANT_LABOR',		-1.5	),
('EA_ARTIFACT_TOME_OF_BEASTS',			'TECH_TRACKING_TRAPPING',	-1.5	),
('EA_ARTIFACT_TOME_OF_BEASTS',			'TECH_ELEPHANT_TRAINING',	-1.5	),
('EA_ARTIFACT_TOME_OF_BEASTS',			'TECH_GAMEKEEPING',			-1.5	),
('EA_ARTIFACT_TOME_OF_BEASTS',			'TECH_ANIMAL_MASTERY',		-1.5	),
('EA_ARTIFACT_TOME_OF_BEASTS',			'TECH_WAR_ELEPHANTS',		-1.5	),
('EA_ARTIFACT_TOME_OF_BEASTS',			'TECH_BEAST_MASTERY',		-1.5	),
('EA_ARTIFACT_TOME_OF_BEASTS',			'TECH_MUMAKIL_RIDING',		-1.5	),

('EA_ARTIFACT_TOME_OF_THE_LEVIATHAN',	'TECH_HARPOONS',			-1.5	),
('EA_ARTIFACT_TOME_OF_THE_LEVIATHAN',	'TECH_SAILING',				-1.5	),
('EA_ARTIFACT_TOME_OF_THE_LEVIATHAN',	'TECH_SHIP_BUILDING',		-1.5	),
('EA_ARTIFACT_TOME_OF_THE_LEVIATHAN',	'TECH_NAVIGATION',			-1.5	),
('EA_ARTIFACT_TOME_OF_THE_LEVIATHAN',	'TECH_BEAST_MASTERY',		-1.5	),
('EA_ARTIFACT_TOME_OF_THE_LEVIATHAN',	'TECH_WHALING',				-1.5	),
('EA_ARTIFACT_TOME_OF_THE_LEVIATHAN',	'TECH_SONG_OF_LEVIATHAN',	-1.5	),

('EA_ARTIFACT_TOME_OF_HARVESTS',		'TECH_MILLING',				-2		),
('EA_ARTIFACT_TOME_OF_HARVESTS',		'TECH_WEAVING',				-2		),
('EA_ARTIFACT_TOME_OF_HARVESTS',		'TECH_ZYMURGY',				-2		),
('EA_ARTIFACT_TOME_OF_HARVESTS',		'TECH_IRRIGATION',			-2		),
('EA_ARTIFACT_TOME_OF_HARVESTS',		'TECH_CALENDAR',			-2		),
('EA_ARTIFACT_TOME_OF_HARVESTS',		'TECH_FORESTRY',			-2		),
('EA_ARTIFACT_TOME_OF_HARVESTS',		'TECH_FINE_TEXTILES',		-2		),
('EA_ARTIFACT_TOME_OF_HARVESTS',		'TECH_OENOLOGY',			-2		),
('EA_ARTIFACT_TOME_OF_HARVESTS',		'TECH_CROP_ROTATION',		-2		),

('EA_ARTIFACT_TOME_OF_AESTHETICS',		'TECH_PHILOSOPHY',			-2		),
('EA_ARTIFACT_TOME_OF_AESTHETICS',		'TECH_DRAMA',				-2		),
('EA_ARTIFACT_TOME_OF_AESTHETICS',		'TECH_MATHEMATICS',			-2		),
('EA_ARTIFACT_TOME_OF_AESTHETICS',		'TECH_LITERATURE',			-2		),
('EA_ARTIFACT_TOME_OF_AESTHETICS',		'TECH_MUSIC_THEORY',		-2		),
('EA_ARTIFACT_TOME_OF_AESTHETICS',		'TECH_AESTHETICS',			-2		),
('EA_ARTIFACT_TOME_OF_AESTHETICS',		'TECH_ETHEREAL_ARCHITECTURE',-2		),

('EA_ARTIFACT_TOME_OF_AXIOMS',			'TECH_MATHEMATICS',			-2		),
('EA_ARTIFACT_TOME_OF_AXIOMS',			'TECH_ASTRONOMY',			-2		),
('EA_ARTIFACT_TOME_OF_AXIOMS',			'TECH_ALCHEMY',				-2		),
('EA_ARTIFACT_TOME_OF_AXIOMS',			'TECH_MECHANICS',			-2		),
('EA_ARTIFACT_TOME_OF_AXIOMS',			'TECH_CHEMISTRY',			-2		),
('EA_ARTIFACT_TOME_OF_AXIOMS',			'TECH_MEDICINE',			-2		),
('EA_ARTIFACT_TOME_OF_AXIOMS',			'TECH_MACHINERY',			-2		),
('EA_ARTIFACT_TOME_OF_AXIOMS',			'TECH_STEAM_POWER',			-2		),

('EA_ARTIFACT_TOME_OF_FORM',			'TECH_MASONRY',				-2		),
('EA_ARTIFACT_TOME_OF_FORM',			'TECH_CONSTRUCTION',		-2		),
('EA_ARTIFACT_TOME_OF_FORM',			'TECH_SANITATION',			-2		),
('EA_ARTIFACT_TOME_OF_FORM',			'TECH_ENGINEERING',			-2		),
('EA_ARTIFACT_TOME_OF_FORM',			'TECH_METAL_CASTING',		-2		),
('EA_ARTIFACT_TOME_OF_FORM',			'TECH_ARCHITECTURE',		-2		),
('EA_ARTIFACT_TOME_OF_FORM',			'TECH_MACHINERY',			-2		),
('EA_ARTIFACT_TOME_OF_FORM',			'TECH_ETHEREAL_ARCHITECTURE',-2		),

('EA_ARTIFACT_TOME_OF_METALLURGY',		'TECH_COINAGE',				-2		),
('EA_ARTIFACT_TOME_OF_METALLURGY',		'TECH_BRONZE_WORKING',		-2		),
('EA_ARTIFACT_TOME_OF_METALLURGY',		'TECH_IRON_WORKING',		-2		),
('EA_ARTIFACT_TOME_OF_METALLURGY',		'TECH_METAL_CASTING',		-2		),
('EA_ARTIFACT_TOME_OF_METALLURGY',		'TECH_STEEL_WORKING',		-2		),
('EA_ARTIFACT_TOME_OF_METALLURGY',		'TECH_ELEMENTAL_FORGING',	-2		),
('EA_ARTIFACT_TOME_OF_METALLURGY',		'TECH_MITHRIL_WORKING',		-2		);

-- Tome of Confusion with +mod?


INSERT INTO EaDebugTableCheck(FileName) SELECT 'EaCreations.sql';



