

--unique creations only (no national wonders!).
--Everything here is either created by a great person or placed by some specific game mechanic.
--Prereqs are controled entirely in EaActions.

CREATE TABLE EaWonders ('ID' INTEGER PRIMARY KEY AUTOINCREMENT,
						'Type' TEXT NOT NULL UNIQUE,
						'Description' TEXT DEFAULT NULL,
						'ImprovementType' TEXT DEFAULT NULL,
						'BuildingType' TEXT DEFAULT NULL,			--1 instance in owning city	
						'BuildingModType' TEXT DEFAULT NULL,		--mod instances in owning city
						'EaAction' TEXT DEFAULT NULL,
						'AzzFollowerOnly' BOOLEAN DEFAULT NULL,	--these 3 control wonder/ruins switch (prereqs in EaActions!)
						'FallenOnly' BOOLEAN DEFAULT NULL,
						'PantheisticOnly' BOOLEAN DEFAULT NULL,
						'God' TEXT DEFAULT NULL,
						'Mod' INTEGER DEFAULT 0,		--Mod and spell modifiers (next 9) for Temples only
						'Devotion' INTEGER DEFAULT 0,	--Can set EITHER Devotion OR magic schools (next 8) to some value > 0; Not set for Pan temples since they change by relationship
						'Divi' INTEGER DEFAULT 0,
						'Abju' INTEGER DEFAULT 0,
						'Evoc' INTEGER DEFAULT 0,
						'Trans' INTEGER DEFAULT 0,
						'Conj' INTEGER DEFAULT 0,
						'Necr' INTEGER DEFAULT 0,
						'Ench' INTEGER DEFAULT 0,
						'Illu' INTEGER DEFAULT 0,
						'IconIndex' INTEGER DEFAULT NULL,
						'IconAtlas' TEXT DEFAULT NULL);
						--Wonders are always associated with a specific iPlot (city iPlot if it is a city wonder) and can change ownership
						--gWonders[ID] = nil or {mod, iPlot} for built wonders
						--or, gWonders[ID][ID2] = {iPlot, ...} if it is a special instance wonder (ID2 is iPerson for Arcane Tower)



INSERT INTO EaWonders (Type,		Description,							ImprovementType,					BuildingType,					BuildingModType,			God,							EaAction						) VALUES
('EA_WONDER_KOLOSSOS',				'TXT_KEY_EA_WONDER_KOLOSSOS',			NULL,								'BUILDING_KOLOSSOS',			NULL,						NULL,							'EA_ACTION_KOLOSSOS'			),
('EA_WONDER_MEGALOS_FAROS',			'TXT_KEY_EA_WONDER_MEGALOS_FAROS',		NULL,								'BUILDING_MEGALOS_FAROS',		NULL,						NULL,							'EA_ACTION_MEGALOS_FAROS'		),
('EA_WONDER_HANGING_GARDENS',		'TXT_KEY_EA_WONDER_HANGING_GARDENS',	NULL,								'BUILDING_HANGING_GARDENS',		NULL,						NULL,							'EA_ACTION_HANGING_GARDENS'		),
('EA_WONDER_UUC_YABNAL',			'TXT_KEY_EA_WONDER_UUC_YABNAL',			NULL,								'BUILDING_UUC_YABNAL',			NULL,						NULL,							'EA_ACTION_UUC_YABNAL'			),
('EA_WONDER_THE_LONG_WALL',			'TXT_KEY_EA_WONDER_THE_LONG_WALL',		NULL,								'BUILDING_THE_LONG_WALL',		NULL,						NULL,							'EA_ACTION_THE_LONG_WALL'		),
('EA_WONDER_CLOG_MOR',				'TXT_KEY_EA_WONDER_CLOG_MOR',			NULL,								'BUILDING_CLOG_MOR',			NULL,						NULL,							'EA_ACTION_CLOG_MOR'			),
('EA_WONDER_DA_BAOEN_SI',			'TXT_KEY_EA_WONDER_DA_BAOEN_SI',		NULL,								'BUILDING_DA_BAOEN_SI',			NULL,						NULL,							'EA_ACTION_DA_BAOEN_SI'			);

--plot wonders
INSERT INTO EaWonders (Type,		Description,							ImprovementType,					BuildingType,					BuildingModType,			EaAction						) VALUES
('EA_WONDER_STANHENCG',				'TXT_KEY_EA_WONDER_STANHENCG',			'IMPROVEMENT_STANHENCG',			NULL,							'BUILDING_MOD_STANHENCG',	'EA_ACTION_STANHENCG'			),
('EA_WONDER_PYRAMID',				'TXT_KEY_EA_WONDER_PYRAMID',			'IMPROVEMENT_PYRAMID',				'BUILDING_PYRAMID',				NULL,						'EA_ACTION_PYRAMID'				),
('EA_WONDER_GREAT_LIBRARY',			'TXT_KEY_EA_WONDER_GREAT_LIBRARY',		'IMPROVEMENT_GREAT_LIBRARY',		'BUILDING_GREAT_LIBRARY',		NULL,						'EA_ACTION_GREAT_LIBRARY'		),
('EA_WONDER_ARCANE_TOWER',			'TXT_KEY_EA_WONDER_ARCANE_TOWER',		'IMPROVEMENT_ARCANE_TOWER',			NULL,							'BUILDING_MOD_ARCANE_TOWER','EA_ACTION_ARCANE_TOWER'		);

--Lue expects these to be last, EA_WONDER_TEMPLE_AZZANDARA_1, EA_WONDER_TEMPLE_AHRIMAN_1, and EA_WONDER_TEMPLE_FAGUS
INSERT INTO EaWonders (Type,		Description,							ImprovementType,					BuildingType,					Mod,	Devotion,	EaAction						) VALUES
('EA_WONDER_TEMPLE_AZZANDARA_1',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_1',	'IMPROVEMENT_TEMPLE_AZZANDARA_1',	'BUILDING_TEMPLE_AZZANDARA_1',	3,		3,			'EA_ACTION_TEMPLE_AZZANDARA_1'	),
('EA_WONDER_TEMPLE_AZZANDARA_2',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_2',	'IMPROVEMENT_TEMPLE_AZZANDARA_2',	'BUILDING_TEMPLE_AZZANDARA_2',	5,		5,			'EA_ACTION_TEMPLE_AZZANDARA_2'	),
('EA_WONDER_TEMPLE_AZZANDARA_3',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_3',	'IMPROVEMENT_TEMPLE_AZZANDARA_3',	'BUILDING_TEMPLE_AZZANDARA_3',	8,		8,			'EA_ACTION_TEMPLE_AZZANDARA_3'	),
('EA_WONDER_TEMPLE_AZZANDARA_4',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_4',	'IMPROVEMENT_TEMPLE_AZZANDARA_4',	'BUILDING_TEMPLE_AZZANDARA_4',	13,		13,			'EA_ACTION_TEMPLE_AZZANDARA_4'	),
('EA_WONDER_TEMPLE_AZZANDARA_5',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_5',	'IMPROVEMENT_TEMPLE_AZZANDARA_5',	'BUILDING_TEMPLE_AZZANDARA_5',	21,		21,			'EA_ACTION_TEMPLE_AZZANDARA_5'	),
('EA_WONDER_TEMPLE_AZZANDARA_6',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_6',	'IMPROVEMENT_TEMPLE_AZZANDARA_6',	'BUILDING_TEMPLE_AZZANDARA_6',	34,		34,			'EA_ACTION_TEMPLE_AZZANDARA_6'	),
('EA_WONDER_TEMPLE_AZZANDARA_7',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_7',	'IMPROVEMENT_TEMPLE_AZZANDARA_7',	'BUILDING_TEMPLE_AZZANDARA_7',	55,		55,			'EA_ACTION_TEMPLE_AZZANDARA_7'	);

INSERT INTO EaWonders (Type,		Description,							ImprovementType,					BuildingType,					Mod,	Divi,	Abju,	Evoc,	Trans,	Conj,	Necr,	Ench,	Illu,	EaAction						) VALUES
('EA_WONDER_TEMPLE_AHRIMAN_1',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_1',	'IMPROVEMENT_TEMPLE_AHRIMAN_1',		'BUILDING_TEMPLE_AHRIMAN_1',	11,		11,		11,		11,		13,		11,		11,		11,		11,		'EA_ACTION_TEMPLE_AHRIMAN_1'	),
('EA_WONDER_TEMPLE_AHRIMAN_2',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_2',	'IMPROVEMENT_TEMPLE_AHRIMAN_2',		'BUILDING_TEMPLE_AHRIMAN_2',	13,		13,		13,		13,		13,		13,		17,		13,		13,		'EA_ACTION_TEMPLE_AHRIMAN_2'	),
('EA_WONDER_TEMPLE_AHRIMAN_3',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_3',	'IMPROVEMENT_TEMPLE_AHRIMAN_3',		'BUILDING_TEMPLE_AHRIMAN_3',	17,		17,		17,		17,		17,		17,		17,		19,		17,		'EA_ACTION_TEMPLE_AHRIMAN_3'	),
('EA_WONDER_TEMPLE_AHRIMAN_4',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_4',	'IMPROVEMENT_TEMPLE_AHRIMAN_4',		'BUILDING_TEMPLE_AHRIMAN_4',	19,		19,		19,		19,		19,		19,		23,		19,		19,		'EA_ACTION_TEMPLE_AHRIMAN_4'	),
('EA_WONDER_TEMPLE_AHRIMAN_5',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_5',	'IMPROVEMENT_TEMPLE_AHRIMAN_5',		'BUILDING_TEMPLE_AHRIMAN_5',	23,		23,		23,		23,		23,		29,		23,		23,		23,		'EA_ACTION_TEMPLE_AHRIMAN_5'	),
('EA_WONDER_TEMPLE_AHRIMAN_6',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_6',	'IMPROVEMENT_TEMPLE_AHRIMAN_6',		'BUILDING_TEMPLE_AHRIMAN_6',	29,		29,		29,		29,		29,		29,		29,		29,		31,		'EA_ACTION_TEMPLE_AHRIMAN_6'	),
('EA_WONDER_TEMPLE_AHRIMAN_7',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_7',	'IMPROVEMENT_TEMPLE_AHRIMAN_7',		'BUILDING_TEMPLE_AHRIMAN_7',	31,		31,		31,		37,		31,		31,		31,		31,		31,		'EA_ACTION_TEMPLE_AHRIMAN_7'	),
('EA_WONDER_TEMPLE_AHRIMAN_8',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_8',	'IMPROVEMENT_TEMPLE_AHRIMAN_8',		'BUILDING_TEMPLE_AHRIMAN_8',	43,		37,		37,		37,		37,		37,		41,		37,		37,		'EA_ACTION_TEMPLE_AHRIMAN_8'	),
('EA_WONDER_TEMPLE_AHRIMAN_9',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_9',	'IMPROVEMENT_TEMPLE_AHRIMAN_9',		'BUILDING_TEMPLE_AHRIMAN_9',	41,		41,		41,		41,		43,		43,		43,		41,		43,		'EA_ACTION_TEMPLE_AHRIMAN_9'	);

INSERT INTO EaWonders (Type,		Description,							ImprovementType,					BuildingType,					God,							EaAction						) VALUES
('EA_WONDER_TEMPLE_FAGUS',			'TXT_KEY_EA_WONDER_TEMPLE_FAGUS',		'IMPROVEMENT_TEMPLE_FAGUS',			'BUILDING_TEMPLE_FAGUS',		'MINOR_CIV_GOD_FAGUS',			'EA_ACTION_TEMPLE_FAGUS'		),
('EA_WONDER_TEMPLE_ABELLIO',		'TXT_KEY_EA_WONDER_TEMPLE_ABELLIO',		'IMPROVEMENT_TEMPLE_ABELLIO',		'BUILDING_TEMPLE_ABELLIO',		'MINOR_CIV_GOD_ABELLIO',		'EA_ACTION_TEMPLE_ABELLIO'		),
('EA_WONDER_TEMPLE_BUXENUS',		'TXT_KEY_EA_WONDER_TEMPLE_BUXENUS',		'IMPROVEMENT_TEMPLE_BUXENUS',		'BUILDING_TEMPLE_BUXENUS',		'MINOR_CIV_GOD_BUXENUS',		'EA_ACTION_TEMPLE_BUXENUS'		),
('EA_WONDER_TEMPLE_ROBOR',			'TXT_KEY_EA_WONDER_TEMPLE_ROBOR',		'IMPROVEMENT_TEMPLE_ROBOR',			'BUILDING_TEMPLE_ROBOR',		'MINOR_CIV_GOD_ROBOR',			'EA_ACTION_TEMPLE_ROBOR'		),
('EA_WONDER_TEMPLE_ABNOAB',			'TXT_KEY_EA_WONDER_TEMPLE_ABNOAB',		'IMPROVEMENT_TEMPLE_ABNOAB',		'BUILDING_TEMPLE_ABNOAB',		'MINOR_CIV_GOD_ABNOAB',			'EA_ACTION_TEMPLE_ABNOAB'		),
('EA_WONDER_TEMPLE_EPONA',			'TXT_KEY_EA_WONDER_TEMPLE_EPONA',		'IMPROVEMENT_TEMPLE_EPONA',			'BUILDING_TEMPLE_EPONA',		'MINOR_CIV_GOD_EPONA',			'EA_ACTION_TEMPLE_EPONA'		),
('EA_WONDER_TEMPLE_ATEPOMARUS',		'TXT_KEY_EA_WONDER_TEMPLE_ATEPOMARUS',	'IMPROVEMENT_TEMPLE_ATEPOMARUS',	'BUILDING_TEMPLE_ATEPOMARUS',	'MINOR_CIV_GOD_ATEPOMARUS',		'EA_ACTION_TEMPLE_ATEPOMARUS'	),
('EA_WONDER_TEMPLE_SABAZIOS',		'TXT_KEY_EA_WONDER_TEMPLE_SABAZIOS',	'IMPROVEMENT_TEMPLE_SABAZIOS',		'BUILDING_TEMPLE_SABAZIOS',		'MINOR_CIV_GOD_SABAZIOS',		'EA_ACTION_TEMPLE_SABAZIOS'		),
('EA_WONDER_TEMPLE_AVETA',			'TXT_KEY_EA_WONDER_TEMPLE_AVETA',		'IMPROVEMENT_TEMPLE_AVETA',			'BUILDING_TEMPLE_AVETA',		'MINOR_CIV_GOD_AVETA',			'EA_ACTION_TEMPLE_AVETA'		),
('EA_WONDER_TEMPLE_CONDATIS',		'TXT_KEY_EA_WONDER_TEMPLE_CONDATIS',	'IMPROVEMENT_TEMPLE_CONDATIS',		'BUILDING_TEMPLE_CONDATIS',		'MINOR_CIV_GOD_CONDATIS',		'EA_ACTION_TEMPLE_CONDATIS'		),
('EA_WONDER_TEMPLE_ABANDINUS',		'TXT_KEY_EA_WONDER_TEMPLE_ABANDINUS',	'IMPROVEMENT_TEMPLE_ABANDINUS',		'BUILDING_TEMPLE_ABANDINUS',	'MINOR_CIV_GOD_ABANDINUS',		'EA_ACTION_TEMPLE_ABANDINUS'	),
('EA_WONDER_TEMPLE_ADSULLATA',		'TXT_KEY_EA_WONDER_TEMPLE_ADSULLATA',	'IMPROVEMENT_TEMPLE_ADSULLATA',		'BUILDING_TEMPLE_ADSULLATA',	'MINOR_CIV_GOD_ADSULLATA',		'EA_ACTION_TEMPLE_ADSULLATA'	),
('EA_WONDER_TEMPLE_ICAUNUS',		'TXT_KEY_EA_WONDER_TEMPLE_ICAUNUS',		'IMPROVEMENT_TEMPLE_ICAUNUS',		'BUILDING_TEMPLE_ICAUNUS',		'MINOR_CIV_GOD_ICAUNUS',		'EA_ACTION_TEMPLE_ICAUNUS'		),
('EA_WONDER_TEMPLE_BELISAMA',		'TXT_KEY_EA_WONDER_TEMPLE_BELISAMA',	'IMPROVEMENT_TEMPLE_BELISAMA',		'BUILDING_TEMPLE_BELISAMA',		'MINOR_CIV_GOD_BELISAMA',		'EA_ACTION_TEMPLE_BELISAMA'		),
('EA_WONDER_TEMPLE_CLOTA',			'TXT_KEY_EA_WONDER_TEMPLE_CLOTA',		'IMPROVEMENT_TEMPLE_CLOTA',			'BUILDING_TEMPLE_CLOTA',		'MINOR_CIV_GOD_CLOTA',			'EA_ACTION_TEMPLE_CLOTA'		),
('EA_WONDER_TEMPLE_SABRINA',		'TXT_KEY_EA_WONDER_TEMPLE_SABRINA',		'IMPROVEMENT_TEMPLE_SABRINA',		'BUILDING_TEMPLE_SABRINA',		'MINOR_CIV_GOD_SABRINA',		'EA_ACTION_TEMPLE_SABRINA'		),
('EA_WONDER_TEMPLE_SEQUANA',		'TXT_KEY_EA_WONDER_TEMPLE_SEQUANA',		'IMPROVEMENT_TEMPLE_SEQUANA',		'BUILDING_TEMPLE_SEQUANA',		'MINOR_CIV_GOD_SEQUANA',		'EA_ACTION_TEMPLE_SEQUANA'		),
('EA_WONDER_TEMPLE_VERBEIA',		'TXT_KEY_EA_WONDER_TEMPLE_VERBEIA',		'IMPROVEMENT_TEMPLE_VERBEIA',		'BUILDING_TEMPLE_VERBEIA',		'MINOR_CIV_GOD_VERBEIA',		'EA_ACTION_TEMPLE_VERBEIA'		),
('EA_WONDER_TEMPLE_BORVO',			'TXT_KEY_EA_WONDER_TEMPLE_BORVO',		'IMPROVEMENT_TEMPLE_BORVO',			'BUILDING_TEMPLE_BORVO',		'MINOR_CIV_GOD_BORVO',			'EA_ACTION_TEMPLE_BORVO'		),
('EA_WONDER_TEMPLE_AEGIR',			'TXT_KEY_EA_WONDER_TEMPLE_AEGIR',		'IMPROVEMENT_TEMPLE_AEGIR',			'BUILDING_TEMPLE_AEGIR',		'MINOR_CIV_GOD_AEGIR',			'EA_ACTION_TEMPLE_AEGIR'		),
('EA_WONDER_TEMPLE_BARINTHUS',		'TXT_KEY_EA_WONDER_TEMPLE_BARINTHUS',	'IMPROVEMENT_TEMPLE_BARINTHUS',		'BUILDING_TEMPLE_BARINTHUS',	'MINOR_CIV_GOD_BARINTHUS',		'EA_ACTION_TEMPLE_BARINTHUS'	),
('EA_WONDER_TEMPLE_LIBAN',			'TXT_KEY_EA_WONDER_TEMPLE_LIBAN',		'IMPROVEMENT_TEMPLE_LIBAN',			'BUILDING_TEMPLE_LIBAN',		'MINOR_CIV_GOD_LIBAN',			'EA_ACTION_TEMPLE_LIBAN'		),
('EA_WONDER_TEMPLE_FIMAFENG',		'TXT_KEY_EA_WONDER_TEMPLE_FIMAFENG',	'IMPROVEMENT_TEMPLE_FIMAFENG',		'BUILDING_TEMPLE_FIMAFENG',		'MINOR_CIV_GOD_FIMAFENG',		'EA_ACTION_TEMPLE_FIMAFENG'		),
('EA_WONDER_TEMPLE_ELDIR',			'TXT_KEY_EA_WONDER_TEMPLE_ELDIR',		'IMPROVEMENT_TEMPLE_ELDIR',			'BUILDING_TEMPLE_ELDIR',		'MINOR_CIV_GOD_ELDIR',			'EA_ACTION_TEMPLE_ELDIR'		),
('EA_WONDER_TEMPLE_RITONA',			'TXT_KEY_EA_WONDER_TEMPLE_RITONA',		'IMPROVEMENT_TEMPLE_RITONA',		'BUILDING_TEMPLE_RITONA',		'MINOR_CIV_GOD_RITONA',			'EA_ACTION_TEMPLE_RITONA'		),
('EA_WONDER_TEMPLE_BAKKHOS',		'TXT_KEY_EA_WONDER_TEMPLE_BAKKHOS',		'IMPROVEMENT_TEMPLE_BAKKHOS',		'BUILDING_TEMPLE_BAKKHOS',		'MINOR_CIV_GOD_BAKKHOS',		'EA_ACTION_TEMPLE_BAKKHOS'		),
('EA_WONDER_TEMPLE_PAN',			'TXT_KEY_EA_WONDER_TEMPLE_PAN',			'IMPROVEMENT_TEMPLE_PAN',			'BUILDING_TEMPLE_PAN',			'MINOR_CIV_GOD_PAN',			'EA_ACTION_TEMPLE_PAN'			),
('EA_WONDER_TEMPLE_SILENUS',		'TXT_KEY_EA_WONDER_TEMPLE_SILENUS',		'IMPROVEMENT_TEMPLE_SILENUS',		'BUILDING_TEMPLE_SILENUS',		'MINOR_CIV_GOD_SILENUS',		'EA_ACTION_TEMPLE_SILENUS'		),
('EA_WONDER_TEMPLE_ERECURA',		'TXT_KEY_EA_WONDER_TEMPLE_ERECURA',		'IMPROVEMENT_TEMPLE_ERECURA',		'BUILDING_TEMPLE_ERECURA',		'MINOR_CIV_GOD_ERECURA',		'EA_ACTION_TEMPLE_ERECURA'		),
('EA_WONDER_TEMPLE_VOSEGUS',		'TXT_KEY_EA_WONDER_TEMPLE_VOSEGUS',		'IMPROVEMENT_TEMPLE_VOSEGUS',		'BUILDING_TEMPLE_VOSEGUS',		'MINOR_CIV_GOD_VOSEGUS',		'EA_ACTION_TEMPLE_VOSEGUS'		),
('EA_WONDER_TEMPLE_NANTOSUELTA',	'TXT_KEY_EA_WONDER_TEMPLE_NANTOSUELTA',	'IMPROVEMENT_TEMPLE_NANTOSUELTA',	'BUILDING_TEMPLE_NANTOSUELTA',	'MINOR_CIV_GOD_NANTOSUELTA',	'EA_ACTION_TEMPLE_NANTOSUELTA'	),
('EA_WONDER_TEMPLE_DIS_PATER',		'TXT_KEY_EA_WONDER_TEMPLE_DIS_PATER',	'IMPROVEMENT_TEMPLE_DIS_PATER',		'BUILDING_TEMPLE_DIS_PATER',	'MINOR_CIV_GOD_DIS_PATER',		'EA_ACTION_TEMPLE_DIS_PATER'	),
('EA_WONDER_TEMPLE_NERGAL',			'TXT_KEY_EA_WONDER_TEMPLE_NERGAL',		'IMPROVEMENT_TEMPLE_NERGAL',		'BUILDING_TEMPLE_NERGAL',		'MINOR_CIV_GOD_NERGAL',			'EA_ACTION_TEMPLE_NERGAL'		),
('EA_WONDER_TEMPLE_WADD',			'TXT_KEY_EA_WONDER_TEMPLE_WADD',		'IMPROVEMENT_TEMPLE_WADD',			'BUILDING_TEMPLE_WADD',			'MINOR_CIV_GOD_WADD',			'EA_ACTION_TEMPLE_WADD'			),
('EA_WONDER_TEMPLE_ABGAL',			'TXT_KEY_EA_WONDER_TEMPLE_ABGAL',		'IMPROVEMENT_TEMPLE_ABGAL',			'BUILDING_TEMPLE_ABGAL',		'MINOR_CIV_GOD_ABGAL',			'EA_ACTION_TEMPLE_ABGAL'		),
('EA_WONDER_TEMPLE_NESR',			'TXT_KEY_EA_WONDER_TEMPLE_NESR',		'IMPROVEMENT_TEMPLE_NESR',			'BUILDING_TEMPLE_NESR',			'MINOR_CIV_GOD_NESR',			'EA_ACTION_TEMPLE_NESR'			);


UPDATE EaWonders SET AzzFollowerOnly = 1 WHERE Type GLOB 'EA_WONDER_TEMPLE_AZZANDARA_*';
UPDATE EaWonders SET FallenOnly = 1 WHERE Type GLOB 'EA_WONDER_TEMPLE_AHRIMAN_*';

UPDATE EaWonders SET IconIndex = (SELECT IconIndex FROM EaActions WHERE EaWonder = EaWonders.Type);
UPDATE EaWonders SET IconAtlas = (SELECT IconAtlas FROM EaActions WHERE EaWonder = EaWonders.Type);
UPDATE EaWonders SET IconIndex = 3, IconAtlas = 'UNIT_ACTION_ATLAS_EXP2' WHERE Type = 'EA_WONDER_ARCANE_TOWER';

INSERT INTO EaDebugTableCheck(FileName) SELECT 'EaWonders.sql';