

--unique creations only (no national wonders!).
--Everything here is either created by a great person or placed by some specific game mechanic.
--Prereqs are controled entirely in EaActions.

CREATE TABLE EaWonders ('ID' INTEGER PRIMARY KEY AUTOINCREMENT,
						'Type' TEXT NOT NULL UNIQUE,
						'Description' TEXT DEFAULT NULL,
						'ImprovementType' TEXT DEFAULT NULL,
						'BuildingType' TEXT DEFAULT NULL,			--1 instance in owning city	
						'BuildingModType' TEXT DEFAULT NULL,		--mod instances in owning city
						'EaAction' TEXT DEFAULT NULL,
						'AzzFollowerOnly' BOOLEAN DEFAULT NULL,	--these 3 control wonder/ruins switch (prereqs in EaActions!)
						'FallenOnly' BOOLEAN DEFAULT NULL,
						'PantheisticOnly' BOOLEAN DEFAULT NULL,
						'IconIndex' INTEGER DEFAULT NULL,
						'IconAtlas' TEXT DEFAULT NULL);
						--Wonders are always associated with a specific iPlot (city iPlot if it is a city wonder) and can change ownership
						--gWonders[ID] = nil or {mod, iPlot} for built wonders
						--or, gWonders[ID][ID2] = {iPlot, ...} if it is a special instance wonder (ID2 is iPerson for Arcane Tower)



INSERT INTO EaWonders (Type,		Description,							ImprovementType,					BuildingType,				BuildingModType,		EaAction						) VALUES
('EA_WONDER_KOLOSSOS',				'TXT_KEY_EA_WONDER_KOLOSSOS',			NULL,								'BUILDING_KOLOSSOS',		NULL,					'EA_ACTION_KOLOSSOS'			),
('EA_WONDER_MEGALOS_FAROS',			'TXT_KEY_EA_WONDER_MEGALOS_FAROS',		NULL,								'BUILDING_MEGALOS_FAROS',	NULL,					'EA_ACTION_MEGALOS_FAROS'		),
('EA_WONDER_HANGING_GARDENS',		'TXT_KEY_EA_WONDER_HANGING_GARDENS',	NULL,								'BUILDING_HANGING_GARDENS',	NULL,					'EA_ACTION_HANGING_GARDENS'		),
('EA_WONDER_UUC_YABNAL',			'TXT_KEY_EA_WONDER_UUC_YABNAL',			NULL,								'BUILDING_UUC_YABNAL',		NULL,					'EA_ACTION_UUC_YABNAL'			),
('EA_WONDER_THE_LONG_WALL',			'TXT_KEY_EA_WONDER_THE_LONG_WALL',		NULL,								'BUILDING_THE_LONG_WALL',	NULL,					'EA_ACTION_THE_LONG_WALL'		),
('EA_WONDER_CLOG_MOR',				'TXT_KEY_EA_WONDER_CLOG_MOR',			NULL,								'BUILDING_CLOG_MOR',		NULL,					'EA_ACTION_CLOG_MOR'			),
('EA_WONDER_DA_BAOEN_SI',			'TXT_KEY_EA_WONDER_DA_BAOEN_SI',		NULL,								'BUILDING_DA_BAOEN_SI',		NULL,					'EA_ACTION_DA_BAOEN_SI'			),

--plot wonders
('EA_WONDER_STANHENCG',				'TXT_KEY_EA_WONDER_STANHENCG',			'IMPROVEMENT_STANHENCG',			'BUILDING_STANHENCG',		NULL,					'EA_ACTION_STANHENCG'			),
('EA_WONDER_PYRAMID',				'TXT_KEY_EA_WONDER_PYRAMID',			'IMPROVEMENT_PYRAMID',				'BUILDING_PYRAMID',			NULL,					'EA_ACTION_PYRAMID'				),
('EA_WONDER_GREAT_LIBRARY',			'TXT_KEY_EA_WONDER_GREAT_LIBRARY',		'IMPROVEMENT_GREAT_LIBRARY',		'BUILDING_GREAT_LIBRARY',	NULL,					'EA_ACTION_GREAT_LIBRARY'		),
('EA_WONDER_ARCANE_TOWER',			'TXT_KEY_EA_WONDER_ARCANE_TOWER',		'IMPROVEMENT_ARCANE_TOWER',			NULL,						NULL,					'EA_ACTION_ARCANE_TOWER'		),
('EA_WONDER_TEMPLE_AZZANDARA_1',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_1',	'IMPROVEMENT_TEMPLE_AZZANDARA_1',	NULL,						NULL,					'EA_ACTION_TEMPLE_AZZANDARA_1'	),
('EA_WONDER_TEMPLE_AZZANDARA_2',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_2',	'IMPROVEMENT_TEMPLE_AZZANDARA_2',	NULL,						NULL,					'EA_ACTION_TEMPLE_AZZANDARA_2'	),
('EA_WONDER_TEMPLE_AZZANDARA_3',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_3',	'IMPROVEMENT_TEMPLE_AZZANDARA_3',	NULL,						NULL,					'EA_ACTION_TEMPLE_AZZANDARA_3'	),
('EA_WONDER_TEMPLE_AZZANDARA_4',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_4',	'IMPROVEMENT_TEMPLE_AZZANDARA_4',	NULL,						NULL,					'EA_ACTION_TEMPLE_AZZANDARA_4'	),
('EA_WONDER_TEMPLE_AZZANDARA_5',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_5',	'IMPROVEMENT_TEMPLE_AZZANDARA_5',	NULL,						NULL,					'EA_ACTION_TEMPLE_AZZANDARA_5'	),
('EA_WONDER_TEMPLE_AZZANDARA_6',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_6',	'IMPROVEMENT_TEMPLE_AZZANDARA_6',	NULL,						NULL,					'EA_ACTION_TEMPLE_AZZANDARA_6'	),
('EA_WONDER_TEMPLE_AZZANDARA_7',	'TXT_KEY_EA_WONDER_TEMPLE_AZZANDARA_7',	'IMPROVEMENT_TEMPLE_AZZANDARA_7',	NULL,						NULL,					'EA_ACTION_TEMPLE_AZZANDARA_7'	),
('EA_WONDER_TEMPLE_AHRIMAN_1',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_1',	'IMPROVEMENT_TEMPLE_AHRIMAN_1',		NULL,						NULL,					'EA_ACTION_TEMPLE_AHRIMAN_1'	),
('EA_WONDER_TEMPLE_AHRIMAN_2',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_2',	'IMPROVEMENT_TEMPLE_AHRIMAN_2',		NULL,						NULL,					'EA_ACTION_TEMPLE_AHRIMAN_2'	),
('EA_WONDER_TEMPLE_AHRIMAN_3',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_3',	'IMPROVEMENT_TEMPLE_AHRIMAN_3',		NULL,						NULL,					'EA_ACTION_TEMPLE_AHRIMAN_3'	),
('EA_WONDER_TEMPLE_AHRIMAN_4',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_4',	'IMPROVEMENT_TEMPLE_AHRIMAN_4',		NULL,						NULL,					'EA_ACTION_TEMPLE_AHRIMAN_4'	),
('EA_WONDER_TEMPLE_AHRIMAN_5',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_5',	'IMPROVEMENT_TEMPLE_AHRIMAN_5',		NULL,						NULL,					'EA_ACTION_TEMPLE_AHRIMAN_5'	),
('EA_WONDER_TEMPLE_AHRIMAN_6',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_6',	'IMPROVEMENT_TEMPLE_AHRIMAN_6',		NULL,						NULL,					'EA_ACTION_TEMPLE_AHRIMAN_6'	),
('EA_WONDER_TEMPLE_AHRIMAN_7',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_7',	'IMPROVEMENT_TEMPLE_AHRIMAN_7',		NULL,						NULL,					'EA_ACTION_TEMPLE_AHRIMAN_7'	),
('EA_WONDER_TEMPLE_AHRIMAN_8',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_8',	'IMPROVEMENT_TEMPLE_AHRIMAN_8',		NULL,						NULL,					'EA_ACTION_TEMPLE_AHRIMAN_8'	),
('EA_WONDER_TEMPLE_AHRIMAN_9',		'TXT_KEY_EA_WONDER_TEMPLE_AHRIMAN_9',	'IMPROVEMENT_TEMPLE_AHRIMAN_9',		NULL,						NULL,					'EA_ACTION_TEMPLE_AHRIMAN_9'	);

UPDATE EaWonders SET AzzFollowerOnly = 1 WHERE Type GLOB 'EA_WONDER_TEMPLE_AZZANDARA_*';
UPDATE EaWonders SET FallenOnly = 1 WHERE Type GLOB 'EA_WONDER_TEMPLE_AHRIMAN_*';

UPDATE EaWonders SET IconIndex = (SELECT IconIndex FROM EaActions WHERE EaWonder = EaWonders.Type);
UPDATE EaWonders SET IconAtlas = (SELECT IconAtlas FROM EaActions WHERE EaWonder = EaWonders.Type);
UPDATE EaWonders SET IconIndex = 3, IconAtlas = 'UNIT_ACTION_ATLAS_EXP2' WHERE Type = 'EA_WONDER_ARCANE_TOWER';

INSERT INTO EaDebugTableCheck(FileName) SELECT 'EaWonders.sql';