
--Global Defines
UPDATE Defines SET Value = 5 WHERE Name = 'AI_STRATEGY_DEFEND_MY_LANDS_BASE_UNITS';		--3
UPDATE Defines SET Value = 13 WHERE Name = 'AI_CITIZEN_VALUE_FOOD';						--14
UPDATE Defines SET Value = 100 WHERE Name = 'AI_CITIZEN_MOD_FOOD_DEFICIT';				--300


--City
UPDATE AICityStrategies SET WeightThreshold = 67 WHERE Type = 'AICITYSTRATEGY_NEED_TILE_IMPROVERS';	--67
UPDATE AICityStrategies SET WeightThreshold = 40 WHERE Type = 'AICITYSTRATEGY_WANT_TILE_IMPROVERS';		--40
UPDATE AICityStrategies SET TechPrereq = NULL WHERE Type = 'AICITYSTRATEGY_FIRST_FAITH_BUILDING';

--Economic
UPDATE AIEconomicStrategies SET TechPrereq = 'TECH_ASTRONOMY' WHERE Type = 'ECONOMICAISTRATEGY_EXPAND_TO_OTHER_CONTINENTS';
UPDATE AIEconomicStrategies SET TechPrereq = 'TECH_ASTRONOMY' WHERE Type = 'ECONOMICAISTRATEGY_REALLY_EXPAND_TO_OTHER_CONTINENTS';
UPDATE AIEconomicStrategies SET TechPrereq = NULL WHERE Type = 'ECONOMICAISTRATEGY_DEVELOPING_RELIGION';
UPDATE AIEconomicStrategies SET TechObsolete = NULL WHERE Type = 'ECONOMICAISTRATEGY_DEVELOPING_RELIGION';

--Military
UPDATE AIMilitaryStrategies SET WeightThreshold = 100 WHERE Type = 'MILITARYAISTRATEGY_WAR_MOBILIZATION';	--100
UPDATE AIMilitaryStrategies SET WeightThreshold = 50 WHERE Type = 'MILITARYAISTRATEGY_ERADICATE_BARBARIANS';	--75
UPDATE AIMilitaryStrategies SET TechPrereq = NULL WHERE Type = 'MILITARYAISTRATEGY_NEED_AIR';	
UPDATE AIMilitaryStrategies SET FirstTurnExecuted = 100 WHERE Type = 'MILITARYAISTRATEGY_ENOUGH_MILITARY_UNITS';
UPDATE AIMilitaryStrategies SET FirstTurnExecuted = 150 WHERE Type = 'MILITARYAISTRATEGY_ENOUGH_NAVAL_UNITS';

UPDATE AIMilitaryStrategies SET TechPrereq = 'TECH_NEVER' WHERE Type IN ('MILITARYAISTRATEGY_ENOUGH_RANGED', 'MILITARYAISTRATEGY_ENOUGH_MOBILE', 'MILITARYAISTRATEGY_NEED_RANGED_EARLY', 'MILITARYAISTRATEGY_NEED_NUKE', 'MILITARYAISTRATEGY_ENOUGH_AIR', 'MILITARYAISTRATEGY_NEED_ANTIAIR', 'MILITARYAISTRATEGY_ENOUGH_ANTIAIR', 'MILITARYAISTRATEGY_NEED_AIR_CARRIER');


--TO DO: Use utility tech to obsolete all strategies for gods



INSERT INTO EaDebugTableCheck(FileName) SELECT 'AI.sql';

--To Do:

--Diplomacy_Responses

