
--Global AI Defines
UPDATE Defines SET Value = 5 WHERE Name = 'AI_STRATEGY_DEFEND_MY_LANDS_BASE_UNITS';		--3
UPDATE Defines SET Value = 13 WHERE Name = 'AI_CITIZEN_VALUE_FOOD';						--14
UPDATE Defines SET Value = 100 WHERE Name = 'AI_CITIZEN_MOD_FOOD_DEFICIT';				--300

UPDATE Defines SET Value = 2 WHERE Name = 'AI_CITYSTRATEGY_SMALL_CITY_POP_THRESHOLD';			--2
UPDATE Defines SET Value = 3 WHERE Name = 'AI_CITYSTRATEGY_MEDIUM_CITY_POP_THRESHOLD';			--5
UPDATE Defines SET Value = 8 WHERE Name = 'AI_CITYSTRATEGY_LARGE_CITY_POP_THRESHOLD';			--12


--City
UPDATE AICityStrategies SET WeightThreshold = 67 WHERE Type = 'AICITYSTRATEGY_NEED_TILE_IMPROVERS';	--67
UPDATE AICityStrategies SET WeightThreshold = 40 WHERE Type = 'AICITYSTRATEGY_WANT_TILE_IMPROVERS';		--40

UPDATE AICityStrategies SET TechPrereq = NULL;		--All can start immediately except disables below
UPDATE AICityStrategies SET TechPrereq = 'TECH_NEVER' WHERE Type IN
('AICITYSTRATEGY_NEED_TOURISM_BUILDING', 'AICITYSTRATEGY_GOOD_AIRLIFT_CITY', 'AICITYSTRATEGY_MANY_TECHS_STOLEN',	--NA
'AICITYSTRATEGY_KEY_SCIENCE_CITY', 'AICITYSTRATEGY_GOOD_GP_CITY', 'AICITYSTRATEGY_NEED_CULTURE_BUILDING',	--NA or dangerous for mod (see dll)
'AICITYSTRATEGY_ENOUGH_NAVAL_TILE_IMPROVEMENT');	--if allowed then it is a good idea

--Economic
UPDATE AIEconomicStrategies SET TechPrereq = 'TECH_ASTRONOMY' WHERE Type = 'ECONOMICAISTRATEGY_EXPAND_TO_OTHER_CONTINENTS';
UPDATE AIEconomicStrategies SET TechPrereq = 'TECH_ASTRONOMY' WHERE Type = 'ECONOMICAISTRATEGY_REALLY_EXPAND_TO_OTHER_CONTINENTS';
UPDATE AIEconomicStrategies SET TechPrereq = NULL WHERE Type = 'ECONOMICAISTRATEGY_DEVELOPING_RELIGION';
UPDATE AIEconomicStrategies SET TechObsolete = NULL WHERE Type = 'ECONOMICAISTRATEGY_DEVELOPING_RELIGION';

UPDATE AIEconomicStrategies SET TechPrereq = 'TECH_NEVER' WHERE Type IN
('ECONOMICAISTRATEGY_HALT_GROWTH_BUILDINGS', 'ECONOMICAISTRATEGY_TECH_LEADER',		--triggers don't apply to mod
'ECONOMICAISTRATEGY_NEED_ARCHAEOLOGISTS', 'ECONOMICAISTRATEGY_ENOUGH_ARCHAEOLOGISTS', 'ECONOMICAISTRATEGY_NEED_MUSEUMS',	--NA
'ECONOMICAISTRATEGY_NEED_GUILDS', 'ECONOMICAISTRATEGY_CONCERT_TOUR', 'ECONOMICAISTRATEGY_STARTED_PIETY');					--NA

--disabled by event:
--ECONOMICAISTRATEGY_NEED_HAPPINESS, ECONOMICAISTRATEGY_NEED_HAPPINESS_CRITICAL depending on Slavery level

--Military
UPDATE AIMilitaryStrategies SET WeightThreshold = 100 WHERE Type = 'MILITARYAISTRATEGY_WAR_MOBILIZATION';	--100
UPDATE AIMilitaryStrategies SET WeightThreshold = 50 WHERE Type = 'MILITARYAISTRATEGY_ERADICATE_BARBARIANS';	--75



UPDATE AIMilitaryStrategies SET FirstTurnExecuted = 100 WHERE Type = 'MILITARYAISTRATEGY_ENOUGH_MILITARY_UNITS';
UPDATE AIMilitaryStrategies SET FirstTurnExecuted = 150 WHERE Type = 'MILITARYAISTRATEGY_ENOUGH_NAVAL_UNITS';

UPDATE AIMilitaryStrategies SET TechPrereq = 'TECH_NEVER' WHERE Type IN
('MILITARYAISTRATEGY_NEED_AIR', 'MILITARYAISTRATEGY_ENOUGH_AIR', 'MILITARYAISTRATEGY_NEED_ANTIAIR',			--NA
'MILITARYAISTRATEGY_NEED_NUKE', 'MILITARYAISTRATEGY_ENOUGH_ANTIAIR', 'MILITARYAISTRATEGY_NEED_AIR_CARRIER',	--NA
'MILITARYAISTRATEGY_NEED_RANGED', 'MILITARYAISTRATEGY_ENOUGH_RANGED', 'MILITARYAISTRATEGY_NEED_RANGED_EARLY',	--these may not work well with Ea unit system
'MILITARYAISTRATEGY_NEED_MOBILE', 'MILITARYAISTRATEGY_ENOUGH_MOBILE');			--NA

--Note: we could attach "enough" ranged and mobile to event, but for now we should just build highest flavor unit (ie, best unit)
--remember that ranged (archers) have good melee and can take cities in this mod
--what we really need is checks for city siege


--TO DO: Use utility tech to obsolete all strategies for gods



INSERT INTO EaDebugTableCheck(FileName) SELECT 'AI.sql';

--To Do:

--Diplomacy_Responses

