-- Contains PolicyBranchTypes and Policies


------------------------------------------------------------------------------------
-- Selectable Policies
------------------------------------------------------------------------------------
-- Holy cow this is badly coded!
-- policy branch  graphics are hard-coded in xml; order from id 0 to 9 are displayed as:
-- top row		0 1 2 3 4
-- bottom row	8 9 7 6 5

DELETE FROM PolicyBranchTypes;
INSERT INTO PolicyBranchTypes (Type,	Description,						Help,											Title,								EraPrereq,			FreePolicy,				FreeFinishingPolicy)
SELECT 'POLICY_BRANCH_DOMINIONISM',		'TXT_KEY_EA_POLICY_DOMINIONISM',	'TXT_KEY_EA_POLICY_BRANCH_DOMINIONISM_HELP',	'TXT_KEY_EA_DOMINIONISM_TITLE',		NULL,				'POLICY_DOMINIONISM',	'POLICY_DOMINIONISM_FINISHER'	UNION ALL
SELECT 'POLICY_BRANCH_PANTHEISM',		'TXT_KEY_EA_POLICY_PANTHEISM',		'TXT_KEY_EA_POLICY_BRANCH_PANTHEISM_HELP',		'TXT_KEY_EA_PANTHEISM_TITLE',		NULL,				'POLICY_PANTHEISM',		'POLICY_PANTHEISM_FINISHER'		UNION ALL
SELECT 'POLICY_BRANCH_THEISM',			'TXT_KEY_EA_POLICY_THEISM',			'TXT_KEY_EA_POLICY_BRANCH_THEISM_HELP',			'TXT_KEY_EA_THEISM_TITLE',			NULL,				'POLICY_THEISM',		'POLICY_THEISM_FINISHER'		UNION ALL
SELECT 'POLICY_BRANCH_ARCANA',			'TXT_KEY_EA_POLICY_ARCANA',			'TXT_KEY_EA_POLICY_BRANCH_ARCANA_HELP',			'TXT_KEY_EA_ARCANA_TITLE',			NULL,				'POLICY_ARCANA',		'POLICY_ARCANA_FINISHER'		UNION ALL
SELECT 'POLICY_BRANCH_SLAVERY',			'TXT_KEY_EA_POLICY_SLAVERY',		'TXT_KEY_EA_POLICY_BRANCH_SLAVERY_HELP',		'TXT_KEY_EA_SLAVERY_TITLE',			NULL,				'POLICY_SLAVERY',		'POLICY_SLAVERY_FINISHER'		UNION ALL
SELECT 'POLICY_BRANCH_CIV_ENABLED',		'TXT_KEY_EA_PLACEHOLDER',			'TXT_KEY_EA_POLICY_BRANCH_CIV_ENABLED_HELP',	'TXT_KEY_EA_PLACEHOLDER',			NULL,				'POLICY_CIV_ENABLED',	NULL							UNION ALL

SELECT 'POLICY_BRANCH_COMMERCE',		'TXT_KEY_EA_POLICY_COMMERCE',		'TXT_KEY_EA_POLICY_BRANCH_COMMERCE_HELP',		'TXT_KEY_EA_COMMERCE_TITLE',		NULL,				'POLICY_COMMERCE',		'POLICY_COMMERCE_FINISHER'		UNION ALL
SELECT 'POLICY_BRANCH_TRADITION',		'TXT_KEY_EA_POLICY_TRADITION',		'TXT_KEY_EA_POLICY_BRANCH_TRADITION_HELP',		'TXT_KEY_EA_TRADITION_TITLE',		NULL,				'POLICY_TRADITION',		'POLICY_TRADITION_FINISHER'		UNION ALL
SELECT 'POLICY_BRANCH_8',				'TXT_KEY_EA_PLACEHOLDER',			'TXT_KEY_EA_PLACEHOLDER',						'TXT_KEY_EA_PLACEHOLDER',			'ERA_CLASSICAL',	'POLICY_FAKE_OPENER',	NULL							UNION ALL
SELECT 'POLICY_BRANCH_MILITARISM',		'TXT_KEY_EA_POLICY_MILITARISM',		'TXT_KEY_EA_POLICY_BRANCH_MILITARISM_HELP',		'TXT_KEY_EA_MILITARISM_TITLE',		NULL,				'POLICY_MILITARISM',	'POLICY_MILITARISM_FINISHER'	UNION ALL
SELECT 'POLICY_BRANCH_ANTI_THEISM',		'TXT_KEY_EA_POLICY_THEISM',			'TXT_KEY_EA_POLICY_BRANCH_ANTI_THEISM_HELP',	'TXT_KEY_EA_THEISM_TITLE',			NULL,				'POLICY_ANTI_THEISM',	'POLICY_ANTI_THEISM_FINISHER'	;

DELETE FROM PolicyBranch_Disables;
INSERT INTO PolicyBranch_Disables (PolicyBranchType, PolicyBranchDisable)	--always in pairs!
SELECT 'POLICY_BRANCH_DOMINIONISM',	'POLICY_BRANCH_PANTHEISM'	UNION ALL
SELECT 'POLICY_BRANCH_PANTHEISM',	'POLICY_BRANCH_DOMINIONISM'	UNION ALL
SELECT 'POLICY_BRANCH_PANTHEISM',	'POLICY_BRANCH_THEISM'		UNION ALL
SELECT 'POLICY_BRANCH_THEISM',		'POLICY_BRANCH_PANTHEISM'	UNION ALL
SELECT 'POLICY_BRANCH_PANTHEISM',	'POLICY_BRANCH_ANTI_THEISM'	UNION ALL
SELECT 'POLICY_BRANCH_ANTI_THEISM',	'POLICY_BRANCH_PANTHEISM'	UNION ALL
SELECT 'POLICY_BRANCH_THEISM',		'POLICY_BRANCH_ARCANA'	UNION ALL
SELECT 'POLICY_BRANCH_ARCANA',		'POLICY_BRANCH_THEISM'	;
--SELECT 'POLICY_BRANCH_THEISM',		'POLICY_BRANCH_ANTI_THEISM'	UNION ALL
--SELECT 'POLICY_BRANCH_ANTI_THEISM',	'POLICY_BRANCH_THEISM'	;

DELETE FROM Policies;
ALTER TABLE Policies ADD COLUMN 'Utility' BOOLEAN DEFAULT NULL;
ALTER TABLE Policies ADD COLUMN 'EaCivTrait' TEXT DEFAULT NULL;			
ALTER TABLE Policies ADD COLUMN 'EaFirstInBranchGPClass' TEXT DEFAULT NULL;
ALTER TABLE Policies ADD COLUMN 'EaFirstInBranchGPSubclass' TEXT DEFAULT NULL;

--Dominionism
INSERT INTO Policies (Type,				GridX,	GridY,	PolicyBranchType,				PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_DOMINIONISM',			0,		0,		NULL,							24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ARISTOCRACY',			5,		1,		'POLICY_BRANCH_DOMINIONISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_FEUDALISM',				5,		2,		'POLICY_BRANCH_DOMINIONISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_GUILDS',					1,		1,		'POLICY_BRANCH_DOMINIONISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_TRADE_UNIONS',			1,		2,		'POLICY_BRANCH_DOMINIONISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_CIVIL_SERVICE',			3,		1,		'POLICY_BRANCH_DOMINIONISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_TAXATION',				3,		2,		'POLICY_BRANCH_DOMINIONISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		3,		3,		'POLICY_BRANCH_DOMINIONISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_DOMINIONISM_FINISHER',	0,		0,		NULL,							0,				NULL,			NULL ;

--Pantheism
INSERT INTO Policies (Type,				GridX,	GridY,	PolicyBranchType,				PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_PANTHEISM',				0,		0,		NULL,							24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ANIMAL_LORE',			1,		1,		'POLICY_BRANCH_PANTHEISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_FERAL_BOND',				1,		2,		'POLICY_BRANCH_PANTHEISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_COMMUNE_WITH_NATURE',	1,		3,		'POLICY_BRANCH_PANTHEISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_WOODS_LORE',				3,		1,		'POLICY_BRANCH_PANTHEISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_FELLOWSHIP_OF_LEAVES',	3,		2,		'POLICY_BRANCH_PANTHEISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_FOREST_DOMINION',		3,		3,		'POLICY_BRANCH_PANTHEISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_EARTH_LORE',				5,		1,		'POLICY_BRANCH_PANTHEISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_MANA_VORTEXES',			5,		2,		'POLICY_BRANCH_PANTHEISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_THROUGH_THE_VEIL',		5,		3,		'POLICY_BRANCH_PANTHEISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_PANTHEISM_FINISHER',		0,		0,		NULL,							0,				NULL,			NULL	;

--Theism
INSERT INTO Policies (Type,				GridX,	GridY,	PolicyBranchType,				PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_THEISM',					0,		0,		NULL,							24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_PRIESTHOOD',				1,		1,		'POLICY_BRANCH_THEISM',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_HOLY_ORDER',				1,		2,		'POLICY_BRANCH_THEISM',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_THEOCRACY',				1,		3,		'POLICY_BRANCH_THEISM',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_WAY_OF_THE_WISE',		3,		1,		'POLICY_BRANCH_THEISM',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_HEAVENS_MANDATE',		3,		2,		'POLICY_BRANCH_THEISM',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_MYSTICISM',				5,		1,		'POLICY_BRANCH_THEISM',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_MONASTIC_TRADITION',		5,		2,		'POLICY_BRANCH_THEISM',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_THEISM_FINISHER',		0,		0,		NULL,							0,				NULL,			NULL	;

--Anti-Theism (order here must mirror Theism exactly for proper swap in Lua code)
INSERT INTO Policies (Type,				GridX,	GridY,	PolicyBranchType,				PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_ANTI_THEISM',			0,		0,		NULL,							24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ANTI_PRIESTHOOD',		1,		1,		'POLICY_BRANCH_ANTI_THEISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ANTI_HOLY_ORDER',		1,		2,		'POLICY_BRANCH_ANTI_THEISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ANTI_THEOCRACY',			1,		3,		'POLICY_BRANCH_ANTI_THEISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ANTI_WAY_OF_THE_WISE',	3,		1,		'POLICY_BRANCH_ANTI_THEISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ANTI_HEAVENS_MANDATE',	3,		2,		'POLICY_BRANCH_ANTI_THEISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ANTI_MYSTICISM',			5,		1,		'POLICY_BRANCH_ANTI_THEISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ANTI_MONASTIC_TRADITION',5,		2,		'POLICY_BRANCH_ANTI_THEISM',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ANTI_THEISM_FINISHER',	0,		0,		NULL,							0,				NULL,			NULL	;

--Arcana
INSERT INTO Policies (Type,				GridX,	GridY,	PolicyBranchType,				PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_ARCANA',					0,		0,		NULL,							24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_WITCHCRAFT',				1,		1,		'POLICY_BRANCH_ARCANA',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ARCANE_TRADITION',		3,		1,		'POLICY_BRANCH_ARCANA',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ARCANE_LORE',			3,		2,		'POLICY_BRANCH_ARCANA',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ARCANE_RESEARCH',		3,		3,		'POLICY_BRANCH_ARCANA',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_SOCIO_ARCANA',			5,		1,		'POLICY_BRANCH_ARCANA',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ARCANE_ELITE',			5,		2,		'POLICY_BRANCH_ARCANA',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ARCANE_PRIMUS',			5,		3,		'POLICY_BRANCH_ARCANA',			24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ARCANA_FINISHER',		0,		0,		NULL,							0,				NULL,			NULL ;

--Slavery
INSERT INTO Policies (Type,				GridX,	GridY,	PolicyBranchType,				PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_SLAVERY',				0,		0,		NULL,							24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_DEBT_BONDAGE',			1,		1,		'POLICY_BRANCH_SLAVERY',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_SERVI_AETERNAM',			1,		3,		'POLICY_BRANCH_SLAVERY',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_SLAVE_TRADE',			3,		1,		'POLICY_BRANCH_SLAVERY',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_SLAVE_CASTES',			3,		2,		'POLICY_BRANCH_SLAVERY',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_SLAVE_BREEDING',			3,		3,		'POLICY_BRANCH_SLAVERY',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_SLAVE_RAIDERS',			5,		1,		'POLICY_BRANCH_SLAVERY',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_SLAVE_ARMIES',			5,		2,		'POLICY_BRANCH_SLAVERY',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_SLAVERY_FINISHER',		0,		0,		NULL,							0,				NULL,			NULL ;

--Militarism
INSERT INTO Policies (Type,				GridX,	GridY,	PolicyBranchType,				PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_MILITARISM',				0,		0,		NULL,							24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_DISCIPLINE',				3,		1,		'POLICY_BRANCH_MILITARISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_MILITARY_TRADITION',		3,		2,		'POLICY_BRANCH_MILITARISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_PROFESSIONAL_ARMY',		3,		3,		'POLICY_BRANCH_MILITARISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_WARCRAFT',				1,		1,		'POLICY_BRANCH_MILITARISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_WARRIOR_CODE',			1,		3,		'POLICY_BRANCH_MILITARISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_WARSPIRIT',				5,		1,		'POLICY_BRANCH_MILITARISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_BERSERKER_RAGE',			5,		2,		'POLICY_BRANCH_MILITARISM',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_MILITARISM_FINISHER',	0,		0,		NULL,							0,				NULL,			NULL ;

--Tradition
INSERT INTO Policies (Type,				GridX,	GridY,	PolicyBranchType,				PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_TRADITION',				0,		0,		NULL,							24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_FOLKLORE',				1,		1,		'POLICY_BRANCH_TRADITION',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_BARDING',				1,		2,		'POLICY_BRANCH_TRADITION',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_FOLKART',				3,		1,		'POLICY_BRANCH_TRADITION',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_CRAFTING',				3,		2,		'POLICY_BRANCH_TRADITION',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_THE_ARTS',				3,		3,		'POLICY_BRANCH_TRADITION',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_SCHOLASTICISM',			5,		1,		'POLICY_BRANCH_TRADITION',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ACADEMIC_TRADITION',		5,		2,		'POLICY_BRANCH_TRADITION',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_RATIONALISM',			5,		3,		'POLICY_BRANCH_TRADITION',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_TRADITION_FINISHER',		0,		0,		NULL,							0,				NULL,			NULL ;

--Commerce
INSERT INTO Policies (Type,				GridX,	GridY,	PolicyBranchType,				PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_COMMERCE',				0,		0,		NULL,							24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_MERCANTILISM',			3,		1,		'POLICY_BRANCH_COMMERCE',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_FREE_MARKETS',			3,		2,		'POLICY_BRANCH_COMMERCE',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_FREE_TRADE',				3,		3,		'POLICY_BRANCH_COMMERCE',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_MERCENARIES',			5,		1,		'POLICY_BRANCH_COMMERCE',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_MERCHANT_NAVY',			5,		2,		'POLICY_BRANCH_COMMERCE',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_CULTURAL_DIPLOMACY',		1,		1,		'POLICY_BRANCH_COMMERCE',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_PATRONAGE',				1,		2,		'POLICY_BRANCH_COMMERCE',		24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_COMMERCE_FINISHER',		0,		0,		NULL,							0,				NULL,			NULL ;

--Civ-Enabled
INSERT INTO Policies (Type,				PolicyBranchType,				PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_CIV_ENABLED',			NULL,							24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_PASTORALISTS',			'POLICY_BRANCH_CIV_ENABLED',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_MYSTICS',				'POLICY_BRANCH_CIV_ENABLED',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_HERBALISTS',				'POLICY_BRANCH_CIV_ENABLED',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_CONJURORS',				'POLICY_BRANCH_CIV_ENABLED',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ENCHANTERS',				'POLICY_BRANCH_CIV_ENABLED',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_DIVINATORS',				'POLICY_BRANCH_CIV_ENABLED',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_ALCHEMISTS',				'POLICY_BRANCH_CIV_ENABLED',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL
SELECT 'POLICY_POTION_MAKERS',			'POLICY_BRANCH_CIV_ENABLED',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' UNION ALL



SELECT 'POLICY_ANIMAL_MASTERS',			'POLICY_BRANCH_CIV_ENABLED',	24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' ;



INSERT INTO Policies (Type,				Utility,	GridX,	GridY,	PolicyBranchType,		PortraitIndex,	IconAtlas,		IconAtlasAchieved)
SELECT 'POLICY_FAKE_OPENER',			1,			0,		0,		NULL,					24,				'POLICY_ATLAS',	'POLICY_A_ATLAS' ;


--Build out the table for dependent strings
UPDATE Policies SET Description = 'TXT_KEY_EA_' || Type;
UPDATE Policies SET Civilopedia = Description || '_PEDIA', Help = Description || '_HELP';

--GPs (assign class or subclass, not both!)
UPDATE Policies SET EaFirstInBranchGPSubclass = 'Druid' WHERE Type IN ('POLICY_ANIMAL_LORE', 'POLICY_WOODS_LORE', 'POLICY_EARTH_LORE');
UPDATE Policies SET EaFirstInBranchGPSubclass = 'Priest' WHERE Type IN ('POLICY_PRIESTHOOD', 'POLICY_WAY_OF_THE_WISE', 'POLICY_MYSTICISM');
UPDATE Policies SET EaFirstInBranchGPSubclass = 'FallenPriest' WHERE Type IN ('POLICY_ANTI_PRIESTHOOD', 'POLICY_ANTI_WAY_OF_THE_WISE', 'POLICY_ANTI_MYSTICISM');
UPDATE Policies SET EaFirstInBranchGPClass = 'Thaumaturge' WHERE Type IN ('POLICY_ARCANE_TRADITION', 'POLICY_SOCIO_ARCANA');
UPDATE Policies SET EaFirstInBranchGPSubclass = 'Witch' WHERE Type = 'POLICY_WITCHCRAFT';
UPDATE Policies SET EaFirstInBranchGPClass = 'Warrior' WHERE Type IN ('POLICY_DISCIPLINE', 'POLICY_WARCRAFT');
UPDATE Policies SET EaFirstInBranchGPSubclass = 'Berserker' WHERE Type = 'POLICY_WARSPIRIT';
UPDATE Policies SET EaFirstInBranchGPClass = 'Artist' WHERE Type IN ('POLICY_FOLKLORE', 'POLICY_FOLKART');
UPDATE Policies SET EaFirstInBranchGPClass = 'Sage' WHERE Type = 'POLICY_SCHOLASTICISM';
UPDATE Policies SET EaFirstInBranchGPClass = 'Merchant' WHERE Type IN ('POLICY_MERCANTILISM', 'POLICY_MERCENARIES', 'POLICY_CULTURAL_DIPLOMACY');


UPDATE Policies SET CultureCost = 10 WHERE PolicyBranchType != NULL;		--don't think this does anything at all

--NumExtraBuilders?
UPDATE Policies SET UnhappinessMod = -33 WHERE Type = 'POLICY_FEUDALISM';
UPDATE Policies SET HalfSpecialistFood = 1 WHERE Type = 'POLICY_TRADE_UNIONS';
UPDATE Policies SET HalfSpecialistUnhappiness = 1 WHERE Type = 'POLICY_GUILDS';



--WoundedUnitDamageMod		--Negative value in base !!!???
--UnitSupplyMod
--CulturalPlunderMultiplier ???	--Receive 10 Culture as plunder for each point of Culture produced in the captured city.

--UnitGoldMaintenanceMod = -33

--BaseFreeMilitaryUnits
--FreeMilitaryUnitsPopulationPercent	--DOES NOT WORK

UPDATE Policies SET BaseFreeUnits = 4 WHERE Type = 'POLICY_MILITARISM';
UPDATE Policies SET UnitGoldMaintenanceMod = -10 WHERE Type = 'POLICY_DISCIPLINE';
UPDATE Policies SET UnitGoldMaintenanceMod = -10, GarrisonFreeMaintenance = 1, HappinessPerGarrisonedUnit = 1 WHERE Type = 'POLICY_MILITARY_TRADITION';
UPDATE Policies SET UnitGoldMaintenanceMod = -10, UnitUpgradeCostMod = -50 WHERE Type = 'POLICY_PROFESSIONAL_ARMY';
UPDATE Policies SET UnitGoldMaintenanceMod = -10, CultureFromKills = 100 WHERE Type = 'POLICY_WARRIOR_CODE';
UPDATE Policies SET UnitGoldMaintenanceMod = -10, ExpModifier = 100 WHERE Type = 'POLICY_WARCRAFT';
UPDATE Policies SET UnitGoldMaintenanceMod = -10 WHERE Type = 'POLICY_WARSPIRIT';
UPDATE Policies SET UnitGoldMaintenanceMod = -10 WHERE Type = 'POLICY_BERSERKER_RAGE';


UPDATE Policies SET CultureWonderMultiplier = 20 WHERE Type = 'POLICY_THE_ARTS';
--UPDATE Policies SET TradeRouteGoldModifier = 20 WHERE Type = 'POLICY_FREE_MARKETS';	--not used in base; works?
UPDATE Policies SET MinorGoldFriendshipMod = 25 WHERE Type = 'POLICY_CULTURAL_DIPLOMACY';
UPDATE Policies SET MinorFriendshipDecayMod = -50 WHERE Type = 'POLICY_PATRONAGE';


--SettlerProductionModifier
--RouteGoldMaintenanceMod

--MinorFriendshipDecayMod

-- EaCivs
INSERT INTO Policies (Type,	Utility)
SELECT 'POLICY_EACIV_ELEUTHERIOS',	1	UNION ALL
SELECT 'POLICY_EACIV_FIR_BOLG',		1	UNION ALL
SELECT 'POLICY_EACIV_CRUITHNI',		1	UNION ALL
SELECT 'POLICY_EACIV_CRECY',		1	UNION ALL
SELECT 'POLICY_EACIV_ALDEBAR',		1	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN',		1	UNION ALL
SELECT 'POLICY_EACIV_AXAGORIA',		1	UNION ALL
SELECT 'POLICY_EACIV_IACCHIA',		1	UNION ALL
SELECT 'POLICY_EACIV_SOPHRONIA',	1	UNION ALL
SELECT 'POLICY_EACIV_LUCHTAIN',		1	UNION ALL
SELECT 'POLICY_EACIV_ORKAHAUGR',	1	UNION ALL
SELECT 'POLICY_EACIV_KAZA',			1	UNION ALL		--can't do +10% from granary here
SELECT 'POLICY_EACIV_HOD',			1	UNION ALL
SELECT 'POLICY_EACIV_NEMEDIA',		1	UNION ALL
SELECT 'POLICY_EACIV_MOR',			1	UNION ALL
SELECT 'POLICY_EACIV_LOTHIN',		1	UNION ALL
SELECT 'POLICY_EACIV_YS',			1	UNION ALL
SELECT 'POLICY_EACIV_PALARE',		1	UNION ALL
SELECT 'POLICY_EACIV_SISUKAS',		1	UNION ALL
SELECT 'POLICY_EACIV_PHRYGES',		1	;



UPDATE Policies SET BuildingProductionModifier=20 WHERE Type IN ('POLICY_EACIV_SOPHRONIA', 'POLICY_EACIV_LUCHTAIN');
UPDATE Policies SET HappinessToScience = 50 WHERE Type = 'POLICY_EACIV_AXAGORIA';		--works?
UPDATE Policies SET HappinessToCulture = 50 WHERE Type = 'POLICY_EACIV_IACCHIA';
UPDATE Policies SET CultureFromKills = 100 WHERE Type = 'POLICY_EACIV_NEMEDIA';
UPDATE Policies SET CultureFromKills = 100 WHERE Type = 'POLICY_EACIV_MOR';	--change to mana?
UPDATE Policies SET GoldFromKills = 100 WHERE Type = 'POLICY_EACIV_LOTHIN';

-- Misc Utility Effects



INSERT INTO Policies (Type,	Utility)
SELECT 'POLICY_ALL_FULL_CIVS',				1	UNION ALL	--exists for all major civs but doesn't do anything yet
SELECT 'POLICY_FOOD_PLUS_PERCENT_0256',	1	UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0128',	1	UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0064',	1	UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0032',	1	UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0016',	1	UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0008',	1	UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0004',	1	UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0002',	1	UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0001',	1	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0256',	1	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0128',	1	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0064',	1	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0032',	1	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0016',	1	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0008',	1	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0004',	1	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0002',	1	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0001',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0256',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0128',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0064',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0032',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0016',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0008',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0004',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0002',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0001',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0256',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0128',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0064',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0032',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0016',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0008',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0004',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0002',	1	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0001',	1	UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0256',	1	UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0128',	1	UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0064',	1	UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0032',	1	UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0016',	1	UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0008',	1	UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0004',	1	UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0002',	1	UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0001',	1	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0256',	1	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0128',	1	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0064',	1	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0032',	1	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0016',	1	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0008',	1	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0004',	1	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0002',	1	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0001',	1	UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0256',	1	UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0128',	1	UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0064',	1	UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0032',	1	UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0016',	1	UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0008',	1	UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0004',	1	UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0002',	1	UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0001',	1	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0256',	1	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0128',	1	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0064',	1	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0032',	1	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0016',	1	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0008',	1	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0004',	1	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0002',	1	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0001',	1	UNION ALL

SELECT 'POLICY_FAITH_PLUS_PERCENT_0256',	1	UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0128',	1	UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0064',	1	UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0032',	1	UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0016',	1	UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0008',	1	UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0004',	1	UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0002',	1	UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0001',	1	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0256',	1	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0128',	1	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0064',	1	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0032',	1	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0016',	1	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0008',	1	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0004',	1	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0002',	1	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0001',	1	UNION ALL

SELECT 'POLICY_EQUUS_TOME_XP_0064',	1	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0032',	1	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0016',	1	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0008',	1	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0004',	1	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0002',	1	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0001',	1	UNION ALL

SELECT 'POLICY_LEVIATHAN_TOME',	1	;

-- housekeeping stuff for utility and EaTrates
UPDATE Policies SET Description='TXT_KEY_EA_PLACEHOLDER' WHERE Utility = 1;

------------------------------------------------------------------------------------
-- Policy Subtables
------------------------------------------------------------------------------------
--unused
DELETE FROM Policy_CoastalCityYieldChanges;
DELETE FROM Policy_Disables;
DELETE FROM Policy_Flavors;
DELETE FROM Policy_PrereqORPolicies;
DELETE FROM Policy_BuildingClassProductionModifiers;
DELETE FROM Policy_ValidSpecialists;
DELETE FROM Policy_UnitCombatProductionModifiers;
DELETE FROM Policy_FreeUnitClasses;
DELETE FROM Policy_FreeItems;
DELETE FROM Policy_FreePromotionUnitCombats;	--Does not work! Use Policy_FreePromotions together with UnitPromotions_UnitCombats

DELETE FROM Policy_GreatWorkYieldChanges;
DELETE FROM Policy_TourismOnUnitCreation;
DELETE FROM Policy_BuildingClassTourismModifiers;


DELETE FROM Policy_CapitalYieldChanges;
INSERT INTO Policy_CapitalYieldChanges(PolicyType, YieldType, Yield)
SELECT 'POLICY_PANTHEISM',				'YIELD_FAITH',		1	UNION ALL
SELECT 'POLICY_THEISM',					'YIELD_FAITH',		1	UNION ALL
SELECT 'POLICY_MYSTICISM',				'YIELD_FAITH',		3	UNION ALL
SELECT 'POLICY_HEAVENS_MANDATE',		'YIELD_FAITH',		3	UNION ALL
SELECT 'POLICY_ANTI_THEISM',			'YIELD_FAITH',		1	UNION ALL
SELECT 'POLICY_ANTI_MYSTICISM',			'YIELD_FAITH',		3	UNION ALL
SELECT 'POLICY_ANTI_HEAVENS_MANDATE',	'YIELD_FAITH',		5	UNION ALL
SELECT 'POLICY_TRADITION',				'YIELD_SCIENCE',	1	UNION ALL
SELECT 'POLICY_TRADITION',				'YIELD_CULTURE',	1	UNION ALL
SELECT 'POLICY_COMMERCE',				'YIELD_GOLD',		3	;

DELETE FROM Policy_CapitalYieldModifiers;
INSERT INTO Policy_CapitalYieldModifiers(PolicyType, YieldType, Yield)
SELECT 'POLICY_THEOCRACY',		'YIELD_GOLD',		20	UNION ALL
SELECT 'POLICY_ANTI_THEOCRACY',	'YIELD_SCIENCE',	20	;

DELETE FROM Policy_CityYieldChanges;
INSERT INTO Policy_CityYieldChanges (PolicyType,	YieldType,	Yield)
SELECT 'POLICY_SLAVE_CASTES',	'YIELD_PRODUCTION',	1	;

DELETE FROM Policy_CapitalYieldPerPopChanges;
INSERT INTO Policy_CapitalYieldPerPopChanges (PolicyType, YieldType, Yield)
SELECT 'POLICY_ARISTOCRACY',	'YIELD_GOLD',		100		UNION ALL
SELECT 'POLICY_CIVIL_SERVICE',	'YIELD_PRODUCTION',	50		UNION ALL
SELECT 'POLICY_EACIV_YS',	'YIELD_SCIENCE',	100	;

DELETE FROM Policy_HurryModifiers;
INSERT INTO Policy_HurryModifiers (PolicyType, HurryType, HurryCostModifier)
SELECT 'POLICY_MERCANTILISM', 'HURRY_GOLD', -25 ;

DELETE FROM Policy_PrereqPolicies;
INSERT INTO Policy_PrereqPolicies (PolicyType,	PrereqPolicy)	--Don't list openers
SELECT 'POLICY_FEUDALISM', 'POLICY_ARISTOCRACY' UNION ALL
SELECT 'POLICY_TRADE_UNIONS', 'POLICY_GUILDS' UNION ALL
SELECT 'POLICY_TAXATION', 'POLICY_CIVIL_SERVICE' UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION', 'POLICY_TRADE_UNIONS' UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION', 'POLICY_TAXATION' UNION ALL
SELECT 'POLICY_FERAL_BOND', 'POLICY_ANIMAL_LORE' UNION ALL
SELECT 'POLICY_COMMUNE_WITH_NATURE', 'POLICY_FERAL_BOND' UNION ALL
SELECT 'POLICY_COMMUNE_WITH_NATURE', 'POLICY_FELLOWSHIP_OF_LEAVES' UNION ALL
SELECT 'POLICY_FELLOWSHIP_OF_LEAVES', 'POLICY_WOODS_LORE' UNION ALL
SELECT 'POLICY_FOREST_DOMINION', 'POLICY_FELLOWSHIP_OF_LEAVES' UNION ALL
SELECT 'POLICY_MANA_VORTEXES', 'POLICY_EARTH_LORE' UNION ALL
SELECT 'POLICY_THROUGH_THE_VEIL', 'POLICY_FELLOWSHIP_OF_LEAVES' UNION ALL
SELECT 'POLICY_THROUGH_THE_VEIL', 'POLICY_MANA_VORTEXES' UNION ALL

SELECT 'POLICY_MONASTIC_TRADITION', 'POLICY_MYSTICISM' UNION ALL
SELECT 'POLICY_HEAVENS_MANDATE', 'POLICY_WAY_OF_THE_WISE' UNION ALL
SELECT 'POLICY_HOLY_ORDER', 'POLICY_PRIESTHOOD' UNION ALL
SELECT 'POLICY_THEOCRACY', 'POLICY_HEAVENS_MANDATE' UNION ALL
SELECT 'POLICY_THEOCRACY', 'POLICY_HOLY_ORDER' UNION ALL

SELECT 'POLICY_ANTI_MONASTIC_TRADITION', 'POLICY_ANTI_MYSTICISM' UNION ALL
SELECT 'POLICY_ANTI_HEAVENS_MANDATE', 'POLICY_ANTI_WAY_OF_THE_WISE' UNION ALL
SELECT 'POLICY_ANTI_HOLY_ORDER', 'POLICY_ANTI_PRIESTHOOD' UNION ALL
SELECT 'POLICY_ANTI_THEOCRACY', 'POLICY_ANTI_HEAVENS_MANDATE' UNION ALL
SELECT 'POLICY_ANTI_THEOCRACY', 'POLICY_ANTI_HOLY_ORDER' UNION ALL

SELECT 'POLICY_ARCANE_LORE', 'POLICY_WITCHCRAFT' UNION ALL
SELECT 'POLICY_ARCANE_LORE', 'POLICY_ARCANE_TRADITION' UNION ALL
SELECT 'POLICY_ARCANE_RESEARCH', 'POLICY_ARCANE_LORE' UNION ALL
SELECT 'POLICY_ARCANE_ELITE', 'POLICY_SOCIO_ARCANA' UNION ALL
SELECT 'POLICY_ARCANE_PRIMUS', 'POLICY_ARCANE_ELITE' UNION ALL

SELECT 'POLICY_SLAVE_CASTES', 'POLICY_SLAVE_TRADE' UNION ALL
SELECT 'POLICY_SLAVE_CASTES', 'POLICY_DEBT_BONDAGE' UNION ALL
SELECT 'POLICY_SERVI_AETERNAM', 'POLICY_SLAVE_CASTES' UNION ALL
SELECT 'POLICY_SLAVE_BREEDING', 'POLICY_SLAVE_CASTES' UNION ALL
SELECT 'POLICY_SLAVE_ARMIES', 'POLICY_SLAVE_RAIDERS' UNION ALL

SELECT 'POLICY_MILITARY_TRADITION', 'POLICY_DISCIPLINE' UNION ALL
SELECT 'POLICY_MILITARY_TRADITION', 'POLICY_WARCRAFT' UNION ALL
SELECT 'POLICY_WARRIOR_CODE', 'POLICY_MILITARY_TRADITION' UNION ALL
SELECT 'POLICY_PROFESSIONAL_ARMY', 'POLICY_MILITARY_TRADITION' UNION ALL
SELECT 'POLICY_BERSERKER_RAGE', 'POLICY_WARSPIRIT' UNION ALL

SELECT 'POLICY_BARDING', 'POLICY_FOLKLORE' UNION ALL
SELECT 'POLICY_CRAFTING', 'POLICY_FOLKART' UNION ALL
SELECT 'POLICY_THE_ARTS', 'POLICY_BARDING' UNION ALL
SELECT 'POLICY_THE_ARTS', 'POLICY_CRAFTING' UNION ALL
SELECT 'POLICY_THE_ARTS', 'POLICY_ACADEMIC_TRADITION' UNION ALL
SELECT 'POLICY_ACADEMIC_TRADITION', 'POLICY_SCHOLASTICISM' UNION ALL
SELECT 'POLICY_RATIONALISM', 'POLICY_ACADEMIC_TRADITION' UNION ALL

SELECT 'POLICY_FREE_MARKETS', 'POLICY_MERCANTILISM' UNION ALL
SELECT 'POLICY_FREE_TRADE', 'POLICY_FREE_MARKETS' UNION ALL
SELECT 'POLICY_MERCHANT_NAVY', 'POLICY_MERCANTILISM' UNION ALL
SELECT 'POLICY_PATRONAGE', 'POLICY_CULTURAL_DIPLOMACY' UNION ALL

SELECT 'POLICY_DIVINATORS', 'POLICY_MYSTICS' UNION ALL
SELECT 'POLICY_POTION_MAKERS', 'POLICY_HERBALISTS' UNION ALL
SELECT 'POLICY_POTION_MAKERS', 'POLICY_ALCHEMISTS' ;

DELETE FROM Policy_SpecialistExtraYields;
INSERT INTO Policy_SpecialistExtraYields (PolicyType,	YieldType,	Yield)
SELECT 'POLICY_TRADE_UNIONS',	'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_GUILDS',			'YIELD_PRODUCTION',	1	;

DELETE FROM Policy_BuildingClassYieldModifiers;
INSERT INTO Policy_BuildingClassYieldModifiers(PolicyType, BuildingClassType, YieldType, YieldMod)
SELECT 'POLICY_INDUSTRIALIZATION',	'BUILDINGCLASS_FACTORY',	'YIELD_PRODUCTION',	15	UNION ALL
SELECT 'POLICY_SCHOLASTICISM',		'BUILDINGCLASS_LIBRARY',	'YIELD_SCIENCE',	5	UNION ALL
SELECT 'POLICY_SCHOLASTICISM',		'BUILDINGCLASS_SCRIBES_GUILD','YIELD_SCIENCE',	1	UNION ALL
SELECT 'POLICY_SCHOLASTICISM',		'BUILDINGCLASS_MONASTIC_SCHOOL','YIELD_SCIENCE',3	UNION ALL
SELECT 'POLICY_SCHOLASTICISM',		'BUILDINGCLASS_APOTHECARY',	'YIELD_SCIENCE',	3	UNION ALL
SELECT 'POLICY_ACADEMIC_TRADITION',	'BUILDINGCLASS_PAPERMILL',	'YIELD_SCIENCE',	5	UNION ALL
SELECT 'POLICY_ACADEMIC_TRADITION',	'BUILDINGCLASS_UNIVERSITY',	'YIELD_SCIENCE',	15	UNION ALL
SELECT 'POLICY_ACADEMIC_TRADITION',	'BUILDINGCLASS_ACADEMY',	'YIELD_SCIENCE',	5	UNION ALL
SELECT 'POLICY_RATIONALISM',		'BUILDINGCLASS_PRINTING_PRESS',	'YIELD_SCIENCE',	5	UNION ALL
SELECT 'POLICY_RATIONALISM',		'BUILDINGCLASS_OBSERVATORY',	'YIELD_SCIENCE',	5	UNION ALL
SELECT 'POLICY_RATIONALISM',		'BUILDINGCLASS_LABORATORY',	'YIELD_SCIENCE',	15	UNION ALL
SELECT 'POLICY_THE_ARTS',			'BUILDINGCLASS_MUSEUM',		'YIELD_SCIENCE',	3	UNION ALL
SELECT 'POLICY_MERCANTILISM',		'BUILDINGCLASS_BANK',		'YIELD_GOLD',		15	UNION ALL
SELECT 'POLICY_MERCHANT_NAVY',		'BUILDINGCLASS_PORT',		'YIELD_GOLD',		15	UNION ALL
SELECT 'POLICY_EACIV_KAZA',		'BUILDINGCLASS_GRANARY',	'YIELD_FOOD',		15	;

DELETE FROM Policy_BuildingClassYieldChanges;
INSERT INTO Policy_BuildingClassYieldChanges (PolicyType, BuildingClassType, YieldType, YieldChange)
SELECT 'POLICY_MONASTIC_TRADITION',			'BUILDINGCLASS_MONASTERY',			'YIELD_CULTURE',	2 UNION ALL
SELECT 'POLICY_ANTI_MONASTIC_TRADITION',	'BUILDINGCLASS_MONASTERY',			'YIELD_SCIENCE',	2 UNION ALL
SELECT 'POLICY_MERCHANT_NAVY',				'BUILDINGCLASS_HARBOR',				'YIELD_GOLD',		1 UNION ALL
SELECT 'POLICY_MERCHANT_NAVY',				'BUILDINGCLASS_LIGHTHOUSE',			'YIELD_GOLD',		1 UNION ALL
SELECT 'POLICY_MERCHANT_NAVY',				'BUILDINGCLASS_PORT',				'YIELD_GOLD',		1 UNION ALL
SELECT 'POLICY_MERCHANT_NAVY',				'BUILDINGCLASS_SHIPYARD',			'YIELD_GOLD',		1 UNION ALL
SELECT 'POLICY_EACIV_HOD',				'BUILDINGCLASS_SHRINE',				'YIELD_FAITH',		2 UNION ALL
SELECT 'POLICY_EACIV_HOD',				'BUILDINGCLASS_MONASTIC_SCHOOL',	'YIELD_FAITH',		2 UNION ALL
SELECT 'POLICY_EACIV_HOD',				'BUILDINGCLASS_MONASTERY',			'YIELD_FAITH',		2 UNION ALL
SELECT 'POLICY_EACIV_HOD',				'BUILDINGCLASS_TEMPLE',				'YIELD_FAITH',		2 UNION ALL
SELECT 'POLICY_EACIV_HOD',				'BUILDINGCLASS_CATHEDRAL',			'YIELD_FAITH',		2 ;

DELETE FROM Policy_BuildingClassCultureChanges;
INSERT INTO Policy_BuildingClassCultureChanges (PolicyType, BuildingClassType, CultureChange)
SELECT 'POLICY_FOLKART',		'BUILDINGCLASS_FAIR',			1	UNION ALL
SELECT 'POLICY_FOLKART',		'BUILDINGCLASS_IVORYWORKS',		1	UNION ALL
SELECT 'POLICY_FOLKART',		'BUILDINGCLASS_JEWELLER',		1	UNION ALL
SELECT 'POLICY_CRAFTING',		'BUILDINGCLASS_WINERY',			1	UNION ALL
SELECT 'POLICY_CRAFTING',		'BUILDINGCLASS_BREWERY',		1	UNION ALL
SELECT 'POLICY_CRAFTING',		'BUILDINGCLASS_STONE_WORKS',	1	UNION ALL
SELECT 'POLICY_CRAFTING',		'BUILDINGCLASS_TEXTILE_MILL',	1	UNION ALL
SELECT 'POLICY_THE_ARTS',		'BUILDINGCLASS_THEATRE',		2	UNION ALL
SELECT 'POLICY_THE_ARTS',		'BUILDINGCLASS_OPERA_HOUSE',	2	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN','BUILDINGCLASS_SHRINE',			1	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN','BUILDINGCLASS_MONASTIC_SCHOOL',	1	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN','BUILDINGCLASS_MONASTERY',		1	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN','BUILDINGCLASS_TEMPLE',			1	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN','BUILDINGCLASS_CATHEDRAL',		1	;

DELETE FROM Policy_BuildingClassHappiness;												--Can add unhappiness
INSERT INTO Policy_BuildingClassHappiness (PolicyType, BuildingClassType, Happiness)
SELECT 'POLICY_ALL_FULL_CIVS',		'BUILDINGCLASS_PLUS_1_UNHAPPINESS',	-1	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN',	'BUILDINGCLASS_SHRINE',				1	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN',	'BUILDINGCLASS_MONASTIC_SCHOOL',	1	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN',	'BUILDINGCLASS_MONASTERY',			1	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN',	'BUILDINGCLASS_TEMPLE',				1	UNION ALL
SELECT 'POLICY_EACIV_ISALLIN',	'BUILDINGCLASS_CATHEDRAL',			1	UNION ALL
SELECT 'POLICY_EACIV_PALARE',		'BUILDINGCLASS_FAIR',				2	;


DELETE FROM Policy_ImprovementYieldChanges;
INSERT INTO Policy_ImprovementYieldChanges (PolicyType,	ImprovementType,	YieldType,	Yield)
SELECT 'POLICY_DOMINIONISM',			'IMPROVEMENT_FARM',				'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_DOMINIONISM',			'IMPROVEMENT_FARM_2',			'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_DOMINIONISM',			'IMPROVEMENT_PASTURE',			'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_FARM',				'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_FARM_2',			'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_PASTURE',			'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_MINE',				'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_MINE_2',			'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_QUARRY',			'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_E_PLANTATION',		'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_CAMP',				'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_VINEYARD',			'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_LUMBERMILL',		'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_LUMBERMILL_2',		'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_FISHING_BOATS',	'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_TAXATION',				'IMPROVEMENT_WHALING_BOATS',	'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_FARM',				'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_FARM_2',			'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_PASTURE',			'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_MINE',				'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_MINE_2',			'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_QUARRY',			'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_E_PLANTATION',		'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_CAMP',				'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_VINEYARD',			'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_LUMBERMILL',		'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_LUMBERMILL_2',		'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_FISHING_BOATS',	'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_INDUSTRIALIZATION',		'IMPROVEMENT_WHALING_BOATS',	'YIELD_PRODUCTION',	1	UNION ALL

SELECT 'POLICY_ANIMAL_LORE',			'IMPROVEMENT_PASTURE',			'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_ANIMAL_LORE',			'IMPROVEMENT_PASTURE',			'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_ANIMAL_LORE',			'IMPROVEMENT_CAMP',				'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_ANIMAL_LORE',			'IMPROVEMENT_CAMP',				'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_ANIMAL_LORE',			'IMPROVEMENT_FISHING_BOATS',	'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_ANIMAL_LORE',			'IMPROVEMENT_FISHING_BOATS',	'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_ANIMAL_LORE',			'IMPROVEMENT_WHALING_BOATS',	'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_ANIMAL_LORE',			'IMPROVEMENT_WHALING_BOATS',	'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_FERAL_BOND',				'IMPROVEMENT_PASTURE',			'YIELD_FAITH',		1	UNION ALL
SELECT 'POLICY_FERAL_BOND',				'IMPROVEMENT_CAMP',				'YIELD_FAITH',		1	UNION ALL
SELECT 'POLICY_FERAL_BOND',				'IMPROVEMENT_FISHING_BOATS',	'YIELD_FAITH',		1	UNION ALL
SELECT 'POLICY_FERAL_BOND',				'IMPROVEMENT_WHALING_BOATS',	'YIELD_FAITH',		1	UNION ALL
SELECT 'POLICY_WOODS_LORE',				'IMPROVEMENT_FARM',				'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_WOODS_LORE',				'IMPROVEMENT_FARM',				'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_WOODS_LORE',				'IMPROVEMENT_VINEYARD',			'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_WOODS_LORE',				'IMPROVEMENT_VINEYARD',			'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_WOODS_LORE',				'IMPROVEMENT_E_PLANTATION',		'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_WOODS_LORE',				'IMPROVEMENT_E_PLANTATION',		'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_FELLOWSHIP_OF_LEAVES',	'IMPROVEMENT_FARM',				'YIELD_FAITH',		1	UNION ALL
SELECT 'POLICY_FELLOWSHIP_OF_LEAVES',	'IMPROVEMENT_VINEYARD',			'YIELD_FAITH',		1	UNION ALL
SELECT 'POLICY_FELLOWSHIP_OF_LEAVES',	'IMPROVEMENT_E_PLANTATION',		'YIELD_FAITH',		1	UNION ALL
SELECT 'POLICY_EARTH_LORE',				'IMPROVEMENT_MINE',				'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_EARTH_LORE',				'IMPROVEMENT_QUARRY',			'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_MANA_VORTEXES',			'IMPROVEMENT_MINE',				'YIELD_SCIENCE',	1	UNION ALL
SELECT 'POLICY_MANA_VORTEXES',			'IMPROVEMENT_MINE',				'YIELD_FAITH',		2	UNION ALL
SELECT 'POLICY_MANA_VORTEXES',			'IMPROVEMENT_QUARRY',			'YIELD_SCIENCE',	1	UNION ALL
SELECT 'POLICY_MANA_VORTEXES',			'IMPROVEMENT_QUARRY',			'YIELD_FAITH',		2	UNION ALL
SELECT 'POLICY_EACIV_ELEUTHERIOS',		'IMPROVEMENT_VINEYARD',			'YIELD_GOLD',		2	UNION ALL
SELECT 'POLICY_EACIV_FIR_BOLG',			'IMPROVEMENT_PASTURE',			'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_EACIV_FIR_BOLG',			'IMPROVEMENT_PASTURE',			'YIELD_GOLD',		1	UNION ALL
SELECT 'POLICY_EACIV_CRUITHNI',			'IMPROVEMENT_CAMP',				'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_EACIV_CRUITHNI',			'IMPROVEMENT_CAMP',				'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_EACIV_ORKAHAUGR',		'IMPROVEMENT_MINE',				'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_EACIV_ORKAHAUGR',		'IMPROVEMENT_MINE',				'YIELD_FOOD',		1	UNION ALL
SELECT 'POLICY_EACIV_ORKAHAUGR',		'IMPROVEMENT_MINE_2',			'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'POLICY_EACIV_ORKAHAUGR',		'IMPROVEMENT_MINE_2',			'YIELD_FOOD',		1	UNION ALL

SELECT 'POLICY_LEVIATHAN_TOME',			'IMPROVEMENT_WHALING_BOATS',	'YIELD_SCIENCE',	2	;




DELETE FROM Policy_ImprovementCultureChanges;
INSERT INTO Policy_ImprovementCultureChanges (PolicyType, ImprovementType, CultureChange)
SELECT 'POLICY_FERAL_BOND',				'IMPROVEMENT_PASTURE',		1	UNION ALL
SELECT 'POLICY_FERAL_BOND',				'IMPROVEMENT_CAMP',			1	UNION ALL
SELECT 'POLICY_FERAL_BOND',				'IMPROVEMENT_FISHING_BOATS',1	UNION ALL
SELECT 'POLICY_FERAL_BOND',				'IMPROVEMENT_WHALING_BOATS',1	UNION ALL
SELECT 'POLICY_FELLOWSHIP_OF_LEAVES',	'IMPROVEMENT_FARM',			1	UNION ALL
SELECT 'POLICY_FELLOWSHIP_OF_LEAVES',	'IMPROVEMENT_VINEYARD',		1	UNION ALL
SELECT 'POLICY_FELLOWSHIP_OF_LEAVES',	'IMPROVEMENT_E_PLANTATION',	1	UNION ALL
SELECT 'POLICY_EARTH_LORE',				'IMPROVEMENT_MINE',			1	UNION ALL
SELECT 'POLICY_EARTH_LORE',				'IMPROVEMENT_QUARRY',		1	UNION ALL

--SELECT 'POLICY_FOLKART',				'IMPROVEMENT_FESTIVAL',		1	UNION ALL
SELECT 'POLICY_CRAFTING',				'IMPROVEMENT_VINEYARD',		1	UNION ALL
SELECT 'POLICY_CRAFTING',				'IMPROVEMENT_QUARRY',		1	UNION ALL
SELECT 'POLICY_EACIV_ELEUTHERIOS',		'IMPROVEMENT_VINEYARD',		3	UNION ALL
SELECT 'POLICY_EACIV_ALDEBAR',			'IMPROVEMENT_E_PLANTATION',	2	;

DELETE FROM Policy_YieldModifiers;
INSERT INTO Policy_YieldModifiers (PolicyType, YieldType, Yield)	--not in base but it works
SELECT 'POLICY_FOOD_PLUS_PERCENT_0256', 'YIELD_FOOD',	256		UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0128', 'YIELD_FOOD',	128		UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0064', 'YIELD_FOOD',	64		UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0032', 'YIELD_FOOD',	32		UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0016', 'YIELD_FOOD',	16		UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0008', 'YIELD_FOOD',	8		UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0004', 'YIELD_FOOD',	4		UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0002', 'YIELD_FOOD',	2		UNION ALL
SELECT 'POLICY_FOOD_PLUS_PERCENT_0001', 'YIELD_FOOD',	1		UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0256', 'YIELD_FOOD',	-256	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0128', 'YIELD_FOOD',	-128	UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0064', 'YIELD_FOOD',	-64		UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0032', 'YIELD_FOOD',	-32		UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0016', 'YIELD_FOOD',	-16		UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0008', 'YIELD_FOOD',	-8		UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0004', 'YIELD_FOOD',	-4		UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0002', 'YIELD_FOOD',	-2		UNION ALL
SELECT 'POLICY_FOOD_MINUS_PERCENT_0001', 'YIELD_FOOD',	-1		UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0256', 'YIELD_PRODUCTION',	256		UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0128', 'YIELD_PRODUCTION',	128		UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0064', 'YIELD_PRODUCTION',	64		UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0032', 'YIELD_PRODUCTION',	32		UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0016', 'YIELD_PRODUCTION',	16		UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0008', 'YIELD_PRODUCTION',	8		UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0004', 'YIELD_PRODUCTION',	4		UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0002', 'YIELD_PRODUCTION',	2		UNION ALL
SELECT 'POLICY_PRODUCTION_PLUS_PERCENT_0001', 'YIELD_PRODUCTION',	1		UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0256', 'YIELD_PRODUCTION',	-256	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0128', 'YIELD_PRODUCTION',	-128	UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0064', 'YIELD_PRODUCTION',	-64		UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0032', 'YIELD_PRODUCTION',	-32		UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0016', 'YIELD_PRODUCTION',	-16		UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0008', 'YIELD_PRODUCTION',	-8		UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0004', 'YIELD_PRODUCTION',	-4		UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0002', 'YIELD_PRODUCTION',	-2		UNION ALL
SELECT 'POLICY_PRODUCTION_MINUS_PERCENT_0001', 'YIELD_PRODUCTION',	-1		UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0256', 'YIELD_GOLD',	256		UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0128', 'YIELD_GOLD',	128		UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0064', 'YIELD_GOLD',	64		UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0032', 'YIELD_GOLD',	32		UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0016', 'YIELD_GOLD',	16		UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0008', 'YIELD_GOLD',	8		UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0004', 'YIELD_GOLD',	4		UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0002', 'YIELD_GOLD',	2		UNION ALL
SELECT 'POLICY_GOLD_PLUS_PERCENT_0001', 'YIELD_GOLD',	1		UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0256', 'YIELD_GOLD',	-256	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0128', 'YIELD_GOLD',	-128	UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0064', 'YIELD_GOLD',	-64		UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0032', 'YIELD_GOLD',	-32		UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0016', 'YIELD_GOLD',	-16		UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0008', 'YIELD_GOLD',	-8		UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0004', 'YIELD_GOLD',	-4		UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0002', 'YIELD_GOLD',	-2		UNION ALL
SELECT 'POLICY_GOLD_MINUS_PERCENT_0001', 'YIELD_GOLD',	-1		UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0256', 'YIELD_SCIENCE',		256		UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0128', 'YIELD_SCIENCE',		128		UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0064', 'YIELD_SCIENCE',		64		UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0032', 'YIELD_SCIENCE',		32		UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0016', 'YIELD_SCIENCE',		16		UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0008', 'YIELD_SCIENCE',		8		UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0004', 'YIELD_SCIENCE',		4		UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0002', 'YIELD_SCIENCE',		2		UNION ALL
SELECT 'POLICY_SCIENCE_PLUS_PERCENT_0001', 'YIELD_SCIENCE',		1		UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0256', 'YIELD_SCIENCE',	-256	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0128', 'YIELD_SCIENCE',	-128	UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0064', 'YIELD_SCIENCE',	-64		UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0032', 'YIELD_SCIENCE',	-32		UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0016', 'YIELD_SCIENCE',	-16		UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0008', 'YIELD_SCIENCE',	-8		UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0004', 'YIELD_SCIENCE',	-4		UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0002', 'YIELD_SCIENCE',	-2		UNION ALL
SELECT 'POLICY_SCIENCE_MINUS_PERCENT_0001', 'YIELD_SCIENCE',	-1		UNION ALL

SELECT 'POLICY_FAITH_PLUS_PERCENT_0256', 'YIELD_FAITH',		256		UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0128', 'YIELD_FAITH',		128		UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0064', 'YIELD_FAITH',		64		UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0032', 'YIELD_FAITH',		32		UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0016', 'YIELD_FAITH',		16		UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0008', 'YIELD_FAITH',		8		UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0004', 'YIELD_FAITH',		4		UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0002', 'YIELD_FAITH',		2		UNION ALL
SELECT 'POLICY_FAITH_PLUS_PERCENT_0001', 'YIELD_FAITH',		1		UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0256', 'YIELD_FAITH',	-256	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0128', 'YIELD_FAITH',	-128	UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0064', 'YIELD_FAITH',	-64		UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0032', 'YIELD_FAITH',	-32		UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0016', 'YIELD_FAITH',	-16		UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0008', 'YIELD_FAITH',	-8		UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0004', 'YIELD_FAITH',	-4		UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0002', 'YIELD_FAITH',	-2		UNION ALL
SELECT 'POLICY_FAITH_MINUS_PERCENT_0001', 'YIELD_FAITH',	-1		;

DELETE FROM Policy_FreePromotions;		--Works if promo in UnitPromotions_UnitCombats. Will transfer to other civ. Can be removed (stays removed)
INSERT INTO Policy_FreePromotions (PolicyType,	PromotionType)
SELECT 'POLICY_SLAVE_RAIDERS',		'PROMOTION_SLAVERAIDER'			UNION ALL
SELECT 'POLICY_SLAVE_ARMIES',		'PROMOTION_SLAVEMAKER'			UNION ALL
SELECT 'POLICY_DISCIPLINE',			'PROMOTION_ADJACENT_BONUS'		UNION ALL
SELECT 'POLICY_MERCHANT_NAVY',		'PROMOTION_NAVAL_TRADITION'		UNION ALL
SELECT 'POLICY_EACIV_SISUKAS',	'PROMOTION_STRONG_INFANTRY'		UNION ALL
SELECT 'POLICY_EACIV_CRECY',		'PROMOTION_STRONG_ARCHER'		UNION ALL
SELECT 'POLICY_EACIV_PHRYGES',	'PROMOTION_STRONG_CAVALRY'		;



DELETE FROM Policy_UnitCombatFreeExperiences;
INSERT INTO Policy_UnitCombatFreeExperiences (PolicyType,	UnitCombatType,	FreeExperience)
SELECT 'POLICY_EQUUS_TOME_XP_0064',	'UNITCOMBAT_MOUNTED',	64	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0032',	'UNITCOMBAT_MOUNTED',	32	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0016',	'UNITCOMBAT_MOUNTED',	16	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0008',	'UNITCOMBAT_MOUNTED',	8	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0004',	'UNITCOMBAT_MOUNTED',	4	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0002',	'UNITCOMBAT_MOUNTED',	2	UNION ALL
SELECT 'POLICY_EQUUS_TOME_XP_0001',	'UNITCOMBAT_MOUNTED',	1	;

-- fixinator
CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM Policies ORDER BY ID;
UPDATE Policies SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Policies.Type = IDRemapper.Type);
DROP TABLE IDRemapper;

CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM PolicyBranchTypes ORDER BY ID;
UPDATE PolicyBranchTypes SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE PolicyBranchTypes.Type = IDRemapper.Type);
DROP TABLE IDRemapper;


INSERT INTO EaDebugTableCheck(FileName) SELECT 'Policies.sql';