-------------------------------------------------------------------------
-- Processes 
-------------------------------------------------------------------------
DELETE FROM Processes;
ALTER TABLE Processes ADD COLUMN 'EaPolicyPrereq' TEXT DEFAULT NULL;

INSERT INTO Processes (Type,				Description,									Help,												Strategy,												EaPolicyPrereq,					IconAtlas,			PortraitIndex)	--all are policy dependent controled in City.lua
SELECT 'PROCESS_INDUSTRIAL_AGRICULTURE',	'TXT_KEY_EA_PROCESS_INDUSTRIAL_AGRICULTURE',	'TXT_KEY_EA_PROCESS_INDUSTRIAL_AGRICULTURE_HELP',	'TXT_KEY_EA_PROCESS_INDUSTRIAL_AGRICULTURE_STRATEGY',	'POLICY_INDUSTRIALIZATION',		'RESOURCE_ATLAS',				6			UNION ALL
SELECT 'PROCESS_WORLD_WEAVE',				'TXT_KEY_EA_PROCESS_WORLD_WEAVE',				'TXT_KEY_EA_PROCESS_WORLD_WEAVE_HELP',				'TXT_KEY_EA_PROCESS_WORLD_WEAVE_STRATEGY',				'POLICY_COMMUNE_WITH_NATURE',	'BW_ATLAS_2',					2			UNION ALL
SELECT 'PROCESS_EA_BLESSINGS',				'TXT_KEY_EA_PROCESS_EA_BLESSINGS',				'TXT_KEY_EA_PROCESS_EA_BLESSINGS_HELP',				'TXT_KEY_EA_PROCESS_EA_BLESSINGS_STRATEGY',				'POLICY_FOREST_DOMINION',		'NW_ATLAS_DLC',					1			UNION ALL
SELECT 'PROCESS_MAJOR_SPIRITS_TRIBUTE',		'TXT_KEY_EA_PROCESS_MAJOR_SPIRITS_TRIBUTE',		'TXT_KEY_EA_PROCESS_MAJOR_SPIRITS_TRIBUTE_HELP',	'TXT_KEY_EA_PROCESS_MAJOR_SPIRITS_TRIBUTE_STRATEGY',	'POLICY_MANA_VORTEXES',			'EXPANSION_BW_ATLAS_2',			10			UNION ALL
SELECT 'PROCESS_FAERIES_TRIBUTE',			'TXT_KEY_EA_PROCESS_FAERIES_TRIBUTE',			'TXT_KEY_EA_PROCESS_FAERIES_TRIBUTE_HELP',			'TXT_KEY_EA_PROCESS_FAERIES_TRIBUTE_STRATEGY',			'POLICY_THROUGH_THE_VEIL',		'NW_ATLAS',						0			UNION ALL
SELECT 'PROCESS_AZZANDARAS_TRIBUTE',		'TXT_KEY_EA_PROCESS_AZZANDARAS_TRIBUTE',		'TXT_KEY_EA_PROCESS_AZZANDARAS_TRIBUTE_HELP',		'TXT_KEY_EA_PROCESS_AZZANDARAS_TRIBUTE_STRATEGY',		'POLICY_HEAVENS_MANDATE',		'BW_ATLAS_2',					17			UNION ALL
SELECT 'PROCESS_WORLD_SALVATION',			'TXT_KEY_EA_PROCESS_WORLD_SALVATION',			'TXT_KEY_EA_PROCESS_WORLD_SALVATION_HELP',			'TXT_KEY_EA_PROCESS_WORLD_SALVATION_STRATEGY',			'POLICY_COMMUNE_WITH_NATURE',	'EXPANSION_UNIT_ATLAS_1',		20			UNION ALL
SELECT 'PROCESS_AHRIMANS_TRIBUTE',			'TXT_KEY_EA_PROCESS_AHRIMANS_TRIBUTE',			'TXT_KEY_EA_PROCESS_AHRIMANS_TRIBUTE_HELP',			'TXT_KEY_EA_PROCESS_AHRIMANS_TRIBUTE_STRATEGY',			'POLICY_ANTI_HEAVENS_MANDATE',	'TECH_ATLAS_2',					9			UNION ALL
SELECT 'PROCESS_WORLD_CORRUPTION',			'TXT_KEY_EA_PROCESS_WORLD_CORRUPTION',			'TXT_KEY_EA_PROCESS_WORLD_CORRUPTION_HELP',			'TXT_KEY_EA_PROCESS_WORLD_CORRUPTION_STRATEGY',			'POLICY_ANTI_THEOCRACY',		'EXPANSION_UNIT_ATLAS_1',		17			UNION ALL
SELECT 'PROCESS_OPPRESSION',				'TXT_KEY_EA_PROCESS_OPPRESSION',				'TXT_KEY_EA_PROCESS_OPPRESSION_HELP',				'TXT_KEY_EA_PROCESS_OPPRESSION_STRATEGY',				'POLICY_SERVI_AETERNAM',		'BW_ATLAS_2',					43			UNION ALL
SELECT 'PROCESS_TRAINING_EXERCISES',		'TXT_KEY_EA_PROCESS_TRAINING_EXERCISES',		'TXT_KEY_EA_PROCESS_TRAINING_EXERCISES_HELP',		'TXT_KEY_EA_PROCESS_TRAINING_EXERCISES_STRATEGY',		'POLICY_PROFESSIONAL_ARMY',		'BW_ATLAS_1',					6			UNION ALL
SELECT 'PROCESS_THE_ARTS',					'TXT_KEY_EA_PROCESS_THE_ARTS',					'TXT_KEY_EA_PROCESS_THE_ARTS_HELP',					'TXT_KEY_EA_PROCESS_THE_ARTS_STRATEGY',					'POLICY_THE_ARTS',				'EXPANSION_TECH_ATLAS_1',		4			UNION ALL
SELECT 'PROCESS_RESEARCH',					'TXT_KEY_EA_PROCESS_RESEARCH',					'TXT_KEY_EA_PROCESS_RESEARCH_HELP',					'TXT_KEY_EA_PROCESS_RESEARCH_STRATEGY',					'POLICY_RATIONALISM',			'EXPANSION_SCEN_TECH_ATLAS',	2			UNION ALL
SELECT 'PROCESS_TRADE_SURPLUS',				'TXT_KEY_EA_PROCESS_TRADE_SURPLUS',				'TXT_KEY_EA_PROCESS_TRADE_SURPLUS_HELP',			'TXT_KEY_EA_PROCESS_TRADE_SURPLUS_STRATEGY',			'POLICY_MERCANTILISM',			'EXPANSION_TECH_ATLAS_1',		2			UNION ALL
SELECT 'PROCESS_PATRONAGE',					'TXT_KEY_EA_PROCESS_PATRONAGE',					'TXT_KEY_EA_PROCESS_PATRONAGE_HELP',				'TXT_KEY_EA_PROCESS_PATRONAGE_STRATEGY',				'POLICY_PATRONAGE',				'EXPANSION_SCEN_TECH_ATLAS',	3			;

--disabled until complete:
UPDATE Processes SET TechPrereq = 'TECH_NEVER' WHERE Type IN ('PROCESS_OPPRESSION');

--debug
--UPDATE Processes SET EaPolicyPrereq = NULL;

DELETE FROM Process_Flavors;
INSERT INTO Process_Flavors (ProcessType,	FlavorType,	Flavor)
SELECT 'PROCESS_INDUSTRIAL_AGRICULTURE',	'FLAVOR_GROWTH',			25	UNION ALL
SELECT 'PROCESS_WORLD_WEAVE',				'FLAVOR_RELIGION',			25	UNION ALL
SELECT 'PROCESS_EA_BLESSINGS',				'FLAVOR_RELIGION',			25	UNION ALL
SELECT 'PROCESS_MAJOR_SPIRITS_TRIBUTE',		'FLAVOR_RELIGION',			10	UNION ALL
SELECT 'PROCESS_MAJOR_SPIRITS_TRIBUTE',		'FLAVOR_DIPLOMACY',			10	UNION ALL
SELECT 'PROCESS_FAERIES_TRIBUTE',			'FLAVOR_RELIGION',			10	UNION ALL
SELECT 'PROCESS_FAERIES_TRIBUTE',			'FLAVOR_DIPLOMACY',			10	UNION ALL
SELECT 'PROCESS_AZZANDARAS_TRIBUTE',		'FLAVOR_RELIGION',			25	UNION ALL
SELECT 'PROCESS_WORLD_SALVATION',			'FLAVOR_RELIGION',			25	UNION ALL
SELECT 'PROCESS_AHRIMANS_TRIBUTE',			'FLAVOR_RELIGION',			25	UNION ALL
SELECT 'PROCESS_WORLD_CORRUPTION',			'FLAVOR_RELIGION',			25	UNION ALL
SELECT 'PROCESS_OPPRESSION',				'FLAVOR_PRODUCTION',		25	UNION ALL
SELECT 'PROCESS_OPPRESSION',				'FLAVOR_HAPPINESS',			25	UNION ALL
SELECT 'PROCESS_TRAINING_EXERCISES',		'FLAVOR_MILITARY_TRAINING',	25	UNION ALL
SELECT 'PROCESS_RESEARCH',					'FLAVOR_SCIENCE',			25	UNION ALL
SELECT 'PROCESS_THE_ARTS',					'FLAVOR_CULTURE',			25	UNION ALL
SELECT 'PROCESS_TRADE_SURPLUS',				'FLAVOR_DIPLOMACY',			25	UNION ALL
SELECT 'PROCESS_TRADE_SURPLUS',				'FLAVOR_GOLD',				25	UNION ALL
SELECT 'PROCESS_PATRONAGE',					'FLAVOR_DIPLOMACY',			25	;

DELETE FROM Process_ProductionYields;
INSERT INTO Process_ProductionYields (ProcessType,	YieldType,	Yield)
SELECT 'PROCESS_TRADE_SURPLUS',	'YIELD_GOLD',		25	UNION ALL
SELECT 'PROCESS_RESEARCH',		'YIELD_SCIENCE',	25	;

-- fixinator
CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM Processes ORDER BY ID;
UPDATE Processes SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Processes.Type = IDRemapper.Type);
DROP TABLE IDRemapper;

INSERT INTO EaDebugTableCheck(FileName) SELECT 'Processes.sql';