
--EaInitialBelief
DELETE FROM Religions WHERE Type <> 'RELIGION_PANTHEON';	--need to keep pantheon for dll?
ALTER TABLE Religions ADD COLUMN 'EaInitialBelief' TEXT DEFAULT NULL;
ALTER TABLE Religions ADD COLUMN 'EaInitialBelief2' TEXT DEFAULT NULL;
ALTER TABLE Religions ADD COLUMN 'EaInitialBelief3' TEXT DEFAULT NULL;
ALTER TABLE Religions ADD COLUMN 'EaFreeCultSpell' TEXT DEFAULT NULL;
ALTER TABLE Religions ADD COLUMN 'EaStrategy' TEXT DEFAULT NULL;
ALTER TABLE Religions ADD COLUMN 'EaFollowerBuilding' TEXT DEFAULT NULL;

INSERT INTO Religions (Type,			Description,								Civilopedia,										EaStrategy,											EaFollowerBuilding,						EaFreeCultSpell,				EaInitialBelief,						EaInitialBelief2,						EaInitialBelief3,						IconAtlas,				PortraitIndex,	IconString)
SELECT 'RELIGION_AZZANDARAYASNA',		'TXT_KEY_EA_RELIGION_AZZANDARAYASNA',		'TXT_KEY_EA_RELIGION_AZZANDARAYASNA_PEDIA',			'TXT_KEY_EA_RELIGION_AZZANDARAYASNA_STRATEGY',		NULL,									NULL,							'BELIEF_AZZANDARAYASNA_FOUNDER',		'BELIEF_AZZANDARAYASNA_FOLLOWER',		NULL,									'EA_RELIGION_ATLAS',	0,				'[ICON_RELIGION_AZZANDARAYASNA]'	UNION ALL
SELECT 'RELIGION_ANRA',					'TXT_KEY_EA_RELIGION_ANRA',					'TXT_KEY_EA_RELIGION_ANRA_PEDIA',					'TXT_KEY_EA_RELIGION_ANRA_STRATEGY',				'BUILDING_ANRA_FOLLOWER',				NULL,							'BELIEF_ANRA_FOUNDER',					'BELIEF_ANRA_FOLLOWER',					NULL,									'EA_RELIGION_ATLAS',	1,				'[ICON_RELIGION_ANRA]'				UNION ALL
--order matters below: all religions that follow The Weave of Ea are treated as cults within that religion
SELECT 'RELIGION_THE_WEAVE_OF_EA',		'TXT_KEY_EA_RELIGION_THE_WEAVE_OF_EA',		'TXT_KEY_EA_RELIGION_THE_WEAVE_OF_EA_PEDIA',		NULL,												NULL,									NULL,							'BELIEF_THE_WEAVE_OF_EA_FOLLOWER',		NULL,									NULL,									'EA_RELIGION_ATLAS',	2,				'[ICON_RELIGION_THE_WEAVE]'			UNION ALL
SELECT 'RELIGION_CULT_OF_LEAVES',		'TXT_KEY_EA_RELIGION_CULT_OF_LEAVES',		'TXT_KEY_EA_RELIGION_CULT_OF_LEAVES_PEDIA',			'TXT_KEY_EA_RELIGION_CULT_OF_LEAVES_STRATEGY',		NULL,									'EA_SPELL_BLOOM',				'BELIEF_THE_WEAVE_OF_EA_FOLLOWER',		'BELIEF_CULT_OF_LEAVES_FOUNDER',		'BELIEF_CULT_OF_LEAVES_FOLLOWER',		'EA_RELIGION_ATLAS',	3,				'[ICON_CULT_OF_LEAVES]'				UNION ALL
SELECT 'RELIGION_CULT_OF_EPONA',		'TXT_KEY_EA_RELIGION_CULT_OF_EPONA',		'TXT_KEY_EA_RELIGION_CULT_OF_EPONA_PEDIA',			'TXT_KEY_EA_RELIGION_CULT_OF_EPONA_STRATEGY',		'BUILDING_CULT_OF_EPONA_FOLLOWER',		'EA_SPELL_RIDE_LIKE_THE_WIND',	'BELIEF_THE_WEAVE_OF_EA_FOLLOWER',		'BELIEF_CULT_OF_EPONA_FOUNDER',			'BELIEF_CULT_OF_EPONA_FOLLOWER',		'EA_RELIGION_ATLAS',	5,				'[ICON_CULT_OF_EPONA]'				UNION ALL
SELECT 'RELIGION_CULT_OF_PURE_WATERS',	'TXT_KEY_EA_RELIGION_CULT_OF_PURE_WATERS',	'TXT_KEY_EA_RELIGION_CULT_OF_PURE_WATERS_PEDIA',	'TXT_KEY_EA_RELIGION_CULT_OF_PURE_WATERS_STRATEGY',	NULL,									'EA_SPELL_PURIFY',				'BELIEF_THE_WEAVE_OF_EA_FOLLOWER',		'BELIEF_CULT_OF_PURE_WATERS_FOUNDER',	'BELIEF_CULT_OF_PURE_WATERS_FOLLOWER',	'EA_RELIGION_ATLAS',	6,				'[ICON_CULT_OF_PURE_WATERS]'		UNION ALL
SELECT 'RELIGION_CULT_OF_AEGIR',		'TXT_KEY_EA_RELIGION_CULT_OF_AEGIR',		'TXT_KEY_EA_RELIGION_CULT_OF_AEGIR_PEDIA',			'TXT_KEY_EA_RELIGION_CULT_OF_AEGIR_STRATEGY',		NULL,									'EA_SPELL_FAIR_WINDS',			'BELIEF_THE_WEAVE_OF_EA_FOLLOWER',		'BELIEF_CULT_OF_AEGIR_FOUNDER',			'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'EA_RELIGION_ATLAS',	7,				'[ICON_CULT_OF_AEGIR]'				UNION ALL
SELECT 'RELIGION_CULT_OF_BAKKHEIA',		'TXT_KEY_EA_RELIGION_CULT_OF_BAKKHEIA',		'TXT_KEY_EA_RELIGION_CULT_OF_BAKKHEIA_PEDIA',		'TXT_KEY_EA_RELIGION_CULT_OF_BAKKHEIA_STRATEGY',	'BUILDING_CULT_OF_BAKKHEIA_FOLLOWER',	'EA_SPELL_REVELRY',				'BELIEF_THE_WEAVE_OF_EA_FOLLOWER',		'BELIEF_CULT_OF_BAKKHEIA_FOUNDER',		'BELIEF_CULT_OF_BAKKHEIA_FOLLOWER',		'EA_RELIGION_ATLAS',	4,				'[ICON_CULT_OF_BAKKHEIA]'			;


CREATE TABLE Religions_BeliefsInReligion (	'ReligionType' TEXT DEFAULT NULL,			--This is used only for Religions UI
											'BeliefType' TEXT DEFAULT NULL);

INSERT INTO Religions_BeliefsInReligion (ReligionType,	BeliefType)
SELECT 'RELIGION_AZZANDARAYASNA',			'BELIEF_AZZANDARAYASNA_FOUNDER'			UNION ALL
SELECT 'RELIGION_AZZANDARAYASNA',			'BELIEF_AZZANDARAYASNA_FOLLOWER'		UNION ALL
SELECT 'RELIGION_AZZANDARAYASNA',			'BELIEF_WAY_OF_THE_WISE'				UNION ALL
SELECT 'RELIGION_AZZANDARAYASNA',			'BELIEF_HEAVENS_MANDATE'				UNION ALL
SELECT 'RELIGION_AZZANDARAYASNA',			'BELIEF_PRIESTHOOD'						UNION ALL
SELECT 'RELIGION_AZZANDARAYASNA',			'BELIEF_HOLY_ORDER'						UNION ALL
SELECT 'RELIGION_AZZANDARAYASNA',			'BELIEF_THEOCRACY'						UNION ALL
SELECT 'RELIGION_ANRA',						'BELIEF_ANRA_FOUNDER'					UNION ALL
SELECT 'RELIGION_ANRA',						'BELIEF_ANRA_FOLLOWER'					UNION ALL
SELECT 'RELIGION_ANRA',						'BELIEF_ANTI_WAY_OF_THE_WISE'			UNION ALL
SELECT 'RELIGION_ANRA',						'BELIEF_ANTI_HEAVENS_MANDATE'			UNION ALL
SELECT 'RELIGION_ANRA',						'BELIEF_ANTI_PRIESTHOOD'				UNION ALL
SELECT 'RELIGION_ANRA',						'BELIEF_ANTI_HOLY_ORDER'				UNION ALL
SELECT 'RELIGION_ANRA',						'BELIEF_ANTI_THEOCRACY'					UNION ALL
SELECT 'RELIGION_THE_WEAVE_OF_EA',			'BELIEF_THE_WEAVE_OF_EA_FOLLOWER'		UNION ALL
SELECT 'RELIGION_CULT_OF_LEAVES',			'BELIEF_CULT_OF_LEAVES_FOUNDER'			UNION ALL
SELECT 'RELIGION_CULT_OF_LEAVES',			'BELIEF_THE_WEAVE_OF_EA_FOLLOWER'		UNION ALL
SELECT 'RELIGION_CULT_OF_LEAVES',			'BELIEF_CULT_OF_LEAVES_FOLLOWER'		UNION ALL
SELECT 'RELIGION_CULT_OF_EPONA',			'BELIEF_CULT_OF_EPONA_FOUNDER'			UNION ALL
SELECT 'RELIGION_CULT_OF_EPONA',			'BELIEF_THE_WEAVE_OF_EA_FOLLOWER'		UNION ALL
SELECT 'RELIGION_CULT_OF_EPONA',			'BELIEF_CULT_OF_EPONA_FOLLOWER'			UNION ALL
SELECT 'RELIGION_CULT_OF_PURE_WATERS',		'BELIEF_CULT_OF_PURE_WATERS_FOUNDER'	UNION ALL
SELECT 'RELIGION_CULT_OF_PURE_WATERS',		'BELIEF_THE_WEAVE_OF_EA_FOLLOWER'		UNION ALL
SELECT 'RELIGION_CULT_OF_PURE_WATERS',		'BELIEF_CULT_OF_PURE_WATERS_FOLLOWER'	UNION ALL
SELECT 'RELIGION_CULT_OF_AEGIR',			'BELIEF_CULT_OF_AEGIR_FOUNDER'			UNION ALL
SELECT 'RELIGION_CULT_OF_AEGIR',			'BELIEF_THE_WEAVE_OF_EA_FOLLOWER'		UNION ALL
SELECT 'RELIGION_CULT_OF_AEGIR',			'BELIEF_CULT_OF_AEGIR_FOLLOWER'			UNION ALL
SELECT 'RELIGION_CULT_OF_BAKKHEIA',			'BELIEF_CULT_OF_BAKKHEIA_FOUNDER'		UNION ALL
SELECT 'RELIGION_CULT_OF_BAKKHEIA',			'BELIEF_THE_WEAVE_OF_EA_FOLLOWER'		UNION ALL
SELECT 'RELIGION_CULT_OF_BAKKHEIA',			'BELIEF_CULT_OF_BAKKHEIA_FOLLOWER'		;


ALTER TABLE Beliefs ADD COLUMN 'EaPolicyTrigger' TEXT DEFAULT NULL;

DELETE FROM Beliefs;
INSERT INTO Beliefs (Type,						Description,										ShortDescription,										EaPolicyTrigger,				Founder,	Follower,	Enhancer)
SELECT 'BELIEF_FAKE_PANTHEON',					'TXT_KEY_EA_BELIEF_FAKE_PANTHEON',					'TXT_KEY_EA_BELIEF_FAKE_PANTHEON_SHORT',				NULL,							0,			0,			0		UNION ALL
SELECT 'BELIEF_AZZANDARAYASNA_FOUNDER',			'TXT_KEY_EA_BELIEF_AZZANDARAYASNA_FOUNDER',			'TXT_KEY_EA_BELIEF_AZZANDARAYASNA_FOUNDER_SHORT',		NULL,							1,			0,			0		UNION ALL
SELECT 'BELIEF_AZZANDARAYASNA_FOLLOWER',		'TXT_KEY_EA_BELIEF_AZZANDARAYASNA_FOLLOWER',		'TXT_KEY_EA_BELIEF_AZZANDARAYASNA_FOLLOWER_SHORT',		NULL,							0,			1,			0		UNION ALL
SELECT 'BELIEF_WAY_OF_THE_WISE',				'TXT_KEY_EA_BELIEF_WAY_OF_THE_WISE',				'TXT_KEY_EA_BELIEF_WAY_OF_THE_WISE_SHORT',				'POLICY_WAY_OF_THE_WISE',		0,			0,			1		UNION ALL
SELECT 'BELIEF_HEAVENS_MANDATE',				'TXT_KEY_EA_BELIEF_HEAVENS_MANDATE',				'TXT_KEY_EA_BELIEF_HEAVENS_MANDATE_SHORT',				'POLICY_HEAVENS_MANDATE',		1,			0,			0		UNION ALL
SELECT 'BELIEF_PRIESTHOOD',						'TXT_KEY_EA_BELIEF_PRIESTHOOD',						'TXT_KEY_EA_BELIEF_PRIESTHOOD_SHORT',					'POLICY_PRIESTHOOD',			0,			0,			1		UNION ALL
SELECT 'BELIEF_HOLY_ORDER',						'TXT_KEY_EA_BELIEF_HOLY_ORDER',						'TXT_KEY_EA_BELIEF_HOLY_ORDER_SHORT',					'POLICY_HOLY_ORDER',			0,			0,			1		UNION ALL
SELECT 'BELIEF_THEOCRACY',						'TXT_KEY_EA_BELIEF_THEOCRACY',						'TXT_KEY_EA_BELIEF_THEOCRACY_SHORT',					'POLICY_THEOCRACY',				1,			0,			0		UNION ALL
SELECT 'BELIEF_ANRA_FOUNDER',					'TXT_KEY_EA_BELIEF_ANRA_FOUNDER',					'TXT_KEY_EA_BELIEF_ANRA_FOUNDER_SHORT',					NULL,							1,			0,			0		UNION ALL
SELECT 'BELIEF_ANRA_FOLLOWER',					'TXT_KEY_EA_BELIEF_ANRA_FOLLOWER',					'TXT_KEY_EA_BELIEF_ANRA_FOLLOWER_SHORT',				NULL,							0,			1,			0		UNION ALL
SELECT 'BELIEF_ANTI_WAY_OF_THE_WISE',			'TXT_KEY_EA_BELIEF_ANTI_WAY_OF_THE_WISE',			'TXT_KEY_EA_BELIEF_ANTI_WAY_OF_THE_WISE_SHORT',			'POLICY_ANTI_WAY_OF_THE_WISE',	0,			0,			1		UNION ALL
SELECT 'BELIEF_ANTI_HEAVENS_MANDATE',			'TXT_KEY_EA_BELIEF_ANTI_HEAVENS_MANDATE',			'TXT_KEY_EA_BELIEF_ANTI_HEAVENS_MANDATE_SHORT',			'POLICY_ANTI_HEAVENS_MANDATE',	1,			0,			0		UNION ALL
SELECT 'BELIEF_ANTI_PRIESTHOOD',				'TXT_KEY_EA_BELIEF_ANTI_PRIESTHOOD',				'TXT_KEY_EA_BELIEF_ANTI_PRIESTHOOD_SHORT',				'POLICY_ANTI_PRIESTHOOD',		0,			0,			1		UNION ALL
SELECT 'BELIEF_ANTI_HOLY_ORDER',				'TXT_KEY_EA_BELIEF_ANTI_HOLY_ORDER',				'TXT_KEY_EA_BELIEF_ANTI_HOLY_ORDER_SHORT',				'POLICY_ANTI_HOLY_ORDER',		0,			0,			1		UNION ALL
SELECT 'BELIEF_ANTI_THEOCRACY',					'TXT_KEY_EA_BELIEF_ANTI_THEOCRACY',					'TXT_KEY_EA_BELIEF_ANTI_THEOCRACY_SHORT',				'POLICY_ANTI_THEOCRACY',		1,			0,			0		UNION ALL
SELECT 'BELIEF_CULT_OF_LEAVES_FOUNDER',			'TXT_KEY_EA_BELIEF_CULT_OF_LEAVES_FOUNDER',			'TXT_KEY_EA_BELIEF_CULT_OF_LEAVES_FOUNDER_SHORT',		NULL,							1,			0,			0		UNION ALL
SELECT 'BELIEF_CULT_OF_EPONA_FOUNDER',			'TXT_KEY_EA_BELIEF_CULT_OF_EPONA_FOUNDER',			'TXT_KEY_EA_BELIEF_CULT_OF_EPONA_FOUNDER_SHORT',		NULL,							1,			0,			0		UNION ALL
SELECT 'BELIEF_CULT_OF_PURE_WATERS_FOUNDER',	'TXT_KEY_EA_BELIEF_CULT_OF_PURE_WATERS_FOUNDER',	'TXT_KEY_EA_BELIEF_CULT_OF_PURE_WATERS_FOUNDER_SHORT',	NULL,							1,			0,			0		UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOUNDER',			'TXT_KEY_EA_BELIEF_CULT_OF_AEGIR_FOUNDER',			'TXT_KEY_EA_BELIEF_CULT_OF_AEGIR_FOUNDER_SHORT',		NULL,							1,			0,			0		UNION ALL
SELECT 'BELIEF_CULT_OF_BAKKHEIA_FOUNDER',		'TXT_KEY_EA_BELIEF_CULT_OF_BAKKHEIA_FOUNDER',		'TXT_KEY_EA_BELIEF_CULT_OF_BAKKHEIA_FOUNDER_SHORT',		NULL,							1,			0,			0		UNION ALL
SELECT 'BELIEF_THE_WEAVE_OF_EA_FOLLOWER',		'TXT_KEY_EA_BELIEF_THE_WEAVE_OF_EA_FOLLOWER',		'TXT_KEY_EA_BELIEF_THE_WEAVE_OF_EA_FOLLOWER_SHORT',		NULL,							0,			1,			0		UNION ALL
SELECT 'BELIEF_CULT_OF_LEAVES_FOLLOWER',		'TXT_KEY_EA_BELIEF_CULT_OF_LEAVES_FOLLOWER',		'TXT_KEY_EA_BELIEF_CULT_OF_LEAVES_FOLLOWER_SHORT',		NULL,							0,			1,			0		UNION ALL
SELECT 'BELIEF_CULT_OF_EPONA_FOLLOWER',			'TXT_KEY_EA_BELIEF_CULT_OF_EPONA_FOLLOWER',			'TXT_KEY_EA_BELIEF_CULT_OF_EPONA_FOLLOWER_SHORT',		NULL,							0,			1,			0		UNION ALL
SELECT 'BELIEF_CULT_OF_PURE_WATERS_FOLLOWER',	'TXT_KEY_EA_BELIEF_CULT_OF_PURE_WATERS_FOLLOWER',	'TXT_KEY_EA_BELIEF_CULT_OF_PURE_WATERS_FOLLOWER_SHORT',	NULL,							0,			1,			0		UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',			'TXT_KEY_EA_BELIEF_CULT_OF_AEGIR_FOLLOWER',			'TXT_KEY_EA_BELIEF_CULT_OF_AEGIR_FOLLOWER_SHORT',		NULL,							0,			1,			0		UNION ALL
SELECT 'BELIEF_CULT_OF_BAKKHEIA_FOLLOWER',		'TXT_KEY_EA_BELIEF_CULT_OF_BAKKHEIA_FOLLOWER',		'TXT_KEY_EA_BELIEF_CULT_OF_BAKKHEIA_FOLLOWER_SHORT',	NULL,							0,			1,			0		;

UPDATE Beliefs SET Pantheon = 1 WHERE Type = 'BELIEF_FAKE_PANTHEON';		--always id=0
UPDATE Beliefs SET GoldPerFollowingCity = 1 WHERE Type = 'BELIEF_AZZANDARAYASNA_FOUNDER';
UPDATE Beliefs SET SpreadStrengthModifier = 33 WHERE Type = 'BELIEF_PRIESTHOOD';
UPDATE Beliefs SET FriendlyHealChange = 30 WHERE Type = 'BELIEF_WAY_OF_THE_WISE';
UPDATE Beliefs SET CombatModifierFriendlyCities = 30 WHERE Type = 'BELIEF_HOLY_ORDER';
UPDATE Beliefs SET GoldPerFollowingCity = 2 WHERE Type = 'BELIEF_THEOCRACY';
UPDATE Beliefs SET CityGrowthModifier = -15 WHERE Type = 'BELIEF_ANRA_FOLLOWER';
UPDATE Beliefs SET SpreadDistanceModifier = 50 WHERE Type = 'BELIEF_ANTI_PRIESTHOOD';
UPDATE Beliefs SET FaithFromKills = 50 WHERE Type = 'BELIEF_ANTI_WAY_OF_THE_WISE';
UPDATE Beliefs SET CombatModifierEnemyCities = 40 WHERE Type = 'BELIEF_ANTI_HOLY_ORDER';
UPDATE Beliefs SET RiverHappiness = 2 WHERE Type = 'BELIEF_CULT_OF_PURE_WATERS_FOLLOWER';



DELETE FROM Belief_CityYieldChanges;
DELETE FROM Belief_HolyCityYieldChanges;
DELETE FROM Belief_ResourceQuantityModifiers;
DELETE FROM Belief_ResourceHappiness;		--not used in base; works?
DELETE FROM Belief_TerrainYieldChanges;
DELETE FROM Belief_YieldChangeAnySpecialist;
DELETE FROM Belief_YieldChangeTradeRoute;
DELETE FROM Belief_YieldChangeNaturalWonder;
DELETE FROM Belief_YieldChangeWorldWonder;
DELETE FROM Belief_YieldModifierNaturalWonder;

DELETE FROM Belief_BuildingClassHappiness;
INSERT INTO Belief_BuildingClassHappiness(BeliefType, BuildingClassType, Happiness)
SELECT 'BELIEF_CULT_OF_EPONA_FOLLOWER',		'BUILDINGCLASS_STABLE',		2	UNION ALL
SELECT 'BELIEF_CULT_OF_BAKKHEIA_FOLLOWER',	'BUILDINGCLASS_WINERY',		2	UNION ALL
SELECT 'BELIEF_CULT_OF_BAKKHEIA_FOLLOWER',	'BUILDINGCLASS_BREWERY',	2	UNION ALL
SELECT 'BELIEF_CULT_OF_BAKKHEIA_FOLLOWER',	'BUILDINGCLASS_DISTILLERY',	2	;

DELETE FROM Belief_BuildingClassYieldChanges;
INSERT INTO Belief_BuildingClassYieldChanges(BeliefType, BuildingClassType, YieldType, YieldChange)
SELECT 'BELIEF_CULT_OF_BAKKHEIA_FOLLOWER',	'BUILDINGCLASS_WINERY',		'YIELD_CULTURE',	2	UNION ALL
SELECT 'BELIEF_CULT_OF_BAKKHEIA_FOLLOWER',	'BUILDINGCLASS_BREWERY',	'YIELD_CULTURE',	2	UNION ALL
SELECT 'BELIEF_CULT_OF_BAKKHEIA_FOLLOWER',	'BUILDINGCLASS_DISTILLERY',	'YIELD_CULTURE',	2	;


DELETE FROM Belief_FeatureYieldChanges;
INSERT INTO Belief_FeatureYieldChanges(BeliefType, FeatureType, YieldType, Yield)
SELECT 'BELIEF_THE_WEAVE_OF_EA_FOLLOWER', 'FEATURE_FOREST', 'YIELD_FOOD', 1 UNION ALL
SELECT 'BELIEF_THE_WEAVE_OF_EA_FOLLOWER', 'FEATURE_JUNGLE', 'YIELD_FOOD', 1 UNION ALL
SELECT 'BELIEF_THE_WEAVE_OF_EA_FOLLOWER', 'FEATURE_MARSH', 'YIELD_FOOD', 1 UNION ALL
SELECT 'BELIEF_CULT_OF_PURE_WATERS_FOLLOWER', 'FEATURE_OASIS', 'YIELD_FOOD', 2 ;		--Does not work

DELETE FROM Belief_MaxYieldModifierPerFollower;
INSERT INTO Belief_MaxYieldModifierPerFollower(BeliefType, YieldType, Max)
SELECT 'BELIEF_AZZANDARAYASNA_FOLLOWER',	'YIELD_CULTURE',	35	UNION ALL
SELECT 'BELIEF_ANRA_FOLLOWER',				'YIELD_SCIENCE',	80	;

DELETE FROM Belief_YieldChangePerForeignCity;
INSERT INTO Belief_YieldChangePerForeignCity(BeliefType, YieldType, Yield)
SELECT 'BELIEF_AZZANDARAYASNA_FOUNDER',	'YIELD_FAITH',		1	UNION ALL
SELECT 'BELIEF_HEAVENS_MANDATE',		'YIELD_FAITH',		2	;

DELETE FROM Belief_YieldChangePerXForeignFollowers;
INSERT INTO Belief_YieldChangePerXForeignFollowers(BeliefType, YieldType, ForeignFollowers)
SELECT 'BELIEF_ANRA_FOUNDER',			'YIELD_SCIENCE',	2	UNION ALL
SELECT 'BELIEF_ANRA_FOUNDER',			'YIELD_FAITH',		2	UNION ALL
SELECT 'BELIEF_ANTI_HEAVENS_MANDATE',	'YIELD_FAITH',		1	UNION ALL
SELECT 'BELIEF_ANTI_THEOCRACY',			'YIELD_SCIENCE',	1	;



DELETE FROM Belief_ImprovementYieldChanges;
--INSERT INTO Belief_ImprovementYieldChanges(BeliefType, ImprovementType, YieldType, Yield)

DELETE FROM Belief_ResourceYieldChanges;
INSERT INTO Belief_ResourceYieldChanges(BeliefType, ResourceType, YieldType, Yield)
SELECT 'BELIEF_CULT_OF_EPONA_FOLLOWER',		'RESOURCE_HORSE',	'YIELD_CULTURE',	2	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_FISH',	'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_FISH',	'YIELD_GOLD',		1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_FISH',	'YIELD_CULTURE',	1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_CRAB',	'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_CRAB',	'YIELD_GOLD',		1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_CRAB',	'YIELD_CULTURE',	1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_PEARLS',	'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_PEARLS',	'YIELD_GOLD',		1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_PEARLS',	'YIELD_CULTURE',	1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_WHALE',	'YIELD_PRODUCTION',	1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_WHALE',	'YIELD_GOLD',		1	UNION ALL
SELECT 'BELIEF_CULT_OF_AEGIR_FOLLOWER',		'RESOURCE_WHALE',	'YIELD_CULTURE',	1	UNION ALL
SELECT 'BELIEF_CULT_OF_BAKKHEIA_FOLLOWER',	'RESOURCE_WINE',	'YIELD_CULTURE',	2	;




-- fixinator
CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM Religions ORDER BY ID;
UPDATE Religions SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Religions.Type = IDRemapper.Type);
DROP TABLE IDRemapper;
CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM Beliefs ORDER BY ID;
UPDATE Beliefs SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Beliefs.Type = IDRemapper.Type);
DROP TABLE IDRemapper;


INSERT INTO EaDebugTableCheck(FileName) SELECT 'Religions.sql';