DELETE FROM Technologies;
ALTER TABLE Technologies ADD COLUMN 'Utility' BOOLEAN DEFAULT NULL;
ALTER TABLE Technologies ADD COLUMN 'EaTechClass' BOOLEAN DEFAULT NULL;
--ALTER TABLE Technologies ADD COLUMN 'EaLandTradeRoutesChange' INTEGER DEFAULT 0;	--Not implemented (maybe never will be)
--ALTER TABLE Technologies ADD COLUMN 'EaSeaTradeRoutesChange' INTEGER DEFAULT 0;

-- Tier 1
INSERT INTO Technologies (GridX, GridY, Type, Cost, EaTechClass, Quote,					PortraitIndex,	IconAtlas		) VALUES
(0, 0, 'TECH_DOMESTICATION',			50,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	2,	'TECH_ATLAS_1'				),
(0, 2, 'TECH_HUNTING',					50,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_2'				),
(0, 5, 'TECH_FISHING',					50,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(0, 9, 'TECH_AGRICULTURE',				50,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	0,	'TECH_ATLAS_1'				),
(0,17, 'TECH_WRITING',					50,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	8,	'TECH_ATLAS_1'				),
(0,22, 'TECH_CURRENCY',					50,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	2,	'EXPANSION_TECH_ATLAS_1'	),
(0,24, 'TECH_MINING',					50,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	1,	'TECH_ATLAS_1'				),
-- Tier 2
(1,-1, 'TECH_HORSEBACK_RIDING',			75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	11,	'TECH_ATLAS_1'				),
(1, 0, 'TECH_ANIMAL_HUSBANDRY',			75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	2,	'TECH_ATLAS_1'				),
(1, 1, 'TECH_ELEPHANT_LABOR',			75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(1, 2, 'TECH_TRACKING_TRAPPING',		75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_2'				),
(1, 3, 'TECH_ARCHERY',					75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	7,	'TECH_ATLAS_1'				),
(1, 4, 'TECH_HARPOONS',					75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(1, 5, 'TECH_SAILING',					75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(1, 6, 'TECH_MILLING',					75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(1, 7, 'TECH_WEAVING',					75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(1, 8, 'TECH_ZYMURGY',					75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	4,	'TECH_ATLAS_1'				),
(1, 9, 'TECH_IRRIGATION',				75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(1,10, 'TECH_CALENDAR',					75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	9,	'TECH_ATLAS_1'				),
(1,11, 'TECH_DIVINE_LITURGY',			75,		'Divine',		'TXT_KEY_EA_BLANK_SPACE',	21,	'TECH_ATLAS_1'				),
(1,13, 'TECH_MALEFICIUM',				75,		'ArcaneEvil',	'TXT_KEY_EA_BLANK_SPACE',	9,	'TECH_ATLAS_2'				),
(1,15, 'TECH_THAUMATURGY',				75,		'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	8,	'TECH_ATLAS_2'				),
(1,17, 'TECH_PHILOSOPHY',				75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	16,	'TECH_ATLAS_1'				),
(1,18, 'TECH_DRAMA',					75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	4,	'EXPANSION_TECH_ATLAS_1'	),
(1,20, 'TECH_MATHEMATICS',				75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	12,	'TECH_ATLAS_1'				),
(1,22, 'TECH_COINAGE',					75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	17,	'TECH_ATLAS_1'				),	--less good: 2,	'EXPANSION_TECH_ATLAS_1'
(1,23, 'TECH_MASONRY',					75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	6,	'TECH_ATLAS_1'				),
(1,24, 'TECH_BRONZE_WORKING',			75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	5,	'TECH_ATLAS_1'				),
(1,25, 'TECH_DEEP_MINING',				75,		NULL,			'TXT_KEY_EA_BLANK_SPACE',	1,	'TECH_ATLAS_1'				),
-- Tier 3
(2,-1, 'TECH_STIRRUPS',					250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	11,	'TECH_ATLAS_1'				),
(2, 0, 'TECH_ANIMAL_INDUSTRY',			250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	2,	'TECH_ATLAS_1'				),
(2, 1, 'TECH_ELEPHANT_TRAINING',		250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(2, 2, 'TECH_GAMEKEEPING',				250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_2'				),
(2, 3, 'TECH_BOWYERS',					250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	7,	'TECH_ATLAS_1'				),
(2, 5, 'TECH_SHIP_BUILDING',			250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(2, 6, 'TECH_FORESTRY',					250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(2, 7, 'TECH_FINE_TEXTILES',			250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(2, 8, 'TECH_OENOLOGY',					250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	4,	'TECH_ATLAS_1'				),
(2, 9, 'TECH_CROP_ROTATION',			250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(2,10, 'TECH_ASTRONOMY',				250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	34,	'TECH_ATLAS_1'				),
(2,11, 'TECH_DIVINE_VITALISM',			250,	'Divine',		'TXT_KEY_EA_BLANK_SPACE',	21,	'TECH_ATLAS_1'				),
(2,12, 'TECH_LYCANTHROPY',				250,	'ArcaneEvil',	'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(2,13, 'TECH_REANIMATION',				250,	'ArcaneEvil',	'TXT_KEY_EA_BLANK_SPACE',	10,	'TECH_ATLAS_2'				),
(2,14, 'TECH_SORCERY',					250,	'ArcaneEvil',	'TXT_KEY_EA_BLANK_SPACE',	9,	'TECH_ATLAS_2'				),
(2,15, 'TECH_CONJURATION',				250,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	8,	'TECH_ATLAS_2'				),
(2,16, 'TECH_TRANSMUTATION',			250,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	8,	'TECH_ATLAS_2'				),
(2,17, 'TECH_LOGIC',					250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	25,	'TECH_ATLAS_1'				),
(2,18, 'TECH_LITERATURE',				250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(2,19, 'TECH_MUSIC',					250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	14,	'TECH_ATLAS_2'				),
(2,20, 'TECH_ALCHEMY',					250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	37,	'TECH_ATLAS_1'				),
(2,21, 'TECH_MECHANICS',				250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	24,	'TECH_ATLAS_1'				),
(2,22, 'TECH_BANKING',					250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	31,	'TECH_ATLAS_1'				),
(2,23, 'TECH_CONSTRUCTION',				250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	15,	'TECH_ATLAS_1'				),
(2,24, 'TECH_IRON_WORKING',				250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	10,	'TECH_ATLAS_1'				),
(2,25, 'TECH_EARTH_DIVINATION',			250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(2,26, 'TECH_UNDERDARK_PATHS',			250,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	1,	'TECH_ATLAS_1'				),
-- Tier 4
(3, 0, 'TECH_ANIMAL_BREEDING',			900,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	2,	'TECH_ATLAS_1'				),
(3, 2, 'TECH_ANIMAL_MASTERY',			900,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_2'				),
(3, 3, 'TECH_MARKSMANSHIP',				900,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	7,	'TECH_ATLAS_1'				),
(3, 5, 'TECH_NAVIGATION',				900,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	23,	'TECH_ATLAS_1'				),
(3,10, 'TECH_HEAVENLY_CYCLES',			900,	'Divine',		'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(3,11, 'TECH_DIVINE_ESSENCE',			900,	'Divine',		'TXT_KEY_EA_BLANK_SPACE',	21,	'TECH_ATLAS_1'				),
(3,12, 'TECH_VAMPIRISM',				900,	'ArcaneEvil',	'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(3,13, 'TECH_NECROMANCY',				900,	'ArcaneEvil',	'TXT_KEY_EA_BLANK_SPACE',	10,	'TECH_ATLAS_2'				),
(3,14, 'TECH_SUMMONING',				900,	'ArcaneEvil',	'TXT_KEY_EA_BLANK_SPACE',	9,	'TECH_ATLAS_2'				),
(3,15, 'TECH_EVOCATION',				900,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	8,	'TECH_ATLAS_2'				),
(3,16, 'TECH_ABJURATION',				900,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	8,	'TECH_ATLAS_2'				),
(3,17, 'TECH_SEMIOTICS',				900,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(3,18, 'TECH_ILLUSION',					900,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	7,	'TECH_ATLAS_2'				),
(3,19, 'TECH_ENCHANTMENT',				900,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	7,	'TECH_ATLAS_2'				),
(3,20, 'TECH_CHEMISTRY',				900,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	32,	'TECH_ATLAS_1'				),
(3,21, 'TECH_SANITATION',				900,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(3,23, 'TECH_ENGINEERING',				900,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	0,	'SHARED_TECH_ATLAS'			),
(3,24, 'TECH_METAL_CASTING',			900,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	14,	'TECH_ATLAS_1'				),
-- Tier 5
(4,-1, 'TECH_WAR_HORSES',				3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	11,	'TECH_ATLAS_1'				),
(4, 1, 'TECH_WAR_ELEPHANTS',			3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(4, 2, 'TECH_BEAST_MASTERY',			3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(4, 4, 'TECH_WHALING',					3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(4, 5, 'TECH_NAVAL_ENGINEERING',		3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	29,	'TECH_ATLAS_1'				),
(4,10, 'TECH_CELESTIAL_KNOWLEDGE',		3000,	'Divine',		'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(4,13, 'TECH_SOUL_BINDING',				3000,	'ArcaneEvil',	'TXT_KEY_EA_BLANK_SPACE',	10,	'TECH_ATLAS_2'				),
(4,15, 'TECH_INVOCATION',				3000,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	8,	'TECH_ATLAS_2'				),
(4,17, 'TECH_METAPHYSICS',				3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(4,18, 'TECH_GREATER_ILLUSION',			3000,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	7,	'TECH_ATLAS_2'				),
(4,20, 'TECH_AESTHETICS',				3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(4,21, 'TECH_MEDICINE',					3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(4,22, 'TECH_ARCHITECTURE',				3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	0,	'EXPANSION_TECH_ATLAS_1'	),
(4,23, 'TECH_MACHINERY',				3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	19,	'TECH_ATLAS_1'				),	--0, EXPANSION_SCEN_TECH_ATLAS
(4,24, 'TECH_STEEL_WORKING',			3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	28,	'TECH_ATLAS_1'				),
(4,25, 'TECH_ELEMENTAL_FORGING',		3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(4,26, 'TECH_DEEP_ROADS',				3000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	1,	'TECH_ATLAS_1'				),
-- Tier 6
(5, 1, 'TECH_MUMAKIL_RIDING',			9000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(5, 3, 'TECH_SONG_OF_LEVIATHAN',		9000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(5, 5, 'TECH_ADV_NAVAL_ENGINEERING',	9000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	29,	'TECH_ATLAS_1'				),
(5,11, 'TECH_DIVINE_INTERVENTION',		9000,	'Divine',		'TXT_KEY_EA_BLANK_SPACE',	21,	'TECH_ATLAS_1'				),
(5,14, 'TECH_BREACH',					9000,	'ArcaneEvil',	'TXT_KEY_EA_BLANK_SPACE',	9,	'TECH_ATLAS_2'				),
(5,15, 'TECH_GREATER_ARCANA',			9000,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	8,	'TECH_ATLAS_2'				),
(5,17, 'TECH_TRANSCENDENTAL_THOUGHT',	9000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	13,	'TECH_ATLAS_1'				),
(5,19, 'TECH_PHANTASMAGORIA',			9000,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	7,	'TECH_ATLAS_2'				),
(5,21, 'TECH_ETHEREAL_ARCHITECTURE',	9000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	0,	'EXPANSION_TECH_ATLAS_1'	),
(5,23, 'TECH_STEAM_POWER',				9000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	42,	'TECH_ATLAS_1'				),
(5,25, 'TECH_MITHRIL_WORKING',			9000,	NULL,			'TXT_KEY_EA_BLANK_SPACE',	33,	'TECH_ATLAS_1'				),
-- Tier 7
(6,11, 'TECH_KNOWLEDGE_OF_HEAVEN',		54000,	'Divine',		'TXT_KEY_EA_BLANK_SPACE',	27,	'TECH_ATLAS_1'				),
(6,13, 'TECH_ARMAGEDDON_RITUALS',		54000,	'ArcaneEvil',	'TXT_KEY_EA_BLANK_SPACE',	9,	'TECH_ATLAS_2'				),
(6,15, 'TECH_ESOTERIC_ARCANA',			54000,	'Arcane',		'TXT_KEY_EA_BLANK_SPACE',	8,	'TECH_ATLAS_2'				);

--Build out the table for dependent strings
UPDATE Technologies SET Description = 'TXT_KEY_EA_' || Type;
UPDATE Technologies SET Civilopedia = Description || '_PEDIA', Help = Description || '_HELP';


--Temp disable unfinished techs (these are manually commented out in rest of mod)
UPDATE Technologies SET Utility = 1, EaTechClass = NULL WHERE Type IN ('TECH_LYCANTHROPY', 'TECH_VAMPIRISM', 'TECH_ILLUSION', 'TECH_ENCHANTMENT', 'TECH_GREATER_ILLUSION', 'TECH_PHANTASMAGORIA', 'TECH_ETHEREAL_ARCHITECTURE', 'TECH_DEEP_ROADS', 'TECH_SONG_OF_LEVIATHAN');
UPDATE Technologies SET GridY = GridY - 1 WHERE Type = 'TECH_AESTHETICS';


-- Utility techs (all automatically given prereq TECH_NEVER)
INSERT INTO Technologies (Type,		Utility) VALUES
('TECH_NEVER',						1	),
('TECH_ALLOW_POLDER',				1	),
('TECH_GAIN_WITH_NAMING',			1	),	--allows open borders
('TECH_ALLOW_TIMBER_TRADE',			1	),	--allows Timber trade and Timberyard
('TECH_ALLOW_HORSE_TRADE',			1	),	--all can trade except Heldeofol
('TECH_MOLY_VISIBLE',				1	),	--Moly visible, tradeable and improveable
('TECH_ALLOW_MANA_YIELDS',			1	),
('TECH_ALLOW_DIVINE_FAVOR_YIELDS',	1	),
('TECH_ALLOW_ALL_WATER_PASSAGE',	1	);




UPDATE Technologies SET GridX = 9, GridY = 36, Cost = -1, Description = 'TXT_KEY_EA_NOTSHOWN', Civilopedia = 'TXT_KEY_EA_NOTSHOWN', Help = 'TXT_KEY_EA_NOTSHOWN', PortraitIndex = 13, IconAtlas = 'TECH_ATLAS_1' WHERE Utility = 1;

UPDATE Technologies SET Trade='TRUE', GoodyTech='FALSE', Era='ERA_ANCIENT';		--Is NULL for quote OK?
UPDATE Technologies SET InternationalTradeRoutesChange = 1 WHERE Type IN ('TECH_CURRENCY', 'TECH_SAILING', 'TECH_COINAGE', 'TECH_SHIP_BUILDING', 'TECH_BANKING', 'TECH_CONSTRUCTION', 'TECH_NAVIGATION', 'TECH_ENGINEERING', 'TECH_NAVAL_ENGINEERING', 'TECH_ADV_NAVAL_ENGINEERING', 'TECH_STEAM_POWER');
UPDATE Technologies SET GoldTrading = 1 WHERE Type = 'TECH_COINAGE';		--TO DO: trade route techs


UPDATE Technologies SET BridgeBuilding=1 WHERE Type='TECH_ENGINEERING';
UPDATE Technologies SET AllowEmbassyTradingAllowed = 1, OpenBordersTradingAllowed = 1 WHERE Type='TECH_GAIN_WITH_NAMING';
UPDATE Technologies SET WaterWork = 1 WHERE Type = 'TECH_FISHING';
UPDATE Technologies SET AllowsEmbarking = 1 WHERE Type = 'TECH_SAILING';
UPDATE Technologies SET EmbarkedAllWaterPassage = 1 WHERE Type IN ('TECH_ASTRONOMY', 'TECH_ALLOW_ALL_WATER_PASSAGE');
UPDATE Technologies SET UnitBaseHealModifier = 5 WHERE Type = 'TECH_MEDICINE';



--UPDATE Technologies SET MapCentering = 1 WHERE Type = 'TECH_GAIN_WITH_NAMING';

-- Fixinator
CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM Technologies ORDER BY ID;
UPDATE Technologies SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Technologies.Type = IDRemapper.Type);
DROP TABLE IDRemapper;

--------------------------------------------------------------
-- Subtables
--------------------------------------------------------------

CREATE TABLE Technology_EaTechButtonIncludeSpecials (	TechType TEXT NOT NULL,
														SpecialText TEXT NOT NULL,
														IconAtlas TEXT DEFAULT NULL,	--uses star if NULL
														IconIndex INTEGER DEFAULT 0);

INSERT INTO Technology_EaTechButtonIncludeSpecials (TechType, SpecialText) VALUES
('TECH_TRACKING_TRAPPING',	'TXT_KEY_EA_TECH_TRACKING_TRAPPING_SPECIAL'	),
('TECH_SAILING',			'TXT_KEY_EA_TECH_SAILING_SPECIAL'			),
('TECH_MALEFICIUM',			'TXT_KEY_EA_TECH_MALEFICIUM_SPECIAL'		),
('TECH_REANIMATION',		'TXT_KEY_EA_TECH_VA_SPECIAL'				),
('TECH_SORCERY',			'TXT_KEY_EA_TECH_VA_SPECIAL'				),
('TECH_SHIP_BUILDING',		'TXT_KEY_EA_TECH_SHIP_BUILDING_SPECIAL'		),
('TECH_FORESTRY',			'TXT_KEY_EA_TECH_FORESTRY_SPECIAL1'			),
('TECH_FORESTRY',			'TXT_KEY_EA_TECH_FORESTRY_SPECIAL2'			),
('TECH_ASTRONOMY',			'TXT_KEY_EA_TECH_ASTRONOMY_SPECIAL'			),
('TECH_CHEMISTRY',			'TXT_KEY_EA_TECH_CHEMISTRY_SPECIAL'			),
('TECH_MEDICINE',			'TXT_KEY_EA_TECH_MEDICINE_SPECIAL'			),
('TECH_BEAST_MASTERY',		'TXT_KEY_EA_TECH_BEAST_MASTERY_SPECIAL'		),
('TECH_WHALING',			'TXT_KEY_EA_TECH_WHALING_SPECIAL'			),
('TECH_NAVIGATION',			'TXT_KEY_EA_TECH_NAVIGATION_SPECIAL'		),
('TECH_ANIMAL_MASTERY',		'TXT_KEY_EA_TECH_ANIMAL_MASTERY_SPECIAL'	),
('TECH_STEEL_WORKING',		'TXT_KEY_EA_TECH_STEEL_WORKING_SPECIAL'		),
('TECH_MITHRIL_WORKING',	'TXT_KEY_EA_TECH_MITHRIL_WORKING_SPECIAL'	),

('TECH_KNOWLEDGE_OF_HEAVEN','TXT_KEY_EA_TECH_KNOWLEDGE_OF_HEAVEN_SPECIAL_1'	),
('TECH_KNOWLEDGE_OF_HEAVEN','TXT_KEY_EA_TECH_KNOWLEDGE_OF_HEAVEN_SPECIAL_2'	),
('TECH_ARMAGEDDON_RITUALS',	'TXT_KEY_EA_TECH_ARMAGEDDON_RITUALS_SPECIAL_1'	),
('TECH_ARMAGEDDON_RITUALS',	'TXT_KEY_EA_TECH_ARMAGEDDON_RITUALS_SPECIAL_2'	),
('TECH_ARMAGEDDON_RITUALS',	'TXT_KEY_EA_TECH_ARMAGEDDON_RITUALS_SPECIAL_3'	),
('TECH_ESOTERIC_ARCANA',	'TXT_KEY_EA_TECH_ESOTERIC_ARCANA_SPECIAL'		);


INSERT INTO Technology_EaTechButtonIncludeSpecials (TechType, SpecialText,	IconAtlas,			IconIndex	) VALUES
('TECH_ELEPHANT_TRAINING',	'TXT_KEY_EA_TECH_ELEPHANT_TRAINING_SPECIAL',	'RESOURCE_ATLAS',	15			),
('TECH_ALCHEMY',			'TXT_KEY_EA_TECH_ALCHEMY_SPECIAL',				'RESOURCE_ATLAS',	5			);


DELETE FROM Technology_Flavors;				--not needed: mod controls all tech choices
DELETE FROM Technology_ORPrereqTechs;		--not used in base
DELETE FROM Technology_DomainExtraMoves;	--not used in base
DELETE FROM Technology_FreePromotions;		--Works if promo added to UnitPromotions_UnitCombats!


DELETE FROM Technology_PrereqTechs;
INSERT INTO Technology_PrereqTechs (PrereqTech, TechType) VALUES	--flipped for easy reading
--tier 2 req
('TECH_DOMESTICATION', 'TECH_HORSEBACK_RIDING' ),
('TECH_DOMESTICATION', 'TECH_ANIMAL_HUSBANDRY' ),
('TECH_DOMESTICATION', 'TECH_ELEPHANT_LABOR' ),
('TECH_HUNTING', 'TECH_ELEPHANT_LABOR' ),
('TECH_HUNTING', 'TECH_TRACKING_TRAPPING' ),
('TECH_HUNTING', 'TECH_ARCHERY' ),
('TECH_HUNTING', 'TECH_HARPOONS' ),
('TECH_FISHING', 'TECH_HARPOONS' ),
('TECH_FISHING', 'TECH_SAILING' ),
('TECH_AGRICULTURE', 'TECH_MILLING' ),
('TECH_AGRICULTURE', 'TECH_WEAVING' ),
('TECH_AGRICULTURE', 'TECH_ZYMURGY' ),
('TECH_AGRICULTURE', 'TECH_IRRIGATION' ),
('TECH_AGRICULTURE', 'TECH_CALENDAR' ),
('TECH_WRITING', 'TECH_CALENDAR' ),
('TECH_WRITING', 'TECH_DIVINE_LITURGY' ),
('TECH_WRITING', 'TECH_MALEFICIUM' ),
('TECH_WRITING', 'TECH_THAUMATURGY' ),
('TECH_WRITING', 'TECH_PHILOSOPHY' ),
('TECH_WRITING', 'TECH_DRAMA' ),
('TECH_WRITING', 'TECH_MATHEMATICS' ),
('TECH_CURRENCY', 'TECH_MATHEMATICS' ),
('TECH_CURRENCY', 'TECH_COINAGE' ),
('TECH_MINING', 'TECH_COINAGE' ),
('TECH_MINING', 'TECH_MASONRY' ),
('TECH_MINING', 'TECH_BRONZE_WORKING' ),
('TECH_MINING', 'TECH_DEEP_MINING' ),
--tier 3 req
('TECH_HORSEBACK_RIDING', 'TECH_STIRRUPS' ),
('TECH_ANIMAL_HUSBANDRY', 'TECH_ANIMAL_INDUSTRY' ),
('TECH_ELEPHANT_LABOR', 'TECH_ELEPHANT_TRAINING' ),
('TECH_TRACKING_TRAPPING', 'TECH_GAMEKEEPING' ),
('TECH_ARCHERY', 'TECH_BOWYERS' ),
('TECH_SAILING', 'TECH_SHIP_BUILDING' ),
('TECH_MILLING', 'TECH_SHIP_BUILDING' ),
('TECH_MILLING', 'TECH_FORESTRY' ),
('TECH_WEAVING', 'TECH_FINE_TEXTILES' ),
('TECH_ZYMURGY', 'TECH_OENOLOGY' ),
('TECH_IRRIGATION', 'TECH_CROP_ROTATION' ),
('TECH_CALENDAR', 'TECH_CROP_ROTATION' ),
('TECH_CALENDAR', 'TECH_ASTRONOMY' ),
('TECH_DIVINE_LITURGY', 'TECH_DIVINE_VITALISM' ),
--('TECH_MALEFICIUM', 'TECH_LYCANTHROPY' ),
('TECH_MALEFICIUM', 'TECH_REANIMATION' ),
('TECH_MALEFICIUM', 'TECH_SORCERY' ),
('TECH_THAUMATURGY', 'TECH_SORCERY' ),
('TECH_THAUMATURGY', 'TECH_CONJURATION' ),
('TECH_THAUMATURGY', 'TECH_TRANSMUTATION' ),
('TECH_PHILOSOPHY', 'TECH_LOGIC' ),
('TECH_PHILOSOPHY', 'TECH_LITERATURE' ),
('TECH_DRAMA', 'TECH_LITERATURE' ),
('TECH_DRAMA', 'TECH_MUSIC' ),
('TECH_MATHEMATICS', 'TECH_MUSIC' ),
('TECH_MATHEMATICS', 'TECH_ALCHEMY' ),
('TECH_MATHEMATICS', 'TECH_MECHANICS' ),
('TECH_MATHEMATICS', 'TECH_BANKING' ),
('TECH_COINAGE', 'TECH_BANKING' ),
('TECH_MASONRY', 'TECH_CONSTRUCTION' ),
('TECH_BRONZE_WORKING', 'TECH_IRON_WORKING' ),
('TECH_DEEP_MINING', 'TECH_EARTH_DIVINATION' ),
('TECH_DEEP_MINING', 'TECH_UNDERDARK_PATHS' ),

--tier 4 req
('TECH_ANIMAL_INDUSTRY', 'TECH_ANIMAL_BREEDING' ),
('TECH_GAMEKEEPING', 'TECH_ANIMAL_MASTERY' ),
('TECH_BOWYERS', 'TECH_MARKSMANSHIP' ),
('TECH_SHIP_BUILDING', 'TECH_NAVIGATION' ),
('TECH_ASTRONOMY', 'TECH_NAVIGATION' ),
('TECH_ASTRONOMY', 'TECH_HEAVENLY_CYCLES' ),
('TECH_DIVINE_VITALISM', 'TECH_HEAVENLY_CYCLES' ),
('TECH_DIVINE_VITALISM', 'TECH_DIVINE_ESSENCE' ),
--('TECH_DIVINE_VITALISM', 'TECH_VAMPIRISM' ),
--('TECH_REANIMATION', 'TECH_VAMPIRISM' ),
('TECH_REANIMATION', 'TECH_NECROMANCY' ),
('TECH_SORCERY', 'TECH_SUMMONING' ),
('TECH_CONJURATION', 'TECH_SUMMONING' ),
('TECH_CONJURATION', 'TECH_EVOCATION' ),
('TECH_TRANSMUTATION', 'TECH_ABJURATION' ),
('TECH_LOGIC', 'TECH_SEMIOTICS' ),
('TECH_MUSIC', 'TECH_SEMIOTICS' ),
--('TECH_MUSIC', 'TECH_ILLUSION' ),
--('TECH_MUSIC', 'TECH_ENCHANTMENT' ),
('TECH_ALCHEMY', 'TECH_CHEMISTRY' ),
('TECH_CONSTRUCTION', 'TECH_SANITATION' ),
('TECH_MECHANICS', 'TECH_ENGINEERING' ),
('TECH_CONSTRUCTION', 'TECH_ENGINEERING' ),
('TECH_CONSTRUCTION', 'TECH_METAL_CASTING' ),
('TECH_IRON_WORKING', 'TECH_METAL_CASTING' ),

--tier 5 req
('TECH_STIRRUPS', 'TECH_WAR_HORSES' ),
('TECH_ANIMAL_BREEDING', 'TECH_WAR_HORSES' ),
('TECH_ELEPHANT_TRAINING', 'TECH_WAR_ELEPHANTS' ),
('TECH_ANIMAL_MASTERY', 'TECH_WAR_ELEPHANTS' ),
('TECH_ANIMAL_MASTERY', 'TECH_BEAST_MASTERY' ),
('TECH_HARPOONS', 'TECH_WHALING' ),
('TECH_NAVIGATION', 'TECH_WHALING' ),
('TECH_NAVIGATION', 'TECH_NAVAL_ENGINEERING' ),
('TECH_HEAVENLY_CYCLES', 'TECH_CELESTIAL_KNOWLEDGE' ),
('TECH_NECROMANCY', 'TECH_SOUL_BINDING' ),
('TECH_EVOCATION', 'TECH_INVOCATION' ),
('TECH_ABJURATION', 'TECH_INVOCATION' ),
('TECH_SEMIOTICS', 'TECH_INVOCATION' ),
('TECH_SEMIOTICS', 'TECH_METAPHYSICS' ),
--('TECH_ILLUSION', 'TECH_GREATER_ILLUSION' ),
--('TECH_ENCHANTMENT', 'TECH_AESTHETICS' ),
('TECH_MUSIC', 'TECH_AESTHETICS' ),		--Remove when above readded
('TECH_CHEMISTRY', 'TECH_MEDICINE' ),
('TECH_SANITATION', 'TECH_MEDICINE' ),
('TECH_ENGINEERING', 'TECH_ARCHITECTURE' ),
('TECH_ENGINEERING', 'TECH_MACHINERY' ),
('TECH_METAL_CASTING', 'TECH_MACHINERY' ),
('TECH_METAL_CASTING', 'TECH_STEEL_WORKING' ),
('TECH_METAL_CASTING', 'TECH_ELEMENTAL_FORGING' ),
('TECH_EARTH_DIVINATION', 'TECH_ELEMENTAL_FORGING' ),
--('TECH_EARTH_DIVINATION', 'TECH_DEEP_ROADS' ),
--('TECH_UNDERDARK_PATHS', 'TECH_DEEP_ROADS' ),

--tier 6 req
('TECH_WAR_ELEPHANTS', 'TECH_MUMAKIL_RIDING' ),
('TECH_BEAST_MASTERY', 'TECH_MUMAKIL_RIDING' ),
--('TECH_BEAST_MASTERY', 'TECH_SONG_OF_LEVIATHAN' ),
--('TECH_WHALING', 'TECH_SONG_OF_LEVIATHAN' ),
('TECH_NAVAL_ENGINEERING', 'TECH_ADV_NAVAL_ENGINEERING' ),
('TECH_CELESTIAL_KNOWLEDGE', 'TECH_DIVINE_INTERVENTION' ),
('TECH_DIVINE_ESSENCE', 'TECH_DIVINE_INTERVENTION' ),
('TECH_SUMMONING', 'TECH_BREACH' ),
('TECH_INVOCATION', 'TECH_BREACH' ),
('TECH_INVOCATION', 'TECH_GREATER_ARCANA' ),
('TECH_METAPHYSICS', 'TECH_GREATER_ARCANA' ),
('TECH_METAPHYSICS', 'TECH_TRANSCENDENTAL_THOUGHT' ),
--('TECH_GREATER_ILLUSION', 'TECH_PHANTASMAGORIA' ),
--('TECH_ENCHANTMENT', 'TECH_PHANTASMAGORIA' ),
--('TECH_AESTHETICS', 'TECH_ETHEREAL_ARCHITECTURE' ),
--('TECH_ARCHITECTURE', 'TECH_ETHEREAL_ARCHITECTURE' ),
('TECH_MACHINERY', 'TECH_STEAM_POWER' ),
('TECH_STEEL_WORKING', 'TECH_STEAM_POWER' ),
('TECH_STEEL_WORKING', 'TECH_MITHRIL_WORKING' ),
('TECH_ELEMENTAL_FORGING', 'TECH_MITHRIL_WORKING' ),

--tier 7 req
('TECH_DIVINE_INTERVENTION', 'TECH_KNOWLEDGE_OF_HEAVEN' ),
('TECH_SOUL_BINDING', 'TECH_ARMAGEDDON_RITUALS' ),
('TECH_BREACH', 'TECH_ARMAGEDDON_RITUALS' ),
('TECH_GREATER_ARCANA', 'TECH_ESOTERIC_ARCANA' ),
('TECH_TRANSCENDENTAL_THOUGHT', 'TECH_ESOTERIC_ARCANA' );

--utility techs
INSERT INTO Technology_PrereqTechs (PrereqTech, TechType) SELECT 'TECH_NEVER', Type FROM Technologies WHERE Utility = 1;


INSERT INTO EaDebugTableCheck(FileName) SELECT 'Technologies.sql';