DELETE FROM Technologies;
ALTER TABLE Technologies ADD COLUMN 'Utility' BOOLEAN DEFAULT NULL;
ALTER TABLE Technologies ADD COLUMN 'EaLandTradeRoutesChange' INTEGER DEFAULT 0;
ALTER TABLE Technologies ADD COLUMN 'EaSeaTradeRoutesChange' INTEGER DEFAULT 0;

-- Tier 1
INSERT INTO Technologies (GridX, GridY, Type, Cost, PortraitIndex, IconAtlas) VALUES
(0, 0, 'TECH_DOMESTICATION',			40,		2,	'TECH_ATLAS_1'				),
(0, 2, 'TECH_HUNTING',					40,		13,	'TECH_ATLAS_2'				),
(0, 5, 'TECH_FISHING',					40,		13,	'TECH_ATLAS_1'				),
(0, 9, 'TECH_AGRICULTURE',				40,		0,	'TECH_ATLAS_1'				),
(0,17, 'TECH_WRITING',					40,		8,	'TECH_ATLAS_1'				),
(0,22, 'TECH_CURRENCY',					40,		2,	'EXPANSION_TECH_ATLAS_1'	),
(0,24, 'TECH_MINING',					40,		1,	'TECH_ATLAS_1'				),
-- Tier 2
(1,-1, 'TECH_HORSEBACK_RIDING',			60,		11,	'TECH_ATLAS_1'				),
(1, 0, 'TECH_ANIMAL_HUSBANDRY',			60,		2,	'TECH_ATLAS_1'				),
(1, 1, 'TECH_ELEPHANT_LABOR',			60,		13,	'TECH_ATLAS_1'				),
(1, 2, 'TECH_TRACKING_TRAPPING',		60,		13,	'TECH_ATLAS_2'				),
(1, 3, 'TECH_ARCHERY',					60,		7,	'TECH_ATLAS_1'				),
(1, 4, 'TECH_HARPOONS',					60,		13,	'TECH_ATLAS_1'				),
(1, 5, 'TECH_SAILING',					60,		13,	'TECH_ATLAS_1'				),
(1, 6, 'TECH_MILLING',					60,		13,	'TECH_ATLAS_1'				),
(1, 7, 'TECH_WEAVING',					60,		13,	'TECH_ATLAS_1'				),
(1, 8, 'TECH_ZYMURGY',					60,		4,	'TECH_ATLAS_1'				),
(1, 9, 'TECH_IRRIGATION',				60,		13,	'TECH_ATLAS_1'				),
(1,10, 'TECH_CALENDAR',					60,		9,	'TECH_ATLAS_1'				),
(1,11, 'TECH_DIVINE_LITURGY',			60,		21,	'TECH_ATLAS_1'				),
(1,13, 'TECH_MALEFICIUM',				60,		9,	'TECH_ATLAS_2'				),
(1,15, 'TECH_THAUMATURGY',				60,		8,	'TECH_ATLAS_2'				),
(1,17, 'TECH_PHILOSOPHY',				60,		16,	'TECH_ATLAS_1'				),
(1,18, 'TECH_DRAMA',					60,		4,	'EXPANSION_TECH_ATLAS_1'	),
(1,20, 'TECH_MATHEMATICS',				60,		12,	'TECH_ATLAS_1'				),
(1,22, 'TECH_COINAGE',					60,		17,	'TECH_ATLAS_1'				),
(1,23, 'TECH_MASONRY',					60,		6,	'TECH_ATLAS_1'				),
(1,24, 'TECH_BRONZE_WORKING',			60,		5,	'TECH_ATLAS_1'				),
(1,25, 'TECH_DEEP_MINING',				60,		1,	'TECH_ATLAS_1'				),
-- Tier 3
(2,-1, 'TECH_STIRRUPS',					120,	11,	'TECH_ATLAS_1'				),
(2, 0, 'TECH_ANIMAL_INDUSTRY',			120,	2,	'TECH_ATLAS_1'				),
(2, 1, 'TECH_ELEPHANT_TRAINING',		120,	13,	'TECH_ATLAS_1'				),
(2, 2, 'TECH_GAMEKEEPING',				120,	13,	'TECH_ATLAS_2'				),
(2, 3, 'TECH_BOWYERS',					120,	7,	'TECH_ATLAS_1'				),
(2, 5, 'TECH_SHIP_BUILDING',			120,	13,	'TECH_ATLAS_1'				),
(2, 6, 'TECH_FORESTRY',					120,	13,	'TECH_ATLAS_1'				),
(2, 7, 'TECH_FINE_TEXTILES',			120,	13,	'TECH_ATLAS_1'				),
(2, 8, 'TECH_OENOLOGY',					120,	4,	'TECH_ATLAS_1'				),
(2, 9, 'TECH_CROP_ROTATION',			120,	13,	'TECH_ATLAS_1'				),
(2,10, 'TECH_ASTRONOMY',				120,	34,	'TECH_ATLAS_1'				),
(2,11, 'TECH_DIVINE_VITALISM',			120,	21,	'TECH_ATLAS_1'				),
(2,12, 'TECH_LYCANTHROPY',				120,	13,	'TECH_ATLAS_1'				),
(2,13, 'TECH_REANIMATION',				120,	10,	'TECH_ATLAS_2'				),
(2,14, 'TECH_SORCERY',					120,	9,	'TECH_ATLAS_2'				),
(2,15, 'TECH_CONJURATION',				120,	8,	'TECH_ATLAS_2'				),
(2,16, 'TECH_TRANSMUTATION',			120,	8,	'TECH_ATLAS_2'				),
(2,17, 'TECH_LOGIC',					120,	25,	'TECH_ATLAS_1'				),
(2,18, 'TECH_LITERATURE',				120,	13,	'TECH_ATLAS_1'				),
(2,19, 'TECH_MUSIC',					120,	14,	'TECH_ATLAS_2'				),
(2,20, 'TECH_ALCHEMY',					120,	37,	'TECH_ATLAS_1'				),
(2,21, 'TECH_MECHANICS',				120,	24,	'TECH_ATLAS_1'				),
(2,22, 'TECH_BANKING',					120,	31,	'TECH_ATLAS_1'				),
(2,23, 'TECH_CONSTRUCTION',				120,	15,	'TECH_ATLAS_1'				),
(2,24, 'TECH_IRON_WORKING',				120,	10,	'TECH_ATLAS_1'				),
(2,25, 'TECH_EARTH_DIVINATION',			120,	13,	'TECH_ATLAS_1'				),
(2,26, 'TECH_UNDERDARK_PATHS',			120,	1,	'TECH_ATLAS_1'				),
-- Tier 4
(3, 0, 'TECH_ANIMAL_BREEDING',			360,	2,	'TECH_ATLAS_1'				),
(3, 2, 'TECH_ANIMAL_MASTERY',			360,	13,	'TECH_ATLAS_2'				),
(3, 3, 'TECH_MARKSMANSHIP',				360,	7,	'TECH_ATLAS_1'				),
(3, 5, 'TECH_NAVIGATION',				360,	23,	'TECH_ATLAS_1'				),
(3,10, 'TECH_HEAVENLY_CYCLES',			360,	13,	'TECH_ATLAS_1'				),
(3,11, 'TECH_DIVINE_ESSENCE',			360,	21,	'TECH_ATLAS_1'				),
(3,12, 'TECH_VAMPIRISM',				360,	13,	'TECH_ATLAS_1'				),
(3,13, 'TECH_NECROMANCY',				360,	10,	'TECH_ATLAS_2'				),
(3,14, 'TECH_SUMMONING',				360,	9,	'TECH_ATLAS_2'				),
(3,15, 'TECH_EVOCATION',				360,	8,	'TECH_ATLAS_2'				),
(3,16, 'TECH_ABJURATION',				360,	8,	'TECH_ATLAS_2'				),
(3,17, 'TECH_SEMIOTICS',				360,	13,	'TECH_ATLAS_1'				),
(3,18, 'TECH_ILLUSION',					360,	7,	'TECH_ATLAS_2'				),
(3,19, 'TECH_ENCHANTMENT',				360,	7,	'TECH_ATLAS_2'				),
(3,20, 'TECH_CHEMISTRY',				360,	32,	'TECH_ATLAS_1'				),
(3,21, 'TECH_SANITATION',				360,	13,	'TECH_ATLAS_1'				),
(3,23, 'TECH_ENGINEERING',				360,	0,	'SHARED_TECH_ATLAS'			),
(3,24, 'TECH_METAL_CASTING',			360,	14,	'TECH_ATLAS_1'				),
-- Tier 5
(4,-1, 'TECH_WAR_HORSES',				1440,	11,	'TECH_ATLAS_1'				),
(4, 1, 'TECH_WAR_ELEPHANTS',			1440,	13,	'TECH_ATLAS_1'				),
(4, 2, 'TECH_BEAST_MASTERY',			1440,	13,	'TECH_ATLAS_1'				),
(4, 4, 'TECH_WHALING',					1440,	13,	'TECH_ATLAS_1'				),
(4, 5, 'TECH_NAVAL_ENGINEERING',		1440,	29,	'TECH_ATLAS_1'				),
(4,10, 'TECH_CELESTIAL_KNOWLEDGE',		1440,	13,	'TECH_ATLAS_1'				),
(4,13, 'TECH_SOUL_BINDING',				1440,	10,	'TECH_ATLAS_2'				),
(4,15, 'TECH_INVOCATION',				1440,	8,	'TECH_ATLAS_2'				),
(4,17, 'TECH_METAPHYSICS',				1440,	13,	'TECH_ATLAS_1'				),
(4,18, 'TECH_GREATER_ILLUSION',			1440,	7,	'TECH_ATLAS_2'				),
(4,20, 'TECH_AESTHETICS',				1440,	13,	'TECH_ATLAS_1'				),
(4,21, 'TECH_MEDICINE',					1440,	13,	'TECH_ATLAS_1'				),
(4,22, 'TECH_ARCHITECTURE',				1440,	0,	'EXPANSION_TECH_ATLAS_1'	),
(4,23, 'TECH_MACHINERY',				1440,	19,	'TECH_ATLAS_1'				),
(4,24, 'TECH_STEEL_WORKING',			1440,	28,	'TECH_ATLAS_1'				),
(4,25, 'TECH_ELEMENTAL_FORGING',		1440,	13,	'TECH_ATLAS_1'				),
(4,26, 'TECH_DEEP_ROADS',				1440,	1,	'TECH_ATLAS_1'				),
-- Tier 6
(5, 1, 'TECH_MUMAKIL_RIDING',			7200,	13,	'TECH_ATLAS_1'				),
(5, 3, 'TECH_SONG_OF_LEVIATHAN',		7200,	13,	'TECH_ATLAS_1'				),
(5, 5, 'TECH_ADV_NAVAL_ENGINEERING',	7200,	29,	'TECH_ATLAS_1'				),
(5,11, 'TECH_DIVINE_INTERVENTION',		7200,	21,	'TECH_ATLAS_1'				),
(5,14, 'TECH_BREACH',					7200,	9,	'TECH_ATLAS_2'				),
(5,15, 'TECH_GREATER_ARCANA',			7200,	8,	'TECH_ATLAS_2'				),
(5,17, 'TECH_COSMOGONY',				7200,	13,	'TECH_ATLAS_1'				),
(5,19, 'TECH_PHANTASMAGORIA',			7200,	7,	'TECH_ATLAS_2'				),
(5,21, 'TECH_ETHEREAL_ARCHITECTURE',	7200,	0,	'EXPANSION_TECH_ATLAS_1'	),
(5,23, 'TECH_STEAM_POWER',				7200,	42,	'TECH_ATLAS_1'				),
(5,25, 'TECH_MITHRIL_WORKING',			7200,	33,	'TECH_ATLAS_1'				),
-- Tier 7
(6,11, 'TECH_KNOWLEDGE_OF_HEAVEN',		43200,	27,	'TECH_ATLAS_1'				),
(6,13, 'TECH_ARMAGEDDON_RITUALS',		43200,	9,	'TECH_ATLAS_2'				),
(6,15, 'TECH_ESOTERIC_ARCANA',			43200,	8,	'TECH_ATLAS_2'				),
(6,17, 'TECH_TRANSCENDENTAL_THOUGHT',	43200,	13,	'TECH_ATLAS_1'				);

--Build out the table for dependent strings
UPDATE Technologies SET Description = 'TXT_KEY_EA_' || Type;
UPDATE Technologies SET Civilopedia = Description || '_PEDIA', Help = Description || '_HELP';

-- Utility techs (all automatically given prereq TECH_NEVER)
INSERT INTO Technologies (Type,		Utility) VALUES
('TECH_NEVER',						1	),
('TECH_NO_PAN',						1	),
('TECH_GAIN_WITH_NAMING',			1	),	--allows open borders
('TECH_ALLOW_TIMBER_TRADE',			1	),	--allows Timber trade and Timberyard
('TECH_ALLOW_HORSE_TRADE',			1	),	--allows Timber trade and Timberyard
('TECH_MOLY_VISIBLE',				1	),	--Moly visible, tradeable and improveable
('TECH_SLAVE_RAIDERS',				1	),
('TECH_SLAVE_ARMIES',				1	),
('TECH_PANTHEISM',					1	),
('TECH_ALLOW_MANA_YIELDS',			1	),
('TECH_ALLOW_DIVINE_FAVOR_YIELDS',	1	);


UPDATE Technologies SET GridX = 9, GridY = 36, Cost = -1, Description = 'TXT_KEY_EA_NOTSHOWN', Civilopedia = 'TXT_KEY_EA_NOTSHOWN', Help = 'TXT_KEY_EA_NOTSHOWN', PortraitIndex = 13, IconAtlas = 'TECH_ATLAS_1' WHERE Utility = 1;

UPDATE Technologies SET Trade='TRUE', GoodyTech='FALSE', Era='ERA_ANCIENT', Quote = 'TXT_KEY_EA_NOTSHOWN';		--Is NULL for quote OK?

UPDATE Technologies SET GoldTrading=1, InternationalTradeRoutesChange = 10 WHERE Type = 'TECH_CURRENCY';		--TO DO: trade route techs
UPDATE Technologies SET BridgeBuilding=1 WHERE Type='TECH_ENGINEERING';
UPDATE Technologies SET OpenBordersTradingAllowed=1 WHERE Type='TECH_GAIN_WITH_NAMING';
UPDATE Technologies SET WaterWork = 1 WHERE Type = 'TECH_FISHING';
UPDATE Technologies SET AllowsEmbarking = 1 WHERE Type = 'TECH_SAILING';
UPDATE Technologies SET EmbarkedAllWaterPassage = 1 WHERE Type = 'TECH_ASTRONOMY';

--UPDATE Technologies SET MapCentering = 1 WHERE Type = 'TECH_GAIN_WITH_NAMING';

-- Fixinator
CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM Technologies ORDER BY ID;
UPDATE Technologies SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Technologies.Type = IDRemapper.Type);
DROP TABLE IDRemapper;

--------------------------------------------------------------
-- Subtables
--------------------------------------------------------------

CREATE TABLE Technology_EaTechButtonIncludeSpecials (	TechType TEXT NOT NULL,
														SpecialText TEXT NOT NULL,
														IconAtlas TEXT DEFAULT NULL,	--uses star if NULL
														IconIndex INTEGER DEFAULT 0);
INSERT INTO Technology_EaTechButtonIncludeSpecials (TechType, SpecialText)
SELECT 'TECH_ELEPHANT_TRAINING','TXT_KEY_EA_TECH_ELEPHANT_TRAINING_SPECIAL'	UNION ALL
SELECT 'TECH_TRACKING_TRAPPING','TXT_KEY_EA_TECH_TRACKING_TRAPPING_SPECIAL'	UNION ALL
SELECT 'TECH_SAILING',			'TXT_KEY_EA_TECH_SAILING_SPECIAL'			UNION ALL
SELECT 'TECH_IRRIGATION',		'TXT_KEY_EA_TECH_IRRIGATION_SPECIAL'		UNION ALL
SELECT 'TECH_MALEFICIUM',		'TXT_KEY_EA_TECH_MALEFICIUM_SPECIAL'		UNION ALL
SELECT 'TECH_BOWYERS',			'TXT_KEY_EA_TECH_BOWYERS_SPECIAL'			UNION ALL
SELECT 'TECH_SHIP_BUILDING',	'TXT_KEY_EA_TECH_SHIP_BUILDING_SPECIAL'		UNION ALL
SELECT 'TECH_FORESTRY',			'TXT_KEY_EA_TECH_FORESTRY_SPECIAL1'			UNION ALL
SELECT 'TECH_FORESTRY',			'TXT_KEY_EA_TECH_FORESTRY_SPECIAL2'			UNION ALL
SELECT 'TECH_ASTRONOMY',		'TXT_KEY_EA_TECH_ASTRONOMY_SPECIAL'			UNION ALL
SELECT 'TECH_CHEMISTRY',		'TXT_KEY_EA_TECH_CHEMISTRY_SPECIAL'			UNION ALL
SELECT 'TECH_BEAST_MASTERY',	'TXT_KEY_EA_TECH_BEAST_MASTERY_SPECIAL'		UNION ALL
SELECT 'TECH_WHALING',			'TXT_KEY_EA_TECH_WHALING_SPECIAL'			UNION ALL
SELECT 'TECH_NAVIGATION',		'TXT_KEY_EA_TECH_NAVIGATION_SPECIAL'		UNION ALL
SELECT 'TECH_ANIMAL_MASTERY',	'TXT_KEY_EA_TECH_ANIMAL_MASTERY_SPECIAL'	;

--INSERT INTO Technology_EaTechButtonIncludeSpecials (TechType, SpecialText, IconAtlas, IconIndex)
--SELECT 'TECH_BRONZE_WORKING',	'TXT_KEY_EA_TECH_BRONZE_WORKING_SPECIAL', 'UNIT_ACTION_ATLAS', 38	;



DELETE FROM Technology_Flavors;				--not needed: mod controls all tech choices
DELETE FROM Technology_ORPrereqTechs;		--not used in base
DELETE FROM Technology_DomainExtraMoves;	--not used in base

DELETE FROM Technology_PrereqTechs;
INSERT INTO Technology_PrereqTechs (PrereqTech, TechType)	--flipped for easy reading
--tier 2 req
SELECT 'TECH_DOMESTICATION', 'TECH_HORSEBACK_RIDING' UNION ALL
SELECT 'TECH_DOMESTICATION', 'TECH_ANIMAL_HUSBANDRY' UNION ALL
SELECT 'TECH_DOMESTICATION', 'TECH_ELEPHANT_LABOR' UNION ALL
SELECT 'TECH_HUNTING', 'TECH_ELEPHANT_LABOR' UNION ALL
SELECT 'TECH_HUNTING', 'TECH_TRACKING_TRAPPING' UNION ALL
SELECT 'TECH_HUNTING', 'TECH_ARCHERY' UNION ALL
SELECT 'TECH_HUNTING', 'TECH_HARPOONS' UNION ALL
SELECT 'TECH_FISHING', 'TECH_HARPOONS' UNION ALL
SELECT 'TECH_FISHING', 'TECH_SAILING' UNION ALL
SELECT 'TECH_AGRICULTURE', 'TECH_MILLING' UNION ALL
SELECT 'TECH_AGRICULTURE', 'TECH_WEAVING' UNION ALL
SELECT 'TECH_AGRICULTURE', 'TECH_ZYMURGY' UNION ALL
SELECT 'TECH_AGRICULTURE', 'TECH_IRRIGATION' UNION ALL
SELECT 'TECH_AGRICULTURE', 'TECH_CALENDAR' UNION ALL
SELECT 'TECH_WRITING', 'TECH_CALENDAR' UNION ALL
SELECT 'TECH_WRITING', 'TECH_DIVINE_LITURGY' UNION ALL
SELECT 'TECH_WRITING', 'TECH_MALEFICIUM' UNION ALL
SELECT 'TECH_WRITING', 'TECH_THAUMATURGY' UNION ALL
SELECT 'TECH_WRITING', 'TECH_PHILOSOPHY' UNION ALL
SELECT 'TECH_WRITING', 'TECH_DRAMA' UNION ALL
SELECT 'TECH_WRITING', 'TECH_MATHEMATICS' UNION ALL
SELECT 'TECH_CURRENCY', 'TECH_MATHEMATICS' UNION ALL
SELECT 'TECH_CURRENCY', 'TECH_COINAGE' UNION ALL
SELECT 'TECH_MINING', 'TECH_COINAGE' UNION ALL
SELECT 'TECH_MINING', 'TECH_MASONRY' UNION ALL
SELECT 'TECH_MINING', 'TECH_BRONZE_WORKING' UNION ALL
SELECT 'TECH_MINING', 'TECH_DEEP_MINING' UNION ALL
--tier 3 req
SELECT 'TECH_HORSEBACK_RIDING', 'TECH_STIRRUPS' UNION ALL
SELECT 'TECH_ANIMAL_HUSBANDRY', 'TECH_ANIMAL_INDUSTRY' UNION ALL
SELECT 'TECH_ELEPHANT_LABOR', 'TECH_ELEPHANT_TRAINING' UNION ALL
SELECT 'TECH_TRACKING_TRAPPING', 'TECH_GAMEKEEPING' UNION ALL
SELECT 'TECH_ARCHERY', 'TECH_BOWYERS' UNION ALL
SELECT 'TECH_SAILING', 'TECH_SHIP_BUILDING' UNION ALL
SELECT 'TECH_MILLING', 'TECH_SHIP_BUILDING' UNION ALL
SELECT 'TECH_MILLING', 'TECH_FORESTRY' UNION ALL
SELECT 'TECH_WEAVING', 'TECH_FINE_TEXTILES' UNION ALL
SELECT 'TECH_ZYMURGY', 'TECH_OENOLOGY' UNION ALL
SELECT 'TECH_IRRIGATION', 'TECH_CROP_ROTATION' UNION ALL
SELECT 'TECH_CALENDAR', 'TECH_CROP_ROTATION' UNION ALL
SELECT 'TECH_CALENDAR', 'TECH_ASTRONOMY' UNION ALL
SELECT 'TECH_DIVINE_LITURGY', 'TECH_DIVINE_VITALISM' UNION ALL
SELECT 'TECH_MALEFICIUM', 'TECH_LYCANTHROPY' UNION ALL
SELECT 'TECH_MALEFICIUM', 'TECH_REANIMATION' UNION ALL
SELECT 'TECH_MALEFICIUM', 'TECH_SORCERY' UNION ALL
SELECT 'TECH_THAUMATURGY', 'TECH_SORCERY' UNION ALL
SELECT 'TECH_THAUMATURGY', 'TECH_CONJURATION' UNION ALL
SELECT 'TECH_THAUMATURGY', 'TECH_TRANSMUTATION' UNION ALL
SELECT 'TECH_PHILOSOPHY', 'TECH_LOGIC' UNION ALL
SELECT 'TECH_PHILOSOPHY', 'TECH_LITERATURE' UNION ALL
SELECT 'TECH_DRAMA', 'TECH_LITERATURE' UNION ALL
SELECT 'TECH_DRAMA', 'TECH_MUSIC' UNION ALL
SELECT 'TECH_MATHEMATICS', 'TECH_MUSIC' UNION ALL
SELECT 'TECH_MATHEMATICS', 'TECH_ALCHEMY' UNION ALL
SELECT 'TECH_MATHEMATICS', 'TECH_MECHANICS' UNION ALL
SELECT 'TECH_MATHEMATICS', 'TECH_BANKING' UNION ALL
SELECT 'TECH_COINAGE', 'TECH_BANKING' UNION ALL
SELECT 'TECH_MASONRY', 'TECH_CONSTRUCTION' UNION ALL
SELECT 'TECH_BRONZE_WORKING', 'TECH_IRON_WORKING' UNION ALL
SELECT 'TECH_DEEP_MINING', 'TECH_EARTH_DIVINATION' UNION ALL
SELECT 'TECH_DEEP_MINING', 'TECH_UNDERDARK_PATHS' UNION ALL

--tier 4 req
SELECT 'TECH_ANIMAL_INDUSTRY', 'TECH_ANIMAL_BREEDING' UNION ALL
SELECT 'TECH_GAMEKEEPING', 'TECH_ANIMAL_MASTERY' UNION ALL
SELECT 'TECH_BOWYERS', 'TECH_MARKSMANSHIP' UNION ALL
SELECT 'TECH_SHIP_BUILDING', 'TECH_NAVIGATION' UNION ALL
SELECT 'TECH_ASTRONOMY', 'TECH_NAVIGATION' UNION ALL
SELECT 'TECH_ASTRONOMY', 'TECH_HEAVENLY_CYCLES' UNION ALL
SELECT 'TECH_DIVINE_VITALISM', 'TECH_HEAVENLY_CYCLES' UNION ALL
SELECT 'TECH_DIVINE_VITALISM', 'TECH_DIVINE_ESSENCE' UNION ALL
SELECT 'TECH_DIVINE_VITALISM', 'TECH_VAMPIRISM' UNION ALL
SELECT 'TECH_REANIMATION', 'TECH_VAMPIRISM' UNION ALL
SELECT 'TECH_REANIMATION', 'TECH_NECROMANCY' UNION ALL
SELECT 'TECH_SORCERY', 'TECH_SUMMONING' UNION ALL
SELECT 'TECH_CONJURATION', 'TECH_SUMMONING' UNION ALL
SELECT 'TECH_CONJURATION', 'TECH_EVOCATION' UNION ALL
SELECT 'TECH_TRANSMUTATION', 'TECH_ABJURATION' UNION ALL
SELECT 'TECH_LOGIC', 'TECH_SEMIOTICS' UNION ALL
SELECT 'TECH_MUSIC', 'TECH_SEMIOTICS' UNION ALL
SELECT 'TECH_MUSIC', 'TECH_ILLUSION' UNION ALL
SELECT 'TECH_MUSIC', 'TECH_ENCHANTMENT' UNION ALL
SELECT 'TECH_ALCHEMY', 'TECH_CHEMISTRY' UNION ALL
SELECT 'TECH_CONSTRUCTION', 'TECH_SANITATION' UNION ALL
SELECT 'TECH_MECHANICS', 'TECH_ENGINEERING' UNION ALL
SELECT 'TECH_CONSTRUCTION', 'TECH_ENGINEERING' UNION ALL
SELECT 'TECH_CONSTRUCTION', 'TECH_METAL_CASTING' UNION ALL
SELECT 'TECH_IRON_WORKING', 'TECH_METAL_CASTING' UNION ALL

--tier 5 req
SELECT 'TECH_STIRRUPS', 'TECH_WAR_HORSES' UNION ALL
SELECT 'TECH_ANIMAL_BREEDING', 'TECH_WAR_HORSES' UNION ALL
SELECT 'TECH_ELEPHANT_TRAINING', 'TECH_WAR_ELEPHANTS' UNION ALL
SELECT 'TECH_ANIMAL_MASTERY', 'TECH_WAR_ELEPHANTS' UNION ALL
SELECT 'TECH_ANIMAL_MASTERY', 'TECH_BEAST_MASTERY' UNION ALL
SELECT 'TECH_HARPOONS', 'TECH_WHALING' UNION ALL
SELECT 'TECH_NAVIGATION', 'TECH_WHALING' UNION ALL
SELECT 'TECH_NAVIGATION', 'TECH_NAVAL_ENGINEERING' UNION ALL
SELECT 'TECH_HEAVENLY_CYCLES', 'TECH_CELESTIAL_KNOWLEDGE' UNION ALL
SELECT 'TECH_NECROMANCY', 'TECH_SOUL_BINDING' UNION ALL
SELECT 'TECH_EVOCATION', 'TECH_INVOCATION' UNION ALL
SELECT 'TECH_ABJURATION', 'TECH_INVOCATION' UNION ALL
SELECT 'TECH_SEMIOTICS', 'TECH_INVOCATION' UNION ALL
SELECT 'TECH_SEMIOTICS', 'TECH_METAPHYSICS' UNION ALL
SELECT 'TECH_ILLUSION', 'TECH_GREATER_ILLUSION' UNION ALL
SELECT 'TECH_ENCHANTMENT', 'TECH_AESTHETICS' UNION ALL
SELECT 'TECH_CHEMISTRY', 'TECH_MEDICINE' UNION ALL
SELECT 'TECH_SANITATION', 'TECH_MEDICINE' UNION ALL
SELECT 'TECH_ENGINEERING', 'TECH_ARCHITECTURE' UNION ALL
SELECT 'TECH_ENGINEERING', 'TECH_MACHINERY' UNION ALL
SELECT 'TECH_METAL_CASTING', 'TECH_MACHINERY' UNION ALL
SELECT 'TECH_METAL_CASTING', 'TECH_STEEL_WORKING' UNION ALL
SELECT 'TECH_METAL_CASTING', 'TECH_ELEMENTAL_FORGING' UNION ALL
SELECT 'TECH_EARTH_DIVINATION', 'TECH_ELEMENTAL_FORGING' UNION ALL
SELECT 'TECH_EARTH_DIVINATION', 'TECH_DEEP_ROADS' UNION ALL
SELECT 'TECH_UNDERDARK_PATHS', 'TECH_DEEP_ROADS' UNION ALL

--tier 6 req
SELECT 'TECH_WAR_ELEPHANTS', 'TECH_MUMAKIL_RIDING' UNION ALL
SELECT 'TECH_BEAST_MASTERY', 'TECH_MUMAKIL_RIDING' UNION ALL
SELECT 'TECH_BEAST_MASTERY', 'TECH_SONG_OF_LEVIATHAN' UNION ALL
SELECT 'TECH_WHALING', 'TECH_SONG_OF_LEVIATHAN' UNION ALL
SELECT 'TECH_NAVAL_ENGINEERING', 'TECH_ADV_NAVAL_ENGINEERING' UNION ALL
SELECT 'TECH_CELESTIAL_KNOWLEDGE', 'TECH_DIVINE_INTERVENTION' UNION ALL
SELECT 'TECH_DIVINE_ESSENCE', 'TECH_DIVINE_INTERVENTION' UNION ALL
SELECT 'TECH_SUMMONING', 'TECH_BREACH' UNION ALL
SELECT 'TECH_INVOCATION', 'TECH_BREACH' UNION ALL
SELECT 'TECH_INVOCATION', 'TECH_GREATER_ARCANA' UNION ALL
SELECT 'TECH_METAPHYSICS', 'TECH_GREATER_ARCANA' UNION ALL
SELECT 'TECH_METAPHYSICS', 'TECH_COSMOGONY' UNION ALL
SELECT 'TECH_GREATER_ILLUSION', 'TECH_PHANTASMAGORIA' UNION ALL
SELECT 'TECH_ENCHANTMENT', 'TECH_PHANTASMAGORIA' UNION ALL
SELECT 'TECH_AESTHETICS', 'TECH_ETHEREAL_ARCHITECTURE' UNION ALL
SELECT 'TECH_ARCHITECTURE', 'TECH_ETHEREAL_ARCHITECTURE' UNION ALL
SELECT 'TECH_MACHINERY', 'TECH_STEAM_POWER' UNION ALL
SELECT 'TECH_STEEL_WORKING', 'TECH_STEAM_POWER' UNION ALL
SELECT 'TECH_STEEL_WORKING', 'TECH_MITHRIL_WORKING' UNION ALL
SELECT 'TECH_ELEMENTAL_FORGING', 'TECH_MITHRIL_WORKING' UNION ALL

--tier 7 req
SELECT 'TECH_DIVINE_INTERVENTION', 'TECH_KNOWLEDGE_OF_HEAVEN' UNION ALL
SELECT 'TECH_SOUL_BINDING', 'TECH_ARMAGEDDON_RITUALS' UNION ALL
SELECT 'TECH_BREACH', 'TECH_ARMAGEDDON_RITUALS' UNION ALL
SELECT 'TECH_GREATER_ARCANA', 'TECH_ESOTERIC_ARCANA' UNION ALL
SELECT 'TECH_COSMOGONY', 'TECH_ESOTERIC_ARCANA' UNION ALL
SELECT 'TECH_COSMOGONY', 'TECH_TRANSCENDENTAL_THOUGHT' ;

--utility techs
INSERT INTO Technology_PrereqTechs (PrereqTech, TechType)
SELECT 'TECH_NEVER', Type FROM Technologies WHERE Utility = 1;


INSERT INTO EaDebugTableCheck(FileName) SELECT 'Technologies.sql';