-- Contains Yields, Terrains, Features, Resources, Improvements and Routes

-- Yield Overview:
--
-- Food per pop is now 3. Unresourced/unimporved tiles have no yield, except for oases and atols.
-- No yield (rather than small yield) is important for AI. The AI will work a 1f plot rather than
-- assign a specialist. With 0 yield the AI will properly assign a specialist. In general, a plot
-- should have at least 3 total yield or nothing at all.


-- Breach and Blight:
--
-- The system works around these existing Civ5 limitations:
--	1. Only the "base features" will update graphically during game session (forest, jungle,
--	   marsh, oasis and fallout (flood plains?). Renamed and new features WILL NOT UPDATE.
--	2. Improvements and Resources can update plot graphics (both through ArtDefine_Landmarks).
--	3. Features can give negative yields, but improvements and resources are only positive.
--
-- So, we use IMPROVEMENT_BLIGHT for graphic, but it has to displace any other improvments. For
-- existing improvments that can't be displaced, use RESOURCE_BLIGHT (exact same graphic). 
-- FEATURE_BLIGHT has no graphic effect but gives negative yield, and gives workers something to
-- remove. (dll is currently hard-coded to prioritize fallout removal.  
--
-- A breach plot is just blight plus FEATURE_FALLOUT. We have to use the base feature name for the
-- graphic to work. TO DO: change all cases of FEATURE_FALLOUT in dll to FEATURE_BLIGHT so that
-- workers will remove blight (breach can't be removed by workers).
--
-- The mod Lua code expects FEATURE_BLIGHT and FEATURE_FALLOUT to always be paired with either
-- IMPROVEMENT_BLIGHT or RESOURCE_BLIGHT. They are always added and removed together. If worker
-- just finishes a build - detected by GameEvents.BuildFinished( iPlayer, x, y, -1 ) - then we
-- look at plot to see if maybe blight was just removed, indicated by a plot that has no feature
-- but has IMPROVEMENT_BLIGHT or RESOURCE_BLIGHT. If so, then remove it.
--
-- IMPROVEMENT_BLIGHT graphic currently obscures any resource on the plot since there is only one
-- row in ArtDefine_Landmarks. In the future, we can add multiple ArtDefine_Landmarks variations
-- that show resources. Also, we can add additional IMPROVEMENT_BLIGHT variations to show other
-- effects like old burnt up forests (cosmetic only).


-----------------------------------------------------------------------------------------
--Yields
-----------------------------------------------------------------------------------------
UPDATE Yields SET MinCity = 4 WHERE Type='YIELD_FOOD';

-----------------------------------------------------------------------------------------
--Terrains
-----------------------------------------------------------------------------------------
UPDATE Terrains SET InfluenceCost = 10000 WHERE Type IN ('TERRAIN_COAST', 'TERRAIN_OCEAN');

DELETE FROM Terrain_Yields;
DELETE FROM Terrain_RiverYieldChanges;
DELETE FROM Terrain_HillsYieldChanges;

-----------------------------------------------------------------------------------------
--Features
-----------------------------------------------------------------------------------------
ALTER TABLE Features ADD COLUMN 'EaGod' TEXT DEFAULT NULL;
ALTER TABLE Features ADD COLUMN 'NaturalWonderHappiness' INTEGER DEFAULT 1;

INSERT INTO Features (Type, Description, Civilopedia, Help, ArtDefineTag, PortraitIndex, IconAtlas) VALUES
('FEATURE_BLIGHT',	'TXT_KEY_EA_FEATURE_BLIGHT',	'TXT_KEY_EA_FEATURE_BLIGHT_PEDIA',	'TXT_KEY_EA_FEATURE_BLIGHT_HELP',	'dummy',	17,	'TERRAIN_ATLAS');


UPDATE Features SET YieldNotAdditive = 0;

--Natural Wonders updates
UPDATE Features SET AdjacentUnitFreePromotion = NULL, FirstFinderGold = 0, InBorderHappiness = 0, OccurrenceFrequency = 10, AddsFreshWater = 0 WHERE NaturalWonder = 1;

UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_MOUNT_ABNOAB', EaGod = 'MINOR_CIV_GOD_ABNOAB' WHERE Type = 'FEATURE_SRI_PADA';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_SPRING_AVETA', EaGod = 'MINOR_CIV_GOD_AVETA' WHERE Type = 'FEATURE_FOUNTAIN_YOUTH';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_BORVOS_GEYSER', EaGod = 'MINOR_CIV_GOD_BORVO' WHERE Type = 'FEATURE_GEYSER';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_LAKE_BELISAMA', EaGod = 'MINOR_CIV_GOD_BELISAMA' WHERE Type = 'FEATURE_LAKE_VICTORIA';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_ELDIRS_VOLCANO', EaGod = 'MINOR_CIV_GOD_ELDIR' WHERE Type = 'FEATURE_VOLCANO';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_RITONAS_ROCK', EaGod = 'MINOR_CIV_GOD_RITONA' WHERE Type = 'FEATURE_GIBRALTAR';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_LI_BANS_REEF', EaGod = 'MINOR_CIV_GOD_LIBAN' WHERE Type = 'FEATURE_REEF';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_MOUNT_ERECURA', EaGod = 'MINOR_CIV_GOD_ERECURA' WHERE Type = 'FEATURE_FUJI';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_MOUNT_VOSEGUS', EaGod = 'MINOR_CIV_GOD_VOSEGUS' WHERE Type = 'FEATURE_KILIMANJARO';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_MOUNT_NANTOSUELTA', EaGod = 'MINOR_CIV_GOD_NANTOSUELTA' WHERE Type = 'FEATURE_MT_KAILASH';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_DIS_PATERS_VAULT', EaGod = 'MINOR_CIV_GOD_DIS_PATER' WHERE Type = 'FEATURE_POTOSI';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_MOUNT_NERGAL', EaGod = 'MINOR_CIV_GOD_NERGAL' WHERE Type = 'FEATURE_MT_SINAI';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_WADDS_ROCK', EaGod = 'MINOR_CIV_GOD_WADD' WHERE Type = 'FEATURE_ULURU';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_ABGALS_OUTCROP', EaGod = 'MINOR_CIV_GOD_ABGAL' WHERE Type = 'FEATURE_MESA';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_NESRS_BOWL', EaGod = 'MINOR_CIV_GOD_NESR', NaturalWonderHappiness = 0 WHERE Type = 'FEATURE_CRATER';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_PYRAMID_AZZANDARA' WHERE Type = 'FEATURE_EL_DORADO';
UPDATE Features SET Description = 'TXT_KEY_EA_FEATURE_VAULT_AHRIMAN', NaturalWonderHappiness = -2 WHERE Type = 'FEATURE_SOLOMONS_MINES';


UPDATE Features SET Civilopedia = Description || '_PEDIA' WHERE NaturalWonder = 1;


--Use Events.NaturalWonderRevealed


DELETE FROM Feature_RiverYieldChanges;

DELETE FROM Feature_YieldChanges;
INSERT INTO Feature_YieldChanges (FeatureType, YieldType, Yield) VALUES
('FEATURE_FOREST',	'YIELD_FOOD', -1),
('FEATURE_JUNGLE',	'YIELD_FOOD', -1),
('FEATURE_MARSH',	'YIELD_FOOD', -1),
('FEATURE_OASIS',	'YIELD_FOOD', 3	),
('FEATURE_ATOLL',	'YIELD_FOOD', 3	),
('FEATURE_BLIGHT',	'YIELD_FOOD', -3),
('FEATURE_BLIGHT',	'YIELD_PRODUCTION', -1),
('FEATURE_BLIGHT',	'YIELD_GOLD', -1),
('FEATURE_BLIGHT',	'YIELD_SCIENCE', -1),
('FEATURE_BLIGHT',	'YIELD_CULTURE', -1),
('FEATURE_BLIGHT',	'YIELD_FAITH', -1);


-----------------------------------------------------------------------------------------
--Resources (only Resource_YieldChanges entirely deleted and rebuilt)
-----------------------------------------------------------------------------------------

ALTER TABLE Resources ADD COLUMN 'EaMapName' TEXT DEFAULT NULL;

DELETE FROM Resources WHERE Type IN ('RESOURCE_COAL','RESOURCE_OIL','RESOURCE_ALUMINUM','RESOURCE_URANIUM','RESOURCE_IVORY', 'RESOURCE_TRUFFLES', 'RESOURCE_SHEEP', 'RESOURCE_COPPER');
INSERT INTO Resources (Type, Happiness, Description,							Civilopedia,										Help,										TechReveal,				TechCityTrade,				ResourceClassType,		ArtDefineTag,					ArtDefineTagHeavy,					AltArtDefineTag,					AltArtDefineTagHeavy,					AITradeModifier,	AIObjective,	ConstAppearance,	MinAreaSize,	MaxLatitude,	RandApp1,	RandApp2,	Player,	Hills,	Flatlands,	NoRiverSide,	IconString,				PortraitIndex,	IconAtlas) VALUES
('RESOURCE_ELEPHANT',		0,			'TXT_KEY_EA_RESOURCE_ELEPHANT',			'TXT_KEY_EA_CIV5_RESOURCE_ELEPHANT_TEXT',			'TXT_KEY_EA_RESOURCE_ELEPHANT_HELP',		NULL,					'TECH_ELEPHANT_LABOR',		'RESOURCECLASS_RUSH',	'ART_DEF_RESOURCE_IVORY',		NULL,								NULL,								NULL,									0,					1,				100,				3,				90,				10,			10,			50,		0,		1,			1,				'[ICON_RES_IVORY]',		15,				'RESOURCE_ATLAS'			),
('RESOURCE_BOARS',			0,			'TXT_KEY_EA_RESOURCE_BOARS',			'TXT_KEY_EA_CIV5_RESOURCE_BOARS_TEXT',				'TXT_KEY_EA_RESOURCE_BOARS_HELP',			NULL,					'TECH_HUNTING',				'RESOURCECLASS_BONUS',	'ART_DEF_RESOURCE_TRUFFLES',	NULL,								NULL,								NULL,									0,					0,				100,				3,				90,				10,			10,			0,		0,		1,			1,				'[ICON_RES_TRUFFLES]',	6,				'EXPANSION_RESOURCE_ATLAS'	),
('RESOURCE_COPPER',			0,			'TXT_KEY_EA_RESOURCE_COPPER',			'TXT_KEY_EA_CIV5_RESOURCE_COPPER_TEXT',				'TXT_KEY_EA_RESOURCE_COPPER_HELP',			'TECH_MINING',			'TECH_BRONZE_WORKING',		'RESOURCECLASS_RUSH',	'ART_DEF_RESOURCE_TIN',			'ART_DEF_RESOURCE_TIN',				'ART_DEF_RESOURCE_TIN',				'ART_DEF_RESOURCE_TIN',					0,					1,				100,				3,				90,				10,			10,			100,	1,		1,			1,				'[ICON_RES_COPPER]',	24,				'RESOURCE_ATLAS'			),
('RESOURCE_MITHRIL',		0,			'TXT_KEY_EA_RESOURCE_MITHRIL',			'TXT_KEY_EA_CIV5_RESOURCE_MITHRIL_TEXT',			'TXT_KEY_EA_RESOURCE_MITHRIL_HELP',			'TECH_EARTH_DIVINATION','TECH_MITHRIL_WORKING',		'RESOURCECLASS_RUSH',	'ART_DEF_RESOURCE_ALUMINUM',	'ART_DEF_RESOURCE_ALUMINUM_HEAVY',	'ART_DEF_RESOURCE_ALUMINUM',		'ART_DEF_RESOURCE_ALUMINUM_HEAVY',		0,					1,				100,				3,				90,				10,			10,			100,	1,		1,			1,				'[ICON_RES_ALUMINUM]',	24,				'RESOURCE_ATLAS'			),
('RESOURCE_NAPHTHA',		0,			'TXT_KEY_EA_RESOURCE_NAPHTHA',			'TXT_KEY_EA_CIV5_RESOURCE_NAPHTHA_TEXT',			'TXT_KEY_EA_RESOURCE_NAPHTHA_HELP',			'TECH_MATHEMATICS',		'TECH_ALCHEMY',				'RESOURCECLASS_RUSH',	'ART_DEF_RESOURCE_OIL',			'ART_DEF_RESOURCE_OIL_HEAVY',		'ART_DEF_RESOURCE_OIL_WATER',		'ART_DEF_RESOURCE_OIL_HEAVY_WATER',		0,					1,				100,				3,				90,				10,			10,			100,	0,		1,			1,				'[ICON_RES_COAL]',		2,				'RESOURCE_ATLAS'			),
('RESOURCE_MOLY',			0,			'TXT_KEY_EA_RESOURCE_MOLY',				'TXT_KEY_EA_CIV5_RESOURCE_MOLY_TEXT',				'TXT_KEY_EA_RESOURCE_MOLY_HELP',			'TECH_MOLY_VISIBLE',	'TECH_MOLY_VISIBLE',		'RESOURCECLASS_RUSH',	'ART_DEF_RESOURCE_ALOEVERA',	NULL,								NULL,								NULL,									0,					1,				100,				3,				90,				10,			10,			100,	1,		1,			1,				'[ICON_RES_URANIUM]',	5,				'RESOURCE_ATLAS'			),
('RESOURCE_QUICKSILVER',	0,			'TXT_KEY_EA_RESOURCE_QUICKSILVER',		'TXT_KEY_EA_CIV5_RESOURCE_QUICKSILVER_TEXT',		'TXT_KEY_EA_RESOURCE_QUICKSILVER_HELP',		'TECH_MATHEMATICS',		'TECH_ALCHEMY',				'RESOURCECLASS_RUSH',	'ART_DEF_RESOURCE_MANGANESE',	NULL,								'ART_DEF_RESOURCE_MANGANESE',		NULL,									0,					1,				100,				3,				90,				10,			10,			100,	1,		1,			1,				'[ICON_RES_URANIUM]',	5,				'RESOURCE_ATLAS'			),
('RESOURCE_JADE',			4,			'TXT_KEY_EA_RESOURCE_JADE',				'TXT_KEY_EA_CIV5_RESOURCE_JADE_TEXT',				'TXT_KEY_EA_RESOURCE_JADE_HELP',			NULL,					'TECH_MINING',				'RESOURCECLASS_LUXURY',	'ART_DEF_RESOURCE_LUBORIC',		NULL,								'ART_DEF_RESOURCE_LUBORIC',			NULL,									0,					1,				50,					3,				90,				25,			25,			67,		1,		1,			1,				'[ICON_RES_URANIUM]',	5,				'RESOURCE_ATLAS'			),
('RESOURCE_WOOL',			4,			'TXT_KEY_EA_RESOURCE_WOOL',				'TXT_KEY_EA_CIV5_RESOURCE_WOOL_TEXT',				'TXT_KEY_EA_RESOURCE_WOOL_HELP',			NULL,					'TECH_DOMESTICATION',		'RESOURCECLASS_LUXURY',	'ART_DEF_RESOURCE_SHEEP',		NULL,								NULL,								NULL,									0,					1,				50,					3,				90,				25,			25,			67,		1,		1,			1,				'[ICON_RES_SHEEP]',		26,				'RESOURCE_ATLAS'			),
('RESOURCE_YEW',			0,			'TXT_KEY_EA_RESOURCE_YEW',				'TXT_KEY_EA_CIV5_RESOURCE_YEW_TEXT',				'TXT_KEY_EA_RESOURCE_YEW_HELP',				NULL,					'TECH_ARCHERY',				'RESOURCECLASS_RUSH',	'ART_DEF_RESOURCE_SPICE',		NULL,								NULL,								NULL,									0,					1,				50,					3,				90,				25,			25,			67,		1,		1,			1,				'[ICON_RES_SPICES]',	17,				'RESOURCE_ATLAS'			),
('RESOURCE_TOBACCO',		4,			'TXT_KEY_EA_RESOURCE_TOBACCO',			'TXT_KEY_EA_CIV5_RESOURCE_TOBACCO_TEXT',			'TXT_KEY_EA_RESOURCE_TOBACCO_HELP',			NULL,					'TECH_CALENDAR',			'RESOURCECLASS_LUXURY',	'ART_DEF_RESOURCE_TOBACCO',		NULL,								NULL,								NULL,									0,					1,				50,					3,				90,				25,			25,			67,		0,		1,			1,				'[ICON_RES_URANIUM]',	5,				'RESOURCE_ATLAS'			),
('RESOURCE_TEA',			4,			'TXT_KEY_EA_RESOURCE_TEA',				'TXT_KEY_EA_CIV5_RESOURCE_TEA_TEXT',				'TXT_KEY_EA_RESOURCE_TEA_HELP',				NULL,					'TECH_CALENDAR',			'RESOURCECLASS_LUXURY',	'ART_DEF_RESOURCE_TEA',			NULL,								'ART_DEF_RESOURCE_TEA',				NULL,									0,					1,				50,					3,				90,				25,			25,			67,		1,		1,			1,				'[ICON_RES_URANIUM]',	26,				'RESOURCE_ATLAS'			),
('RESOURCE_OPIUM',			4,			'TXT_KEY_EA_RESOURCE_OPIUM',			'TXT_KEY_EA_CIV5_RESOURCE_OPIUM_TEXT',				'TXT_KEY_EA_RESOURCE_OPIUM_HELP',			NULL,					'TECH_CALENDAR',			'RESOURCECLASS_LUXURY',	'ART_DEF_RESOURCE_POPPY',		NULL,								NULL,								NULL,									0,					1,				50,					3,				90,				25,			25,			67,		0,		1,			1,				'[ICON_RES_URANIUM]',	5,				'RESOURCE_ATLAS'			),
('RESOURCE_BERRIES',		0,			'TXT_KEY_EA_RESOURCE_BERRIES',			'TXT_KEY_EA_CIV5_RESOURCE_BERRIES_TEXT',			'TXT_KEY_EA_RESOURCE_BERRIES_HELP',			NULL,					'TECH_IRRIGATION',			'RESOURCECLASS_BONUS',	'ART_DEF_RESOURCE_BERRIES',		NULL,								NULL,								NULL,									0,					0,				50,					3,				90,				25,			25,			0,		1,		1,			1,				'[ICON_RES_URANIUM]',	26,				'RESOURCE_ATLAS'			),
--blight - The "resource" is graphic only; use it where we can't use IMPROVEMENT_BLIGHT because there is a specific improvement (eg, Arcane Tower) that we don't want to displace.
('RESOURCE_BLIGHT',			0,			'TXT_KEY_EA_RESOURCE_BLIGHT',			'TXT_KEY_EA_CIV5_RESOURCE_BLIGHT_PEDIA',			'TXT_KEY_EA_RESOURCE_BLIGHT_HELP',			NULL,					NULL,						'RESOURCECLASS_BONUS',	'ART_DEF_RESOURCE_BLIGHT',		NULL,								NULL,								NULL,									0,					0,				50,					3,				90,				0,			0,			0,		1,		1,			0,				'[ICON_RES_URANIUM]',	26,				'RESOURCE_ATLAS'			);

UPDATE Resources SET TechCityTrade = 'TECH_AGRICULTURE' WHERE Type = 'RESOURCE_WHEAT';
UPDATE Resources SET TechReveal = NULL, TechCityTrade = 'TECH_ALLOW_HORSE_TRADE' WHERE Type = 'RESOURCE_HORSE';
UPDATE Resources SET TechReveal = 'TECH_MINING', TechCityTrade = 'TECH_IRON_WORKING' WHERE Type = 'RESOURCE_IRON';
UPDATE Resources SET TechCityTrade = 'TECH_DOMESTICATION' WHERE Type IN ('RESOURCE_HORSE','RESOURCE_COW');
UPDATE Resources SET TechCityTrade = 'TECH_HUNTING' WHERE Type IN ('RESOURCE_DEER','RESOURCE_FUR');
UPDATE Resources SET TechCityTrade = 'TECH_FISHING' WHERE Type IN ('RESOURCE_FISH','RESOURCE_PEARLS','RESOURCE_CRAB');
UPDATE Resources SET TechCityTrade = 'TECH_HARPOONS' WHERE Type = 'RESOURCE_WHALE';
UPDATE Resources SET TechCityTrade = 'TECH_ZYMURGY' WHERE Type = 'RESOURCE_WINE';
UPDATE Resources SET TechCityTrade = 'TECH_WEAVING' WHERE Type IN ('RESOURCE_DYE','RESOURCE_SILK','RESOURCE_COTTON');
UPDATE Resources SET TechCityTrade = 'TECH_IRRIGATION' WHERE Type IN ('RESOURCE_BANANA','RESOURCE_SUGAR','RESOURCE_CITRUS');
UPDATE Resources SET TechCityTrade = 'TECH_CALENDAR' WHERE Type IN ('RESOURCE_INCENSE','RESOURCE_SPICES');		--here to be safe

UPDATE Resources SET Happiness = 0, ResourceClassType = 'RESOURCECLASS_BONUS' WHERE Type IN ('RESOURCE_WHALE', 'RESOURCE_CRAB');	--changed to bonus

UPDATE Resources SET EaMapName = 'TXT_KEY_EA_RESOURCE_OYSTERS' WHERE Type = 'RESOURCE_PEARLS';
UPDATE Resources SET EaMapName = 'TXT_KEY_EA_RESOURCE_SMALL_GAME' WHERE Type = 'RESOURCE_FUR';
UPDATE Resources SET EaMapName = 'TXT_KEY_RESOURCE_SHEEP' WHERE Type = 'RESOURCE_WOOL';
UPDATE Resources SET EaMapName = 'TXT_KEY_EA_RESOURCE_SILKWORMS' WHERE Type = 'RESOURCE_SILK';
UPDATE Resources SET EaMapName = 'TXT_KEY_EA_RESOURCE_COTTON_TREES' WHERE Type = 'RESOURCE_COTTON';
UPDATE Resources SET EaMapName = 'TXT_KEY_EA_RESOURCE_SUGARCANE' WHERE Type = 'RESOURCE_SUGAR';
UPDATE Resources SET EaMapName = 'TXT_KEY_EA_RESOURCE_GRAPES' WHERE Type = 'RESOURCE_WINE';
UPDATE Resources SET EaMapName = 'TXT_KEY_EA_RESOURCE_CITRUS_TREES' WHERE Type = 'RESOURCE_CITRUS';
UPDATE Resources SET EaMapName = 'TXT_KEY_EA_RESOURCE_POPPIES' WHERE Type = 'RESOURCE_OPIUM';
UPDATE Resources SET EaMapName = 'TXT_KEY_EA_RESOURCE_CINNABAR' WHERE Type = 'RESOURCE_QUICKSILVER';

--debug map balancing
--UPDATE Resources SET TechReveal = NULL;



--non map
INSERT INTO Resources (Type, Happiness,	Description,		Civilopedia,							Help,								ResourceClassType,			AITradeModifier,	AIObjective,	Player, ResourceUsage,	IconString,				PortraitIndex,	IconAtlas			) VALUES
('RESOURCE_IVORY',		4,	'TXT_KEY_RESOURCE_IVORY',		'TXT_KEY_EA_CIV5_RESOURCE_IVORY_TEXT',	'TXT_KEY_EA_RESOURCE_IVORY_HELP',	'RESOURCECLASS_LUXURY',		10,					1,				67,		2,				'[ICON_RES_MARBLE]',	14,				'RESOURCE_ATLAS'	),
('RESOURCE_LEATHER',	4,	'TXT_KEY_EA_RESOURCE_LEATHER',	'TXT_KEY_EA_CIV5_RESOURCE_LEATHER_TEXT','TXT_KEY_EA_RESOURCE_LEATHER_HELP',	'RESOURCECLASS_LUXURY',		10,					1,				67,		2,				'[ICON_RES_FUR]',		25,				'RESOURCE_ATLAS'	),
('RESOURCE_ALE',		4,	'TXT_KEY_EA_RESOURCE_ALE',		'TXT_KEY_EA_CIV5_RESOURCE_ALE_TEXT',	'TXT_KEY_EA_RESOURCE_ALE_HELP',		'RESOURCECLASS_LUXURY',		10,					1,				67,		2,				'[ICON_RES_WINE]',		23,				'RESOURCE_ATLAS'	),
('RESOURCE_SPIRITS',	4,	'TXT_KEY_EA_RESOURCE_SPIRITS',	'TXT_KEY_EA_CIV5_RESOURCE_SPIRITS_TEXT','TXT_KEY_EA_RESOURCE_SPIRITS_HELP',	'RESOURCECLASS_LUXURY',		10,					1,				67,		2,				'[ICON_RES_WINE]',		23,				'RESOURCE_ATLAS'	),
('RESOURCE_TIMBER',		0,	'TXT_KEY_EA_RESOURCE_TIMBER',	'TXT_KEY_EA_CIV5_RESOURCE_TIMBER_TEXT',	'TXT_KEY_EA_RESOURCE_TIMBER_HELP',	'RESOURCECLASS_RUSH',		10,					1,				100,	1,				'[ICON_RES_SPICES]',	17,				'RESOURCE_ATLAS'	);

UPDATE Resources SET TechReveal = 'TECH_ALLOW_TIMBER_TRADE', TechCityTrade = 'TECH_ALLOW_TIMBER_TRADE' WHERE Type = 'RESOURCE_TIMBER';



DELETE FROM Resource_YieldChanges;
INSERT INTO Resource_YieldChanges (ResourceType, YieldType, Yield) VALUES
('RESOURCE_COPPER',		'YIELD_PRODUCTION', 3),
('RESOURCE_IRON',		'YIELD_PRODUCTION', 3),
('RESOURCE_MITHRIL',	'YIELD_PRODUCTION', 3),
('RESOURCE_GOLD',		'YIELD_GOLD',		3),
('RESOURCE_SILVER',		'YIELD_GOLD',		3),
('RESOURCE_GEMS',		'YIELD_GOLD',		3),
('RESOURCE_JADE',		'YIELD_GOLD',		2),
('RESOURCE_JADE',		'YIELD_CULTURE',	1),
('RESOURCE_SALT',		'YIELD_GOLD',		2),
('RESOURCE_SALT',		'YIELD_FOOD',		1),
('RESOURCE_MARBLE',		'YIELD_PRODUCTION', 2),
('RESOURCE_MARBLE',		'YIELD_CULTURE',	1),
('RESOURCE_STONE',		'YIELD_PRODUCTION', 3),
('RESOURCE_FISH',		'YIELD_FOOD',		3),
('RESOURCE_CRAB',		'YIELD_FOOD',		3),
('RESOURCE_PEARLS',		'YIELD_FOOD',		2),
('RESOURCE_PEARLS',		'YIELD_CULTURE',	1),
('RESOURCE_WHALE',		'YIELD_FOOD',		3),
('RESOURCE_DEER',		'YIELD_FOOD',		2),
('RESOURCE_DEER',		'YIELD_PRODUCTION', 1),
('RESOURCE_BOARS',		'YIELD_FOOD',		2),
('RESOURCE_BOARS',		'YIELD_PRODUCTION', 1),
('RESOURCE_FUR',		'YIELD_FOOD',		2),
('RESOURCE_FUR',		'YIELD_GOLD',		1),
('RESOURCE_ELEPHANT',	'YIELD_FOOD',		2),
('RESOURCE_ELEPHANT',	'YIELD_PRODUCTION', 1),
('RESOURCE_HORSE',		'YIELD_FOOD',		1),
('RESOURCE_HORSE',		'YIELD_PRODUCTION', 2),
('RESOURCE_COW',		'YIELD_FOOD',		3),
('RESOURCE_WOOL',		'YIELD_FOOD',		3),
('RESOURCE_WHEAT',		'YIELD_FOOD',		3),
('RESOURCE_BANANA',		'YIELD_FOOD',		4),
('RESOURCE_DYE',		'YIELD_GOLD',		2),
('RESOURCE_DYE',		'YIELD_CULTURE',	1),
('RESOURCE_SILK',		'YIELD_GOLD',		2),
('RESOURCE_SILK',		'YIELD_CULTURE',	1),
('RESOURCE_COTTON',		'YIELD_PRODUCTION', 1),
('RESOURCE_COTTON',		'YIELD_GOLD',		2),
('RESOURCE_SPICES',		'YIELD_FOOD',		1),
('RESOURCE_SPICES',		'YIELD_GOLD',		2),
('RESOURCE_SUGAR',		'YIELD_FOOD',		3),
('RESOURCE_WINE',		'YIELD_FOOD',		3),
('RESOURCE_CITRUS',		'YIELD_FOOD',		3),
('RESOURCE_INCENSE',	'YIELD_GOLD',		2),
('RESOURCE_INCENSE',	'YIELD_CULTURE',	1),
('RESOURCE_NAPHTHA',	'YIELD_PRODUCTION',	1),
('RESOURCE_NAPHTHA',	'YIELD_SCIENCE',	2),
('RESOURCE_YEW',		'YIELD_PRODUCTION', 3),
('RESOURCE_MOLY',		'YIELD_FAITH',		3),
('RESOURCE_QUICKSILVER','YIELD_SCIENCE',	3),
('RESOURCE_TOBACCO',	'YIELD_GOLD',		3),
('RESOURCE_TEA',		'YIELD_GOLD',		3),
('RESOURCE_OPIUM',		'YIELD_GOLD',		3),
('RESOURCE_BERRIES',	'YIELD_FOOD',		3);

DELETE FROM Resource_Flavors;
INSERT INTO Resource_Flavors (ResourceType, FlavorType, Flavor) VALUES
('RESOURCE_COPPER',		'FLAVOR_PRODUCTION',	15),
('RESOURCE_COPPER',		'FLAVOR_DEFENSE',		10),
('RESOURCE_COPPER',		'FLAVOR_OFFENSE',		10),
('RESOURCE_IRON',		'FLAVOR_PRODUCTION',	15),
('RESOURCE_IRON',		'FLAVOR_DEFENSE',		10),
('RESOURCE_IRON',		'FLAVOR_OFFENSE',		10),
('RESOURCE_MITHRIL',	'FLAVOR_PRODUCTION',	15),
('RESOURCE_MITHRIL',	'FLAVOR_DEFENSE',		10),
('RESOURCE_MITHRIL',	'FLAVOR_OFFENSE',		10),
('RESOURCE_GOLD',		'FLAVOR_GOLD',			15),
('RESOURCE_GOLD',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_SILVER',		'FLAVOR_GOLD',			15),
('RESOURCE_SILVER',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_GEMS',		'FLAVOR_GOLD',			15),
('RESOURCE_GEMS',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_JADE',		'FLAVOR_GOLD',			10),
('RESOURCE_JADE',		'FLAVOR_CULTURE',		5),
('RESOURCE_JADE',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_SALT',		'FLAVOR_GROWTH',		5),
('RESOURCE_SALT',		'FLAVOR_GOLD',			10),
('RESOURCE_SALT',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_MARBLE',		'FLAVOR_PRODUCTION',	10),
('RESOURCE_MARBLE',		'FLAVOR_CULTURE',		5),
('RESOURCE_MARBLE',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_STONE',		'FLAVOR_PRODUCTION',	15),
('RESOURCE_FISH',		'FLAVOR_GROWTH',		15),
('RESOURCE_CRAB',		'FLAVOR_GROWTH',		15),
('RESOURCE_PEARLS',		'FLAVOR_GROWTH',		10),
('RESOURCE_PEARLS',		'FLAVOR_CULTURE',		5),
('RESOURCE_PEARLS',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_WHALE',		'FLAVOR_GROWTH',		15),
('RESOURCE_WHALE',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_DEER',		'FLAVOR_GROWTH',		10),
('RESOURCE_DEER',		'FLAVOR_PRODUCTION',	5),
('RESOURCE_BOARS',		'FLAVOR_GROWTH',		10),
('RESOURCE_BOARS',		'FLAVOR_PRODUCTION',	5),
('RESOURCE_FUR',		'FLAVOR_GROWTH',		10),
('RESOURCE_FUR',		'FLAVOR_GOLD',			5),
('RESOURCE_FUR',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_ELEPHANT',	'FLAVOR_GROWTH',		10),
('RESOURCE_ELEPHANT',	'FLAVOR_PRODUCTION',	5),
('RESOURCE_ELEPHANT',	'FLAVOR_OFFENSE',		10),
('RESOURCE_ELEPHANT',	'FLAVOR_DEFENSE',		10),
('RESOURCE_ELEPHANT',	'FLAVOR_HAPPINESS',		10),
('RESOURCE_HORSE',		'FLAVOR_GROWTH',		5),
('RESOURCE_HORSE',		'FLAVOR_PRODUCTION',	10),
('RESOURCE_HORSE',		'FLAVOR_OFFENSE',		10),
('RESOURCE_HORSE',		'FLAVOR_DEFENSE',		5),
('RESOURCE_HORSE',		'FLAVOR_MOBILE',		10),
('RESOURCE_COW',		'FLAVOR_GROWTH',		15),
('RESOURCE_WOOL',		'FLAVOR_GROWTH',		15),
('RESOURCE_WOOL',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_WHEAT',		'FLAVOR_GROWTH',		15),
('RESOURCE_BANANA',		'FLAVOR_GROWTH',		20),
('RESOURCE_DYE',		'FLAVOR_GOLD',			10),
('RESOURCE_DYE',		'FLAVOR_CULTURE',		5),
('RESOURCE_DYE',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_SILK',		'FLAVOR_GOLD',			10),
('RESOURCE_SILK',		'FLAVOR_CULTURE',		5),
('RESOURCE_SILK',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_COTTON',		'FLAVOR_GOLD',			10),
('RESOURCE_COTTON',		'FLAVOR_PRODUCTION',	5),
('RESOURCE_COTTON',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_SPICES',		'FLAVOR_GROWTH',		5),
('RESOURCE_SPICES',		'FLAVOR_GOLD',			10),
('RESOURCE_SPICES',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_SUGAR',		'FLAVOR_GROWTH',		15),
('RESOURCE_SUGAR',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_WINE',		'FLAVOR_GROWTH',		15),
('RESOURCE_WINE',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_CITRUS',		'FLAVOR_GROWTH',		15),
('RESOURCE_CITRUS',		'FLAVOR_NAVAL',			10),
('RESOURCE_CITRUS',		'FLAVOR_NAVAL_RECON',	10),
('RESOURCE_CITRUS',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_INCENSE',	'FLAVOR_GOLD',			10),
('RESOURCE_INCENSE',	'FLAVOR_CULTURE',		5),
('RESOURCE_INCENSE',	'FLAVOR_RELIGION',		5),
('RESOURCE_INCENSE',	'FLAVOR_HAPPINESS',		10),
('RESOURCE_NAPHTHA',	'FLAVOR_PRODUCTION',	5),
('RESOURCE_NAPHTHA',	'FLAVOR_SCIENCE',		10),
('RESOURCE_NAPHTHA',	'FLAVOR_OFFENSE',		10),
('RESOURCE_NAPHTHA',	'FLAVOR_DEFENSE',		10),
('RESOURCE_YEW',		'FLAVOR_PRODUCTION',	15),
('RESOURCE_YEW',		'FLAVOR_OFFENSE',		10),
('RESOURCE_YEW',		'FLAVOR_DEFENSE',		10),
('RESOURCE_MOLY',		'FLAVOR_RELIGION',		25),
('RESOURCE_QUICKSILVER','FLAVOR_SCIENCE',		15),
('RESOURCE_QUICKSILVER','FLAVOR_RELIGION',		10),
('RESOURCE_QUICKSILVER','FLAVOR_HAPPINESS',		10),
('RESOURCE_TOBACCO',	'FLAVOR_GOLD',			15),
('RESOURCE_TOBACCO',	'FLAVOR_HAPPINESS',		10),
('RESOURCE_TEA',		'FLAVOR_GOLD',			15),
('RESOURCE_TEA',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_OPIUM',		'FLAVOR_GOLD',			15),
('RESOURCE_OPIUM',		'FLAVOR_HAPPINESS',		10),
('RESOURCE_BERRIES',	'FLAVOR_GROWTH',		15);

--tables below only affect worldbuilder and the mod's resource spawning function PlaceResourceNearCity()
DELETE FROM Resource_TerrainBooleans WHERE ResourceType IN ('RESOURCE_COAL','RESOURCE_OIL','RESOURCE_ALUMINUM','RESOURCE_URANIUM');
UPDATE Resource_TerrainBooleans SET ResourceType = 'RESOURCE_ELEPHANT' WHERE ResourceType = 'RESOURCE_IVORY';
UPDATE Resource_TerrainBooleans SET ResourceType = 'RESOURCE_BOARS' WHERE ResourceType = 'RESOURCE_TRUFFLES';
UPDATE Resource_TerrainBooleans SET ResourceType = 'RESOURCE_WOOL' WHERE ResourceType = 'RESOURCE_SHEEP';
INSERT INTO Resource_TerrainBooleans (ResourceType,	TerrainType) VALUES
('RESOURCE_MITHRIL',	'TERRAIN_GRASS'		),
('RESOURCE_MITHRIL',	'TERRAIN_PLAINS'	),
('RESOURCE_MITHRIL',	'TERRAIN_DESERT'	),
('RESOURCE_MITHRIL',	'TERRAIN_TUNDRA'	),
('RESOURCE_MITHRIL',	'TERRAIN_SNOW'		),

('RESOURCE_NAPHTHA',	'TERRAIN_GRASS'		),
('RESOURCE_NAPHTHA',	'TERRAIN_PLAINS'	),
('RESOURCE_NAPHTHA',	'TERRAIN_DESERT'	),
('RESOURCE_NAPHTHA',	'TERRAIN_TUNDRA'	),
('RESOURCE_NAPHTHA',	'TERRAIN_SNOW'		),

('RESOURCE_MOLY',		'TERRAIN_GRASS'		),
('RESOURCE_MOLY',		'TERRAIN_PLAINS'	),
('RESOURCE_MOLY',		'TERRAIN_DESERT'	),
('RESOURCE_MOLY',		'TERRAIN_TUNDRA'	),

('RESOURCE_QUICKSILVER','TERRAIN_GRASS'		),
('RESOURCE_QUICKSILVER','TERRAIN_PLAINS'	),
('RESOURCE_QUICKSILVER','TERRAIN_DESERT'	),
('RESOURCE_QUICKSILVER','TERRAIN_TUNDRA'	),
('RESOURCE_QUICKSILVER','TERRAIN_SNOW'		),

('RESOURCE_JADE',		'TERRAIN_GRASS'		),
('RESOURCE_JADE',		'TERRAIN_PLAINS'	),
('RESOURCE_JADE',		'TERRAIN_DESERT'	),
('RESOURCE_JADE',		'TERRAIN_TUNDRA'	),
('RESOURCE_JADE',		'TERRAIN_SNOW'		),

('RESOURCE_TOBACCO',	'TERRAIN_GRASS'		),
('RESOURCE_TOBACCO',	'TERRAIN_PLAINS'	),

('RESOURCE_TEA',		'TERRAIN_GRASS'		),

('RESOURCE_OPIUM',		'TERRAIN_GRASS'		),
('RESOURCE_OPIUM',		'TERRAIN_PLAINS'	),
('RESOURCE_OPIUM',		'TERRAIN_DESERT'	),

('RESOURCE_BERRIES',	'TERRAIN_GRASS'		),
('RESOURCE_BERRIES',	'TERRAIN_PLAINS'	),
('RESOURCE_BERRIES',	'TERRAIN_TUNDRA'	);

DELETE FROM Resource_FeatureBooleans;
INSERT INTO Resource_FeatureBooleans (ResourceType,	FeatureType) VALUES
('RESOURCE_YEW',		'FEATURE_FOREST'	);

DELETE FROM Resource_FeatureTerrainBooleans;
INSERT INTO Resource_FeatureTerrainBooleans (ResourceType,	TerrainType) VALUES
('RESOURCE_YEW',		'TERRAIN_GRASS'		),
('RESOURCE_YEW',		'TERRAIN_PLAINS'	),
('RESOURCE_YEW',		'TERRAIN_TUNDRA'	);

DELETE FROM Resource_QuantityTypes;		
INSERT INTO Resource_QuantityTypes (ResourceType,	Quantity) VALUES		--NOT used by AssignStartingPlots.lua (but used by mod resource spawning)
--common
('RESOURCE_HORSE',			6	),
('RESOURCE_HORSE',			4	),
('RESOURCE_COPPER',			8	),
('RESOURCE_COPPER',			4	),
('RESOURCE_IRON',			6	),
('RESOURCE_IRON',			4	),
--rare
('RESOURCE_YEW',			4	),
('RESOURCE_YEW',			2	),
('RESOURCE_MITHRIL',		2	),
('RESOURCE_MITHRIL',		1	),
('RESOURCE_NAPHTHA',		3	),
('RESOURCE_NAPHTHA',		2	),
('RESOURCE_MOLY',			2	),
('RESOURCE_MOLY',			1	),
('RESOURCE_QUICKSILVER',	2	),
('RESOURCE_QUICKSILVER',	1	);


--fixinator
CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM Resources ORDER BY ID;
UPDATE Resources SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Resources.Type = IDRemapper.Type);
DROP TABLE IDRemapper;

-----------------------------------------------------------------------------------------
--Improvements (delete as needed and rebuild)
-----------------------------------------------------------------------------------------
--There is some nasty hard-coding on IDs and/or type strings here in the graphics engine, at least for farm.

ALTER TABLE Improvements ADD COLUMN 'EaBlightSafe' BOOLEAN DEFAULT NULL;

-- "_2" versions below can be built on non-resource plots only; base improvements changed so they can only be built on resource plots
DELETE FROM Improvements WHERE Type NOT IN ('IMPROVEMENT_CITY_RUINS','IMPROVEMENT_BARBARIAN_CAMP','IMPROVEMENT_GOODY_HUT', 'IMPROVEMENT_FORT', 'IMPROVEMENT_CAMP',
'IMPROVEMENT_FARM', 'IMPROVEMENT_MINE', 'IMPROVEMENT_QUARRY', 'IMPROVEMENT_LUMBERMILL', 'IMPROVEMENT_PASTURE', 'IMPROVEMENT_WELL', 'IMPROVEMENT_FISHING_BOATS');
INSERT INTO Improvements (Type,	Description,								Civilopedia,											ArtDefineTag,								Water, PillageGold, Permanent,	DestroyedWhenPillaged,	PortraitIndex,	IconAtlas		) VALUES
--resource only improvements
('IMPROVEMENT_E_PLANTATION',	'TXT_KEY_EA_IMPROVEMENT_E_PLANTATION',		'TXT_KEY_EA_IMPROVEMENT_E_PLANTATION_PEDIA',			'ART_DEF_IMPROVEMENT_PLANTATION',			0,		10,			0,			0,						30,				'TERRAIN_ATLAS'	),
('IMPROVEMENT_VINEYARD',		'TXT_KEY_EA_IMPROVEMENT_VINEYARD',			'TXT_KEY_EA_IMPROVEMENT_VINEYARD_PEDIA',				'ART_DEF_IMPROVEMENT_PLANTATION',			0,		10,			0,			0,						30,				'TERRAIN_ATLAS' ),
('IMPROVEMENT_GATHERERS_HUT',	'TXT_KEY_EA_IMPROVEMENT_GATHERERS_HUT',		'TXT_KEY_EA_IMPROVEMENT_GATHERERS_HUT_PEDIA',			'ART_DEF_IMPROVEMENT_PLANTATION',			0,		10,			1,			0,						30,				'TERRAIN_ATLAS'	),
('IMPROVEMENT_BOWYERS_CAMP',	'TXT_KEY_EA_IMPROVEMENT_BOWYERS_CAMP',		'TXT_KEY_EA_IMPROVEMENT_BOWYERS_CAMP_PEDIA',			'ART_DEF_IMPROVEMENT_LUMBERMILL',			0,		10,			1,			0,						25,				'TERRAIN_ATLAS'	),

('IMPROVEMENT_WHALING_BOATS',	'TXT_KEY_EA_IMPROVEMENT_WHALING_BOATS',		'TXT_KEY_EA_IMPROVEMENT_WHALING_BOATS_PEDIA',			'ART_DEF_IMPROVEMENT_FISHING_BOATS',		1,		0,			1,			0,						23,				'TERRAIN_ATLAS' ),

('IMPROVEMENT_T_PLANTATION',	'TXT_KEY_EA_IMPROVEMENT_T_PLANTATION',		'TXT_KEY_EA_IMPROVEMENT_T_PLANTATION_PEDIA',			'ART_DEF_IMPROVEMENT_PLANTATION',			0,		10,			0,			0,						30,				'TERRAIN_ATLAS'	),
('IMPROVEMENT_ORCHARD',			'TXT_KEY_EA_IMPROVEMENT_ORCHARD',			'TXT_KEY_EA_IMPROVEMENT_ORCHARD_PEDIA',					'ART_DEF_IMPROVEMENT_PLANTATION',			0,		10,			0,			0,						30,				'TERRAIN_ATLAS'	),

--resource-only variations (for pantheistic)
('IMPROVEMENT_FARM_2',			'TXT_KEY_IMPROVEMENT_FARM',					'TXT_KEY_EA_IMPROVEMENT_FARM_PEDIA',					'ART_DEF_IMPROVEMENT_FARM_FIX',				0,		10,			0,			0,						22,				'TERRAIN_ATLAS'	),
('IMPROVEMENT_MINE_2',			'TXT_KEY_IMPROVEMENT_MINE',					'TXT_KEY_EA_IMPROVEMENT_MINE_PEDIA',					'ART_DEF_IMPROVEMENT_MINE',					0,		10,			0,			0,						26,				'TERRAIN_ATLAS'	),
('IMPROVEMENT_LUMBERMILL_2',	'TXT_KEY_EA_IMPROVEMENT_LUMBERMILL',		'TXT_KEY_EA_IMPROVEMENT_LUMBERMILL_PEDIA',				'ART_DEF_IMPROVEMENT_LUMBERMILL',			0,		10,			0,			0,						25,				'TERRAIN_ATLAS'	),

('IMPROVEMENT_BLIGHT',			'TXT_KEY_EA_BLIGHT',						'TXT_KEY_EA_BLIGHT_PEDIA',								'ART_DEF_IMPROVEMENT_BLIGHT',				0,		0,			1,			0,						25,				'TERRAIN_ATLAS'	);

--wonders
INSERT INTO Improvements (Type,	Description,								Civilopedia,											ArtDefineTag,								Water, PillageGold, Permanent,	DestroyedWhenPillaged,	EaBlightSafe,	PortraitIndex,	IconAtlas								) VALUES
('IMPROVEMENT_ARCANE_TOWER',	'TXT_KEY_EA_ARCANE_TOWER',					'TXT_KEY_EA_ARCANE_TOWER_PEDIA',						'ART_DEF_IMPROVEMENT_CHATEAU',				0,		10,			1,			0,						1,				2,				'TERRAIN_IMPROVEMENT_ICON_ATLAS_EXP2'	);


UPDATE Improvements SET PillageGold = 0, Permanent = 1 WHERE Type IN ('IMPROVEMENT_CAMP','IMPROVEMENT_FISHING_BOATS');

--These are the non-resource improvements
UPDATE Improvements SET FreshWaterMakesValid = 1, RequiresFlatlandsOrFreshWater = 1 WHERE Type = 'IMPROVEMENT_FARM';
UPDATE Improvements SET HillsMakesValid = 1 WHERE Type = 'IMPROVEMENT_MINE';
UPDATE Improvements SET RequiresFeature = 1, Description = 'TXT_KEY_EA_IMPROVEMENT_LUMBERMILL' WHERE Type = 'IMPROVEMENT_LUMBERMILL';

--RiverSideMakesValid
--RequiresFlatlandsOrFreshWater
--FreshWaterMakesValid


DELETE FROM Improvement_HillsYields;
DELETE FROM Improvement_TechNoFreshWaterYieldChanges;

DELETE FROM Improvement_ValidTerrains;
INSERT INTO Improvement_ValidTerrains (ImprovementType, TerrainType) VALUES
('IMPROVEMENT_BARBARIAN_CAMP',	'TERRAIN_GRASS'	),
('IMPROVEMENT_BARBARIAN_CAMP',	'TERRAIN_PLAINS'),
('IMPROVEMENT_BARBARIAN_CAMP',	'TERRAIN_DESERT'),
('IMPROVEMENT_BARBARIAN_CAMP',	'TERRAIN_TUNDRA'),
('IMPROVEMENT_GOODY_HUT',		'TERRAIN_GRASS'	),
('IMPROVEMENT_GOODY_HUT',		'TERRAIN_PLAINS'),
('IMPROVEMENT_GOODY_HUT',		'TERRAIN_DESERT'),
('IMPROVEMENT_GOODY_HUT',		'TERRAIN_TUNDRA'),
('IMPROVEMENT_FORT',			'TERRAIN_GRASS' ),
('IMPROVEMENT_FORT',			'TERRAIN_PLAINS'),
('IMPROVEMENT_FORT',			'TERRAIN_DESERT'),
('IMPROVEMENT_FORT',			'TERRAIN_TUNDRA'),
('IMPROVEMENT_FORT',			'TERRAIN_SNOW'	),
('IMPROVEMENT_FARM',			'TERRAIN_GRASS' ),
--('IMPROVEMENT_MINE',			'TERRAIN_HILL'	);

('IMPROVEMENT_ARCANE_TOWER',	'TERRAIN_GRASS' ),
('IMPROVEMENT_ARCANE_TOWER',	'TERRAIN_PLAINS'),
('IMPROVEMENT_ARCANE_TOWER',	'TERRAIN_DESERT'),
('IMPROVEMENT_ARCANE_TOWER',	'TERRAIN_TUNDRA'),
('IMPROVEMENT_ARCANE_TOWER',	'TERRAIN_SNOW'	);

DELETE FROM Improvement_ValidFeatures;
INSERT INTO Improvement_ValidFeatures (ImprovementType, FeatureType) VALUES
('IMPROVEMENT_BARBARIAN_CAMP',	'FEATURE_FOREST' ),
('IMPROVEMENT_BARBARIAN_CAMP',	'FEATURE_JUNGLE' ),
('IMPROVEMENT_GOODY_HUT',		'FEATURE_FOREST' ),
('IMPROVEMENT_GOODY_HUT',		'FEATURE_JUNGLE' ),
('IMPROVEMENT_LUMBERMILL',		'FEATURE_FOREST' ),
('IMPROVEMENT_LUMBERMILL',		'FEATURE_JUNGLE' );

DELETE FROM Improvement_Yields;
INSERT INTO Improvement_Yields (ImprovementType, YieldType, Yield) VALUES
('IMPROVEMENT_FARM_2',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_MINE_2',			'YIELD_PRODUCTION',	2 ),
('IMPROVEMENT_LUMBERMILL_2',	'YIELD_PRODUCTION',	1 ),
('IMPROVEMENT_BOWYERS_CAMP',	'YIELD_PRODUCTION',	1 ),
('IMPROVEMENT_PASTURE',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_E_PLANTATION',	'YIELD_GOLD',		2 ),
('IMPROVEMENT_T_PLANTATION',	'YIELD_GOLD',		2 ),
('IMPROVEMENT_ORCHARD',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_ORCHARD',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_VINEYARD',		'YIELD_GOLD',		1 ),
('IMPROVEMENT_VINEYARD',		'YIELD_CULTURE',	1 ),
('IMPROVEMENT_QUARRY',			'YIELD_PRODUCTION',	2 ),
('IMPROVEMENT_CAMP',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_FISHING_BOATS',	'YIELD_FOOD',		2 ),
('IMPROVEMENT_WHALING_BOATS',	'YIELD_FOOD',		2 ),
('IMPROVEMENT_WELL',			'YIELD_PRODUCTION',	1 );


DELETE FROM Improvement_ResourceTypes; -- WHERE ResourceType IN ('RESOURCE_WHALE','RESOURCE_WINE','RESOURCE_IVORY','RESOURCE_COAL','RESOURCE_OIL','RESOURCE_ALUMINUM','RESOURCE_URANIUM');
INSERT INTO Improvement_ResourceTypes (ImprovementType, ResourceType) VALUES
('IMPROVEMENT_FARM_2',			'RESOURCE_WHEAT'		),
('IMPROVEMENT_MINE_2',			'RESOURCE_COPPER'		),
('IMPROVEMENT_MINE_2',			'RESOURCE_IRON'			),
('IMPROVEMENT_MINE_2',			'RESOURCE_MITHRIL'		),
('IMPROVEMENT_MINE_2',			'RESOURCE_GOLD'			),
('IMPROVEMENT_MINE_2',			'RESOURCE_SILVER'		),
('IMPROVEMENT_MINE_2',			'RESOURCE_GEMS'			),
('IMPROVEMENT_MINE_2',			'RESOURCE_JADE'			),
('IMPROVEMENT_MINE_2',			'RESOURCE_SALT'			),
('IMPROVEMENT_MINE_2',			'RESOURCE_NAPHTHA'		),
('IMPROVEMENT_WELL',			'RESOURCE_NAPHTHA'		),
('IMPROVEMENT_MINE',			'RESOURCE_QUICKSILVER'	),
('IMPROVEMENT_QUARRY',			'RESOURCE_MARBLE'		),
('IMPROVEMENT_QUARRY',			'RESOURCE_STONE'		),
('IMPROVEMENT_LUMBERMILL',		'RESOURCE_YEW'			),
('IMPROVEMENT_BOWYERS_CAMP',	'RESOURCE_YEW'			),
('IMPROVEMENT_FISHING_BOATS',	'RESOURCE_FISH'			),
('IMPROVEMENT_FISHING_BOATS',	'RESOURCE_CRAB'			),
('IMPROVEMENT_FISHING_BOATS',	'RESOURCE_PEARLS'		),
('IMPROVEMENT_WHALING_BOATS',	'RESOURCE_WHALE'		),
('IMPROVEMENT_CAMP',			'RESOURCE_DEER'			),
('IMPROVEMENT_CAMP',			'RESOURCE_BOARS'		),
('IMPROVEMENT_CAMP',			'RESOURCE_FUR'			),
('IMPROVEMENT_CAMP',			'RESOURCE_ELEPHANT'		),
('IMPROVEMENT_PASTURE',			'RESOURCE_HORSE'		),
('IMPROVEMENT_PASTURE',			'RESOURCE_COW'			),
('IMPROVEMENT_PASTURE',			'RESOURCE_WOOL'			),
('IMPROVEMENT_T_PLANTATION',	'RESOURCE_DYE'			),
('IMPROVEMENT_T_PLANTATION',	'RESOURCE_SILK'			),
('IMPROVEMENT_T_PLANTATION',	'RESOURCE_COTTON'		),
('IMPROVEMENT_ORCHARD',			'RESOURCE_BANANA'		),
('IMPROVEMENT_ORCHARD',			'RESOURCE_SUGAR'		),
('IMPROVEMENT_ORCHARD',			'RESOURCE_CITRUS'		),
('IMPROVEMENT_ORCHARD',			'RESOURCE_BERRIES'		),
('IMPROVEMENT_E_PLANTATION',	'RESOURCE_INCENSE'		),
('IMPROVEMENT_E_PLANTATION',	'RESOURCE_SPICES'		),
('IMPROVEMENT_E_PLANTATION',	'RESOURCE_TOBACCO'		),
('IMPROVEMENT_E_PLANTATION',	'RESOURCE_TEA'			),
('IMPROVEMENT_E_PLANTATION',	'RESOURCE_OPIUM'		),
('IMPROVEMENT_VINEYARD',		'RESOURCE_WINE'			),
('IMPROVEMENT_GATHERERS_HUT',	'RESOURCE_MOLY'			);

DELETE FROM Improvement_ResourceType_Yields;
INSERT INTO Improvement_ResourceType_Yields (ImprovementType, ResourceType, YieldType, Yield) VALUES
('IMPROVEMENT_FARM_2',			'RESOURCE_WHEAT',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_MINE_2',			'RESOURCE_COPPER',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_MINE_2',			'RESOURCE_IRON',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_MINE_2',			'RESOURCE_MITHRIL',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_MINE_2',			'RESOURCE_GOLD',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_MINE_2',			'RESOURCE_SILVER',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_MINE_2',			'RESOURCE_GEMS',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_MINE_2',			'RESOURCE_JADE',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_MINE_2',			'RESOURCE_SALT',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_WELL',			'RESOURCE_NAPHTHA',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_LUMBERMILL_2',	'RESOURCE_YEW',				'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_BOWYERS_CAMP',	'RESOURCE_YEW',				'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_BOWYERS_CAMP',	'RESOURCE_YEW',				'YIELD_CULTURE',	1 ),
('IMPROVEMENT_QUARRY',			'RESOURCE_MARBLE',			'YIELD_CULTURE',	1 ),
('IMPROVEMENT_QUARRY',			'RESOURCE_STONE',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_FISHING_BOATS',	'RESOURCE_FISH',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_FISHING_BOATS',	'RESOURCE_CRAB',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_FISHING_BOATS',	'RESOURCE_PEARLS',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_WHALING_BOATS',	'RESOURCE_WHALE',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_CAMP',			'RESOURCE_DEER',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_CAMP',			'RESOURCE_BOARS',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_CAMP',			'RESOURCE_FUR',				'YIELD_GOLD',		1 ),
('IMPROVEMENT_CAMP',			'RESOURCE_ELEPHANT',		'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_PASTURE',			'RESOURCE_HORSE',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_PASTURE',			'RESOURCE_COW',				'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_PASTURE',			'RESOURCE_WOOL',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_VINEYARD',		'RESOURCE_WINE',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_T_PLANTATION',	'RESOURCE_DYE',				'YIELD_GOLD',		1 ),
('IMPROVEMENT_T_PLANTATION',	'RESOURCE_SILK',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_T_PLANTATION',	'RESOURCE_COTTON',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_ORCHARD',			'RESOURCE_BANANA',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_ORCHARD',			'RESOURCE_SUGAR',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_ORCHARD',			'RESOURCE_CITRUS',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_ORCHARD',			'RESOURCE_BERRIES',			'YIELD_FOOD',		1 ),
('IMPROVEMENT_E_PLANTATION',	'RESOURCE_INCENSE',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_E_PLANTATION',	'RESOURCE_SPICES',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_E_PLANTATION',	'RESOURCE_TOBACCO',			'YIELD_GOLD',		1 ),
('IMPROVEMENT_E_PLANTATION',	'RESOURCE_TEA',				'YIELD_GOLD',		1 ),
('IMPROVEMENT_E_PLANTATION',	'RESOURCE_OPIUM',			'YIELD_GOLD',		1 );

DELETE FROM Improvement_Flavors;
INSERT INTO Improvement_Flavors (ImprovementType, FlavorType, Flavor) VALUES
('IMPROVEMENT_FARM',			'FLAVOR_GROWTH',		10),		--assume Dominionism
('IMPROVEMENT_MINE',			'FLAVOR_PRODUCTION',	10),
('IMPROVEMENT_LUMBERMILL',		'FLAVOR_PRODUCTION',	10),
('IMPROVEMENT_FARM_2',			'FLAVOR_GROWTH',		10),
('IMPROVEMENT_MINE_2',			'FLAVOR_PRODUCTION',	10),
('IMPROVEMENT_LUMBERMILL_2',	'FLAVOR_PRODUCTION',	10),
('IMPROVEMENT_LUMBERMILL_2',	'FLAVOR_NAVAL',			25),
('IMPROVEMENT_QUARRY',			'FLAVOR_PRODUCTION',	15),
('IMPROVEMENT_PASTURE',			'FLAVOR_GROWTH',		5),
('IMPROVEMENT_PASTURE',			'FLAVOR_PRODUCTION',	5),
('IMPROVEMENT_WELL',			'FLAVOR_PRODUCTION',	10),
('IMPROVEMENT_E_PLANTATION',	'FLAVOR_GOLD',			15),
('IMPROVEMENT_T_PLANTATION',	'FLAVOR_GOLD',			15),
('IMPROVEMENT_ORCHARD',			'FLAVOR_GROWTH',		10),
('IMPROVEMENT_ORCHARD',			'FLAVOR_GOLD',			5),
('IMPROVEMENT_VINEYARD',		'FLAVOR_GOLD',			10),
('IMPROVEMENT_VINEYARD',		'FLAVOR_CULTURE',		5),
('IMPROVEMENT_GATHERERS_HUT',	'FLAVOR_RELIGION',		15),
('IMPROVEMENT_BOWYERS_CAMP',	'FLAVOR_PRODUCTION',	10),
('IMPROVEMENT_BOWYERS_CAMP',	'FLAVOR_CULTURE',		5);

DELETE FROM Improvement_TechYieldChanges;
INSERT INTO Improvement_TechYieldChanges (ImprovementType, TechType, YieldType, Yield) VALUES
--('IMPROVEMENT_FARM',			'TECH_NO_PAN',				'YIELD_FOOD',		2 ),
--('IMPROVEMENT_MINE',			'TECH_NO_PAN',				'YIELD_PRODUCTION',	2 ),
--('IMPROVEMENT_LUMBERMILL',		'TECH_NO_PAN',				'YIELD_PRODUCTION', 2 ),

('IMPROVEMENT_FARM_2',			'TECH_CROP_ROTATION',		'YIELD_FOOD',		1 ),
('IMPROVEMENT_LUMBERMILL_2',	'TECH_FORESTRY',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_BOWYERS_CAMP',	'TECH_FORESTRY',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_FARM',			'TECH_CROP_ROTATION',		'YIELD_FOOD',		1 ),
('IMPROVEMENT_LUMBERMILL',		'TECH_FORESTRY',			'YIELD_PRODUCTION', 1 ),
('IMPROVEMENT_CAMP',			'TECH_ANIMAL_MASTERY',		'YIELD_FOOD',		1 ),
('IMPROVEMENT_PASTURE',			'TECH_ANIMAL_BREEDING',		'YIELD_FOOD',		1 ),
('IMPROVEMENT_GATHERERS_HUT',	'TECH_ALLOW_MANA_YIELDS',	'YIELD_FAITH',		3 );

DELETE FROM Improvement_TechFreshWaterYieldChanges;
INSERT INTO Improvement_TechFreshWaterYieldChanges (ImprovementType, TechType, YieldType, Yield) VALUES
('IMPROVEMENT_FARM_2',	'TECH_IRRIGATION',			'YIELD_FOOD', 1 ),
('IMPROVEMENT_FARM',	'TECH_IRRIGATION',			'YIELD_FOOD', 1 );


--TO DO:
--Negative yields from Policy_ImprovementYieldChanges


--fixinator
CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM Improvements ORDER BY ID;
UPDATE Improvements SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Improvements.Type = IDRemapper.Type);
DROP TABLE IDRemapper;

-----------------------------------------------------------------------------------------
-- Routes (change railroad to Imperial Road)
-----------------------------------------------------------------------------------------
/*
UPDATE Routes SET Movement=50, FlatMovement=50, PortraitIndex=40 WHERE Type='ROUTE_ROAD';
UPDATE Routes SET Type='ROUTE_IMPERIAL_ROAD', Description='TXT_KEY_EA_IMPERIAL_ROAD', Civilopedia='TXT_KEY_EA_CIV5_IMPROVEMENTS_IMPERIAL_ROAD_TEXT', Movement=30, FlatMovement=30, PortraitIndex=40 WHERE Type='ROUTE_RAILROAD';
UPDATE Route_Yields SET RouteType='ROUTE_IMPERIAL_ROAD' WHERE RouteType='ROUTE_RAILROAD';
DELETE FROM Route_TechMovementChanges;
INSERT INTO Route_TechMovementChanges (RouteType, TechType, MovementChange)
SELECT 'ROUTE_IMPERIAL_ROAD', 'TECH_STEAM_POWER', -10;
DELETE FROM Route_ResourceQuantityRequirements;
*/



--fixinator (may need if road is not id=0)
--CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
--INSERT INTO IDRemapper (Type) SELECT Type FROM Routes;
--UPDATE Routes SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Routes.Type = IDRemapper.Type);
--DROP TABLE IDRemapper;


--MOVE
--UPDATE Building_SeaPlotYieldChanges SET Yield=2 WHERE YieldType='YIELD_FOOD' AND BuildingType='BUILDING_LIGHTHOUSE'
--INSERT INTO Building_SeaPlotYieldChanges (BuildingType,YieldType,Yield) VALUES ('BUILDING_HARBOR','YIELD_FOOD',1)

--

INSERT INTO EaDebugTableCheck(FileName) SELECT 'Terrain.sql';