-- Contains Traits and subtables
-- Must load after Civilizations.sql

DELETE FROM Traits WHERE Type != 'TRAIT_LONG_COUNT';	--need this in the table or Dll gives effect to all
UPDATE Traits SET PrereqTech = NULL;

INSERT INTO Traits (Type, Description, ShortDescription)
SELECT DISTINCT TraitType, 'TXT_KEY_EA_NOTSHOWN', 'TXT_KEY_EA_NOTSHOWN' FROM Civilization_Traits UNION ALL
SELECT DISTINCT TraitType, 'TXT_KEY_EA_NOTSHOWN', 'TXT_KEY_EA_NOTSHOWN' FROM Leader_Traits;

--fixinator
CREATE TABLE IDRemapper ( id INTEGER PRIMARY KEY AUTOINCREMENT, Type TEXT );
INSERT INTO IDRemapper (Type) SELECT Type FROM Traits ORDER BY ID;
UPDATE Traits SET ID =	( SELECT IDRemapper.id-1 FROM IDRemapper WHERE Traits.Type = IDRemapper.Type);
DROP TABLE IDRemapper;

--We now have a trait for each Race and one for each EaCiv, plus Generic; modify these as needed here
UPDATE Traits SET StaysAliveZeroCities = 1 WHERE Type IN ('TRAIT_THE_FAY', 'TRAIT_ANIMALS');

UPDATE Traits SET FreeBuilding = 'BUILDING_IKKOS' WHERE Type = 'TRAIT_IKKOS';
UPDATE Traits SET FreeBuilding = 'BUILDING_AB' WHERE Type = 'TRAIT_AB';
UPDATE Traits SET FreeBuilding = 'BUILDING_FOMHOIRE' WHERE Type = 'TRAIT_FOMHOIRE';
UPDATE Traits SET FreeBuilding = 'BUILDING_NEITH' WHERE Type = 'TRAIT_NEITH';
UPDATE Traits SET FreeBuilding = 'BUILDING_BREWERY' WHERE Type = 'TRAIT_NINKASI';
UPDATE Traits SET FreeBuilding = 'BUILDING_MONASTERY' WHERE Type = 'TRAIT_ANAPHORA';
UPDATE Traits SET FreeBuilding = 'BUILDING_MAMONAS' WHERE Type = 'TRAIT_MAMONAS';

UPDATE Traits SET FreeBuilding = 'BUILDING_1C_ANIMAL_RESOURCES' WHERE Type = 'TRAIT_BANBA';
UPDATE Traits SET FreeBuilding = 'BUILDING_1C_PLANT_RESOURCES' WHERE Type = 'TRAIT_ERIU';
UPDATE Traits SET FreeBuilding = 'BUILDING_1C_EARTH_RESOURCES' WHERE Type = 'TRAIT_FODLA';




UPDATE Traits SET FreeBuilding = 'BUILDING_MAYD' WHERE Type = 'TRAIT_MAYD';

UPDATE Traits SET FreeBuilding = 'BUILDING_MARKETPLACE' WHERE Type = 'TRAIT_TYRE';
UPDATE Traits SET FreeBuilding = 'BUILDING_FORGE' WHERE Type = 'TRAIT_GERZAH';
UPDATE Traits SET FreeBuilding = 'BUILDING_HARBOR' WHERE Type = 'TRAIT_HY_BREASIL';

UPDATE Traits SET FaithFromKills = 100 WHERE Type IN ('TRAIT_STYGIA', 'TRAIT_MORIQUENDI', 'TRAIT_ISALLIN');
UPDATE Traits SET PlotBuyCostModifier = -33, PlotCultureCostModifier = -33 WHERE Type = 'TRAIT_REYNES';
UPDATE Traits SET WorkerSpeedModifier = 20 WHERE Type = 'TRAIT_NEZELIBA';
UPDATE Traits SET PlunderModifier = 200 WHERE Type IN ('TRAIT_NEMEDIA', 'TRAIT_MORRIGNA');
UPDATE Traits SET GoldenAgeCombatModifier = 33 WHERE Type IN ('TRAIT_MACHAE', 'TRAIT_MILESIA');
UPDATE Traits SET FightWellDamaged = 1 WHERE Type IN ('TRAIT_ULFHETHNAR', 'TRAIT_BODWA');


--
--
--TRAIT_

--subtables
DELETE FROM Trait_FreeResourceFirstXCities;
INSERT INTO Trait_FreeResourceFirstXCities (TraitType, ResourceType,	ResourceQuantity,	NumCities) VALUES
('TRAIT_GRAEAE',		'RESOURCE_MOLY',			1,		6	);



DELETE FROM Trait_FreePromotionUnitCombats;
INSERT INTO Trait_FreePromotionUnitCombats (TraitType, UnitCombatType,	PromotionType) VALUES
('TRAIT_CRECY',			'UNITCOMBAT_ARCHER',		'PROMOTION_STRONG_ARCHER'	),
('TRAIT_CRECY',			'UNITCOMBAT_GUN',			'PROMOTION_STRONG_ARCHER'	),
('TRAIT_SISUKAS',		'UNITCOMBAT_MELEE',			'PROMOTION_STRONG_INFANTRY'	),
('TRAIT_PHRYGES',		'UNITCOMBAT_MOUNTED',		'PROMOTION_STRONG_CAVALRY'	),
('TRAIT_PHRYGES',		'UNITCOMBAT_GUN',			'PROMOTION_STRONG_CAVALRY'	);


DELETE FROM Trait_ImprovementYieldChanges;
INSERT INTO Trait_ImprovementYieldChanges (TraitType, ImprovementType, YieldType, Yield) VALUES
('TRAIT_FIR_BOLG',		'IMPROVEMENT_PASTURE',			'YIELD_PRODUCTION',	1	),
('TRAIT_FIR_BOLG',		'IMPROVEMENT_PASTURE',			'YIELD_GOLD',		1	),
('TRAIT_CRUITHNI',		'IMPROVEMENT_CAMP',				'YIELD_FOOD',		1	),
('TRAIT_CRUITHNI',		'IMPROVEMENT_CAMP',				'YIELD_PRODUCTION',	1	),
('TRAIT_ELEUTHERIOS',	'IMPROVEMENT_VINEYARD',			'YIELD_GOLD',		2	),
('TRAIT_ELEUTHERIOS',	'IMPROVEMENT_VINEYARD',			'YIELD_CULTURE',	2	),
('TRAIT_DAGGOO',		'IMPROVEMENT_WHALING_BOATS',	'YIELD_FOOD',		1	),
('TRAIT_DAGGOO',		'IMPROVEMENT_WHALING_BOATS',	'YIELD_PRODUCTION',	1	),
('TRAIT_DAGGOO',		'IMPROVEMENT_WHALING_BOATS',	'YIELD_CULTURE',	1	),
('TRAIT_ALDEBAR',		'IMPROVEMENT_E_PLANTATION',		'YIELD_CULTURE',	2	),

('TRAIT_GRAEAE',		'IMPROVEMENT_CAMP',				'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_QUARRY',			'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_PASTURE',			'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_WELL',				'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_FISHING_BOATS',	'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_WHALING_BOATS',	'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_VINEYARD',			'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_ORCHARD',			'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_E_PLANTATION',		'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_T_PLANTATION',		'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_GATHERERS_HUT',	'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_BOWYERS_CAMP',		'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_FARM_2',			'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_MINE_2',			'YIELD_FAITH',		1	),
('TRAIT_GRAEAE',		'IMPROVEMENT_LUMBERMILL_2',		'YIELD_FAITH',		1	);


DELETE FROM Trait_MaintenanceModifierUnitCombats;
INSERT INTO Trait_MaintenanceModifierUnitCombats (TraitType,	UnitCombatType, MaintenanceModifier) VALUES
('TRAIT_PHRYGES',		'UNITCOMBAT_MOUNTED',		-33	),
('TRAIT_PHRYGES',		'UNITCOMBAT_GUN',			-33	);


DELETE FROM Trait_NoTrain;
INSERT INTO Trait_NoTrain (TraitType, UnitClassType) VALUES
('TRAIT_GENERIC',		'UNITCLASS_SETTLERS_MAN'),
('TRAIT_GENERIC',		'UNITCLASS_SETTLERS_SIDHE'),
('TRAIT_GENERIC',		'UNITCLASS_SETTLERS_ORC');


DELETE FROM Trait_SpecialistYieldChanges;
INSERT INTO Trait_SpecialistYieldChanges (TraitType, SpecialistType, YieldType, Yield) VALUES
('TRAIT_BJARMALAND',	'SPECIALIST_SMITH',		'YIELD_PRODUCTION',	1),
('TRAIT_BJARMALAND',	'SPECIALIST_TRADER',	'YIELD_GOLD',		1),
('TRAIT_BJARMALAND',	'SPECIALIST_SCRIBE',	'YIELD_SCIENCE',	1),
('TRAIT_BJARMALAND',	'SPECIALIST_ARTISAN',	'YIELD_CULTURE',	1),
('TRAIT_BJARMALAND',	'SPECIALIST_DISCIPLE',	'YIELD_FAITH',		1),
('TRAIT_BJARMALAND',	'SPECIALIST_ADEPT',		'YIELD_FAITH',		1);



--unused:
DELETE FROM Trait_ExtraYieldThresholds;

DELETE FROM Trait_FreePromotions;	--not in dll


DELETE FROM Trait_MovesChangeUnitCombats;

DELETE FROM Trait_ResourceQuantityModifiers;
DELETE FROM Trait_Terrains;
DELETE FROM Trait_UnimprovedFeatureYieldChanges;
DELETE FROM Trait_YieldChanges;
DELETE FROM Trait_YieldChangesIncomingTradeRoute;
DELETE FROM Trait_YieldChangesNaturalWonder;
DELETE FROM Trait_YieldChangesPerTradePartner;
DELETE FROM Trait_YieldChangesStrategicResources;
DELETE FROM Trait_YieldModifiers;


INSERT INTO EaDebugTableCheck(FileName) SELECT 'Traits.sql';